import { describe, expect, it, vi } from "vitest";
import { ProjectBuilder } from "../../../builder/ProjectBuilder";
import { architectureInput, environmentInput, hardwareInput, ids, infrastructureInput, moduleInput, partInput, projectInput } from "../../../builder/tests/fixture";
import type { Project } from "../../../builder/types/ProjectTypes";
import { Bridge } from "../../../bridge/Bridge";
import { ProjectCodec } from "../../../codec/ProjectCodec";
import { MobiOrigin } from "../../../origin/MobiOrigin";
import { SyncOrchestrator } from "../../../orchestrator/SyncOrchestrator";
import { SyncManager } from "../../../sync/SyncManager";
import { TransactionEngine } from "../../../transaction/TransactionEngine";
import { MobiConstructor } from "../../mobi-constructor/src/MobiConstructor";
import type { ConstructionDescriptor } from "../../mobi-constructor/src/interfaces/ConstructorTypes";
import { DinaboxAdapter } from "../../mobi-dinabox-adapter/src/DinaboxAdapter";
import type { AdapterInput, DinaboxProjectInput } from "../../mobi-dinabox-adapter/src/interfaces/DinaboxAdapterTypes";
import { DivergenceAnalyzer } from "../src/divergence/DivergenceAnalyzer";
import { DivergenceReporter } from "../src/divergence/DivergenceReporter";
import { DivergenceResolver } from "../src/divergence/DivergenceResolver";
import { MobiDinaEvent } from "../src/events/MobiDinaEvent";
import { MobiDinaEventBus } from "../src/events/MobiDinaEventBus";
import { IntegrationController } from "../src/IntegrationController";
import { IntegrationRepository } from "../src/IntegrationRepository";
import { MobiDina } from "../src/MobiDina";
import { MobiDina as PublicMobiDina } from "../src/index";
import { DinaboxProjectMapper } from "../src/mapping/DinaboxProjectMapper";
import { HardwareMapper } from "../src/mapping/HardwareMapper";
import { MaterialMapper } from "../src/mapping/MaterialMapper";
import { MobiProjectMapper } from "../src/mapping/MobiProjectMapper";
import { MobiDinaSession } from "../src/MobiDinaSession";
import { SynchronizationContext } from "../src/SynchronizationContext";
import { SynchronizationReport } from "../src/SynchronizationReport";
import { SynchronizationResult } from "../src/SynchronizationResult";
import type { MobiDinaDependencies, SynchronizationInput } from "../src/interfaces/MobiDinaTypes";
import { SyncCoordinator } from "../src/synchronization/SyncCoordinator";
import { SyncExecution } from "../src/synchronization/SyncExecution";
import { SyncPlanner } from "../src/synchronization/SyncPlanner";
import { HardwareValidation } from "../src/validation/HardwareValidation";
import { SynchronizationValidation } from "../src/validation/SynchronizationValidation";

function project(): Project { return new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addArchitecture(ids.environment, architectureInput).addInfrastructure(ids.environment, infrastructureInput).addModule(ids.environment, moduleInput).addPart(ids.module, partInput).addHardware(ids.module, hardwareInput).build(); }
function descriptor(name = projectInput.displayName): ConstructionDescriptor { return { project: { ...structuredClone(projectInput), displayName: name }, environments: [{ environment: structuredClone(environmentInput), architectures: [structuredClone(architectureInput)], infrastructures: [structuredClone(infrastructureInput)], modules: [{ module: structuredClone(moduleInput), parts: [structuredClone(partInput)], hardwares: [structuredClone(hardwareInput)] }] }] }; }
function dinabox(name = "Changed by Dinabox"): DinaboxProjectInput { return { id: "dinabox-project", name: "Dinabox kitchen", modules: [{ id: "dm", name: "Module", cabinets: [{ id: "dc", name: "Cabinet", parts: [{ id: "dp", name: "Part", materialId: "MDF", thickness: 15, orientation: "vertical" }], hardware: [{ id: "dh", name: "Dowel", catalogId: "CAVILHA-8X30", hostId: "dp" }] }] }], materials: [{ id: "MDF", name: "MDF", thickness: 15 }], parameters: { width: 600 }, metadata: { mobiConstructionDescriptor: descriptor(name) } }; }
function adapterInput(name?: string): AdapterInput { return { project: dinabox(name), transactionId: "mobidina-tx", logicalTimestamp: 10 }; }
function setup() { const origin = new MobiOrigin(); origin.openProject(ProjectCodec.serialize(project())); const syncManager = new SyncManager(origin); const adapter = new DinaboxAdapter(new MobiConstructor()); const dependencies: MobiDinaDependencies = { origin, syncManager, adapter, transactionEngine: new TransactionEngine(origin), orchestrator: new SyncOrchestrator(syncManager), bridge: new Bridge(origin) }; return { origin, dependencies, app: new MobiDina(dependencies) }; }
function syncInput(overrides: Partial<SynchronizationInput> = {}): SynchronizationInput { return { adapterInput: adapterInput(), mode: "IMPORT", confirmed: false, author: "tester", ...overrides }; }

describe("MobiDina Foundation v1", () => {
  it("exports and initializes the vertical integration", () => { const { dependencies } = setup(); expect(new PublicMobiDina(dependencies)).toBeInstanceOf(MobiDina); });
  it("creates and closes all composed sessions with events", () => { const { app, dependencies } = setup(); const listener = vi.fn(); app.subscribe(listener); expect(app.createSession("s").active).toBe(true); expect(dependencies.syncManager.getSession().active).toBe(true); expect(dependencies.bridge.getState().session?.open).toBe(true); app.unsubscribe(listener); app.subscribe(listener); expect(app.closeSession().active).toBe(false); expect(listener).toHaveBeenCalledWith(expect.objectContaining({ type: "SESSION_STARTED" })); });
  it("requires explicit confirmation and never changes Origin automatically", () => { const { app, origin } = setup(); app.createSession("s"); const before = origin.getProject(); const result = app.synchronize(syncInput()); expect(result.status).toBe("CONFIRMATION_REQUIRED"); expect(result.divergence?.state).toBe("DIVERGENT"); expect(result.request?.status).toBe("PREPARED"); expect(origin.getProject()).toEqual(before); });
  it("commits confirmed import only through Transaction Engine", () => { const { app, origin } = setup(); app.createSession("s"); const result = app.synchronize(syncInput({ confirmed: true })); expect(result.status).toBe("COMMITTED"); expect(result.transaction?.log.operations).toEqual(["mobidina-sync"]); expect(origin.getProject().displayName).toBe("Changed by Dinabox"); expect(result.report.statistics.divergences).toBe(1); });
  it("rolls back atomically and preserves the prior project", () => { const { app, origin } = setup(); app.createSession("s"); const before = origin.getProject(); const result = app.synchronize(syncInput({ confirmed: true, failOperation: true })); expect(result.status).toBe("ROLLED_BACK"); expect(result.transaction?.log.rollbackExecuted).toBe(true); expect(origin.getProject()).toEqual(before); });
  it("recognizes equal fingerprints without a transaction", () => { const { app } = setup(); app.createSession("s"); const result = app.synchronize(syncInput({ adapterInput: adapterInput(projectInput.displayName), confirmed: true })); expect(result.status).toBe("SYNCHRONIZED"); expect(result.transaction).toBeUndefined(); });
  it("blocks invalid adapter input before divergence or transactions", () => { const { app } = setup(); app.createSession("s"); const invalid = adapterInput(); invalid.project.metadata = {}; const result = app.synchronize(syncInput({ adapterInput: invalid, confirmed: true })); expect(result.status).toBe("BLOCKED"); expect(result.report.statistics.errors).toBe(1); });
  it("classifies and groups project, parameter, material and hardware divergences", () => { const { dependencies } = setup(); dependencies.syncManager.createSession("sync"); const coordinator = new SyncCoordinator(dependencies.syncManager); const analyzer = new DivergenceAnalyzer(); const reports = ["project", "parameter-width", "material-MDF", "hardware-hinge"].map((entity, index) => coordinator.compare(entity, index, index + 1, index, `tx-${index}`)); const classified = reports.map(report => analyzer.analyze(report)); expect(classified.map(item => item.kind)).toEqual(["PROJECT", "PARAMETER", "MATERIAL", "HARDWARE"]); expect(new DivergenceReporter().group(classified).map(group => group.kind)).toEqual(["PROJECT", "PARAMETER", "MATERIAL", "HARDWARE"]); });
  it("honors explicit divergence classification for simultaneous conflicts", () => { const { app } = setup(); app.createSession("s"); const result = app.synchronize(syncInput({ divergenceKind: "HARDWARE" })); expect(result.report.divergences[0]?.kind).toBe("HARDWARE"); });
  it("never offers automatic divergence resolution", () => { const { dependencies } = setup(); dependencies.syncManager.createSession("sync"); const report = new SyncCoordinator(dependencies.syncManager).compare("project", 1, 2, 0, "tx"); const classified = new DivergenceAnalyzer().analyze(report); const resolver = new DivergenceResolver(); expect(resolver.requiresConfirmation(classified)).toBe(true); expect(() => resolver.resolve()).toThrow("never resolves"); });
  it("consumes official Hardware Rules without modifying hardware", () => { const valid = project(); const original = structuredClone(valid); expect(new HardwareValidation().validate(valid).valid).toBe(true); valid.environments[0]!.modules[0]!.hardwares[0]!.catalogId = ""; const result = new HardwareValidation().validate(valid); expect(result.valid).toBe(false); expect(result.issues.some(item => item.code === "HARDWARE_INVALID_CATALOG")).toBe(true); expect(original.environments[0]!.modules[0]!.hardwares[0]!.catalogId).toBe("CAVILHA-8X30"); });
  it("maps Dinabox, Mobi, hardware and materials defensively", () => { const source = dinabox(); const mapped = new DinaboxProjectMapper().map(source); mapped.name = "changed"; expect(source.name).toBe("Dinabox kitchen"); const mobi = project(); const mobiCopy = new MobiProjectMapper().map(mobi); mobiCopy.displayName = "changed"; expect(mobi.displayName).not.toBe("changed"); expect(new HardwareMapper().fromMobi(mobi)[0]).toMatchObject({ catalogId: "CAVILHA-8X30" }); expect(new MaterialMapper().fromMobi(mobi)[0]).toMatchObject({ materialId: "MDF-15", thickness: 15 }); });
  it("provides deterministic plans for import, update, reconciliation and incremental sync", () => { const planner = new SyncPlanner(); for (const mode of ["IMPORT", "UPDATE", "RECONCILE", "INCREMENTAL"] as const) expect(planner.plan(mode)).toMatchObject({ mode, requiresConfirmation: true }); });
  it("validates synchronization context prerequisites", () => { const context = new SynchronizationContext(syncInput()); expect(() => new SynchronizationValidation().validate(context)).toThrow("source"); context.sourceProject = project(); expect(() => new SynchronizationValidation().validate(context)).toThrow("destination"); context.destinationProject = project(); expect(() => new SynchronizationValidation().validate(context)).toThrow("divergence"); expect(() => new SynchronizationContext(syncInput({ author: "" }))).toThrow("author"); expect(context.get().input.author).toBe("tester"); });
  it("isolates reports, results and repository history", () => { const times = [1, 2]; const report = new SynchronizationReport(() => times.shift() ?? 2); report.add({ stage: "VALIDATION", code: "HARDWARE_X", message: "x", severity: "warning", entity: "h" }); const snapshot = report.get(); expect(snapshot).toMatchObject({ durationMs: 1, statistics: { hardwareIssues: 1, warnings: 1 } }); const defaultReport = new SynchronizationReport(); defaultReport.add({ stage: "ADAPTER", code: "X", message: "x", severity: "info", entity: "x" }); expect(defaultReport.get().durationMs).toBe(0); const result = new SynchronizationResult({ success: false, status: "BLOCKED", report: snapshot }).get(); const repository = new IntegrationRepository(); expect(repository.get().lastResult).toBeNull(); repository.save(result); result.report.entries.length = 0; expect(repository.get().lastResult?.report.entries).toHaveLength(1); repository.clear(); expect(repository.get().history).toHaveLength(0); });
  it("provides isolated EventBus and session contracts", () => { const bus = new MobiDinaEventBus(); const first = vi.fn((event) => { event.sessionId = "changed"; }); const second = vi.fn(); bus.subscribe(first); bus.subscribe(second); bus.publish(new MobiDinaEvent("SYNC_STARTED", "s", 0, "tx").get()); expect(second).toHaveBeenCalledWith(expect.objectContaining({ sessionId: "s", transactionId: "tx" })); bus.unsubscribe(first); bus.clear(); expect(() => new MobiDinaEvent("SYNC_STARTED", "s", -1)).toThrow("non-negative"); const session = new MobiDinaSession(); expect(() => session.create(" ")).toThrow("empty"); expect(() => session.close()).toThrow("No active"); session.create("s"); expect(session.require()).toBe("s"); });
  it("guards inactive use and exposes defensive integration state", () => { const { app } = setup(); expect(() => app.synchronize(syncInput())).toThrow("No active"); app.createSession("s"); const value = app.synchronize(syncInput()); const state = app.getState(); state.history.length = 0; expect(app.getState().history).toHaveLength(1); expect(value.adapterResult?.success).toBe(true); });
  it("supports standalone Adapter and Transaction integration controllers", () => { const { dependencies, origin } = setup(); dependencies.adapter.createSession("adapter"); const adapted = new IntegrationController(dependencies.adapter).import(adapterInput()); expect(adapted.success).toBe(true); const execution = new SyncExecution(dependencies.transactionEngine); const result = execution.execute(adapted.transactionRequest!, adapted.constructorResult!.entity!, "tester"); expect(result.status).toBe("COMMITTED"); expect(origin.getProject().displayName).toBe("Changed by Dinabox"); });
});
