import type { Camera, Scene } from "three";
import { describe, expect, it } from "vitest";
import { ProjectBuilder } from "../../../builder/ProjectBuilder";
import { environmentInput, ids, projectInput } from "../../../builder/tests/fixture";
import { MobiCopilot } from "../../../copilot/MobiCopilot";
import { RuleRegistry } from "../../../copilot/rules/RuleRegistry";
import { RuleRunner } from "../../../copilot/rules/RuleRunner";
import { MobiOrigin } from "../../../origin/MobiOrigin";
import { PresentationCore } from "../../../presentation/PresentationCore";
import { MobiStudio } from "../../../studio/MobiStudio";
import { SyncManager } from "../../../sync/SyncManager";
import { Viewer } from "../../../viewer/Viewer";
import type { FrameScheduler, RenderBackend } from "../../../viewer/interfaces/ViewerTypes";
import { MobiStudioApplication } from "../../mobi-studio/src/MobiStudioApplication";
import { toArchitecture } from "../../mobi-studio-walls/src/WallGeometry";
import type { WallDescriptor } from "../../mobi-studio-walls/src/WallTypes";
import { OpeningRule } from "../src/OpeningRule";
import { OpeningAwareWallsController } from "../src/OpeningAwareWallsController";
import { fromOpeningArchitecture, openingOffset, pointOnWall, toOpeningArchitecture } from "../src/OpeningGeometry";
import { OpeningPresentation } from "../src/OpeningPresentation";
import type { OpeningDescriptor } from "../src/OpeningTypes";
import { OpeningValidator } from "../src/OpeningValidator";
import { OpeningsController } from "../src/OpeningsController";

class Backend implements RenderBackend { render(_scene: Scene, _camera: Camera) {} setSize() {} dispose() {} }
class Scheduler implements FrameScheduler { request() { return 1; } cancel() {} }
const wallId = "40000000-0000-4000-8000-000000000001";
const openingId = (n: number) => `50000000-0000-4000-8000-${n.toString().padStart(12, "0")}`;
const wall: WallDescriptor = { id: wallId, environmentId: ids.environment, start: { x: 0, y: 0, z: 0 }, end: { x: 4000, y: 0, z: 0 }, height: 2700, thickness: 120, finish: "paint" };
const opening = (n = 1): OpeningDescriptor => ({ id: openingId(n), environmentId: ids.environment, hostWallId: wallId, offset: 500, sillHeight: 900, width: 1000, height: 1200, finish: "raw" });

function setup() {
  const origin = new MobiOrigin(), foundation = new MobiStudio(origin), presentation = new PresentationCore(); presentation.createSession("p");
  const viewer = new Viewer(presentation, new Backend(), new Scheduler()), copilot = new MobiCopilot(origin, foundation), sync = new SyncManager(origin);
  const studio = new MobiStudioApplication({ origin, foundation, presentation, viewer, copilot, sync }); studio.startSession("s");
  const project = new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).build(); project.environments[0]!.architectures.push(toArchitecture(wall)); foundation.openProject(JSON.stringify(project));
  const registry = new RuleRegistry(); registry.registerRule(new OpeningRule());
  const runner = new RuleRunner(registry);
  return { controller: new OpeningsController(studio, runner), walls: new OpeningAwareWallsController(studio, runner), origin, foundation, studio };
}

describe("mobi-studio-openings", () => {
  it("creates an Opening with mandatory wall host through the transaction pipeline", () => { const { controller, origin } = setup(); expect(controller.create(opening(), "u", 1).success).toBe(true); expect(origin.getProject().environments[0]!.architectures[1]).toMatchObject({ type: "opening", hostId: wallId, parentId: ids.environment }); });
  it("edits position and height", () => { const { controller } = setup(); const value = opening(); controller.create(value, "u", 1); expect(controller.update({ ...value, offset: 700, sillHeight: 800, height: 1300 }, "u", 2).success).toBe(true); expect(controller.get(ids.environment, value.id)).toMatchObject({ offset: 700, sillHeight: 800, height: 1300 }); });
  it("moves and resizes", () => { const { controller } = setup(); const value = opening(); controller.create(value, "u", 1); expect(controller.move(value.id, ids.environment, 1000, 500, "u", 2).success).toBe(true); expect(controller.resize(value.id, ids.environment, 800, 1000, "u", 3).success).toBe(true); expect(controller.get(ids.environment, value.id)).toMatchObject({ offset: 1000, sillHeight: 500, width: 800, height: 1000 }); });
  it("deletes", () => { const { controller, origin } = setup(); const value = opening(); controller.create(value, "u", 1); expect(controller.delete(ids.environment, value.id, "u", 2).success).toBe(true); expect(origin.getProject().environments[0]!.architectures.filter(value => value.type === "opening")).toHaveLength(0); });
  it("requires a valid HostWallID", () => { const { controller } = setup(); expect(controller.create({ ...opening(), hostWallId: "" }, "u", 1).success).toBe(false); expect(controller.create({ ...opening(), hostWallId: openingId(99) }, "u", 2).success).toBe(false); });
  it("rejects fully and partially out-of-bounds Openings", () => { const { controller } = setup(); expect(controller.create({ ...opening(), offset: 5000 }, "u", 1).success).toBe(false); expect(controller.create({ ...opening(), offset: 3500, width: 1000 }, "u", 2).success).toBe(false); expect(controller.create({ ...opening(), sillHeight: 2000, height: 1000 }, "u", 3).success).toBe(false); });
  it("supports multiple non-overlapping Openings and rejects overlap", () => { const { controller } = setup(); expect(controller.create(opening(1), "u", 1).success).toBe(true); expect(controller.create({ ...opening(2), offset: 2000 }, "u", 2).success).toBe(true); expect(controller.create({ ...opening(3), offset: 1000 }, "u", 3).success).toBe(false); });
  it("undoes and redoes committed Opening changes", () => { const { controller } = setup(); const value = opening(); controller.create(value, "u", 1); controller.move(value.id, ids.environment, 1200, 900, "u", 2); expect(controller.undo("u", 3).success).toBe(true); expect(controller.get(ids.environment, value.id)!.offset).toBeCloseTo(500); expect(controller.redo("u", 4).success).toBe(true); expect(controller.get(ids.environment, value.id)!.offset).toBeCloseTo(1200); });
  it("validates malformed dimensions and duplicate identity", () => { const { controller, foundation } = setup(); expect(controller.create({ ...opening(), width: 0 }, "u", 1).success).toBe(false); const value = opening(); controller.create(value, "u", 2); expect(controller.create(value, "u", 3).success).toBe(false); const environment = foundation.getProject().environments[0]!; expect(new OpeningValidator().validateEnvironment(environment).valid).toBe(true); });
  it("reattributes Openings to the compatible segment after Split Wall", () => { const { controller, walls } = setup(); const left = opening(1), right = { ...opening(2), offset: 2500 }; controller.create(left, "u", 1); controller.create(right, "u", 2); expect(walls.splitWall(ids.environment, wallId, { x: 2000, y: 0, z: 0 }, [openingId(20), openingId(21)], "u", 3).success).toBe(true); expect(controller.get(ids.environment, left.id)).toMatchObject({ hostWallId: openingId(20), offset: 500 }); expect(controller.get(ids.environment, right.id)).toMatchObject({ hostWallId: openingId(21), offset: 500 }); });
  it("rolls back Split Wall when an Opening crosses the split", () => { const { controller, walls, origin } = setup(); const value = { ...opening(), offset: 1500, width: 1000 }; controller.create(value, "u", 1); const before = origin.getProject(); expect(walls.splitWall(ids.environment, wallId, { x: 2000, y: 0, z: 0 }, [openingId(20), openingId(21)], "u", 2).success).toBe(false); expect(origin.getProject()).toEqual(before); });
  it("preserves Openings and rehosts them after Merge Wall", () => { const { controller, walls, foundation } = setup(); let project = foundation.getProject(), environment = project.environments[0]!, original = environment.architectures[0]!; environment.architectures = [toArchitecture({ ...wall, id: openingId(20), end: { x: 2000, y: 0, z: 0 } }), toArchitecture({ ...wall, id: openingId(21), start: { x: 2000, y: 0, z: 0 } })]; foundation.openProject(JSON.stringify(project)); controller.create({ ...opening(1), hostWallId: openingId(20) }, "u", 1); controller.create({ ...opening(2), hostWallId: openingId(21), offset: 500 }, "u", 2); expect(walls.mergeWalls(ids.environment, [openingId(20), openingId(21)], original.id, "u", 3).success).toBe(true); expect(controller.get(ids.environment, openingId(1))).toMatchObject({ hostWallId: original.id, offset: 500 }); expect(controller.get(ids.environment, openingId(2))).toMatchObject({ hostWallId: original.id, offset: 2500 }); });
  it("deletes hosted Openings in the same cascade transaction", () => { const { controller, walls, origin } = setup(); controller.create(opening(), "u", 1); expect(walls.deleteWall(ids.environment, wallId, "u", 2).success).toBe(true); expect(origin.getProject().environments[0]!.architectures).toHaveLength(0); });
  it("moves Openings geometrically with their Wall", () => { const { controller, walls, origin } = setup(); controller.create(opening(), "u", 1); expect(walls.updateWall({ ...wall, start: { x: 100, y: 0, z: 200 }, end: { x: 4100, y: 0, z: 200 } }, "u", 2).success).toBe(true); const entity = origin.getProject().environments[0]!.architectures.find(value => value.type === "opening")!; expect(entity.position).toMatchObject({ x: 600, y: 900, z: 200 }); });
  it("rolls back Wall resize if a hosted Opening becomes invalid", () => { const { controller, walls, origin } = setup(); controller.create({ ...opening(), offset: 2500 }, "u", 1); const before = origin.getProject(); expect(walls.updateWall({ ...wall, end: { x: 3000, y: 0, z: 0 } }, "u", 2).success).toBe(false); expect(origin.getProject()).toEqual(before); });
  it("rehosts an Opening explicitly", () => { const { controller, foundation } = setup(); const project = foundation.getProject(), environment = project.environments[0]!; environment.architectures.push(toArchitecture({ ...wall, id: openingId(20), start: { x: 0, y: 0, z: 1000 }, end: { x: 4000, y: 0, z: 1000 } })); foundation.openProject(JSON.stringify(project)); const value = opening(); controller.create(value, "u", 1); expect(controller.rehost(value.id, ids.environment, openingId(20), 750, "u", 2).success).toBe(true); expect(controller.get(ids.environment, value.id)).toMatchObject({ hostWallId: openingId(20), offset: 750 }); });
  it("returns defensive not-found and empty-history results", () => { const { controller } = setup(); expect(controller.get(ids.environment, openingId(99))).toBeUndefined(); expect(controller.move(openingId(99), ids.environment, 0, 0, "u", 1).code).toBe("OPENING_NOT_FOUND"); expect(controller.resize(openingId(99), ids.environment, 1, 1, "u", 2).code).toBe("OPENING_NOT_FOUND"); expect(controller.rehost(openingId(99), ids.environment, wallId, 0, "u", 3).code).toBe("OPENING_NOT_FOUND"); expect(controller.delete(ids.environment, openingId(99), "u", 4).code).toBe("OPENING_NOT_FOUND"); expect(controller.undo("u", 5).code).toBe("NOTHING_TO_UNDO"); expect(controller.redo("u", 6).code).toBe("NOTHING_TO_REDO"); });
  it("rolls back when RuleRunner rejects an otherwise valid Opening", () => { const s = setup(), registry = new RuleRegistry(); registry.registerRule({ id: "reject", displayName: "Reject", description: "test", severity: "error", enabled: true, analyze: () => [{ code: "REJECT", severity: "error", path: "/", message: "reject" }] }); const controller = new OpeningsController(s.studio, new RuleRunner(registry)), before = s.origin.getProject(); expect(controller.create(opening(), "u", 1).code).toBe("TRANSACTION_ROLLED_BACK"); expect(s.origin.getProject()).toEqual(before); });
  it("checks invalid updates without mutating committed state", () => { const { controller, origin } = setup(), value = opening(); controller.create(value, "u", 1); const before = origin.getProject(); expect(controller.update({ ...value, offset: -10 }, "u", 2).success).toBe(false); expect(controller.update({ ...value, sillHeight: -1 }, "u", 3).success).toBe(false); expect(origin.getProject()).toEqual(before); });
  it("allows vertically separated Openings at the same longitudinal position", () => { const { controller } = setup(); expect(controller.create({ ...opening(1), sillHeight: 0, height: 500 }, "u", 1).success).toBe(true); expect(controller.create({ ...opening(2), sillHeight: 600, height: 500 }, "u", 2).success).toBe(true); });
  it("validates orphan serialized Openings", () => { const { foundation } = setup(), environment = foundation.getProject().environments[0]!, orphan = toOpeningArchitecture(opening(), environment.architectures[0]!); orphan.hostId = openingId(99); environment.architectures.push(orphan); const result = new OpeningValidator().validateEnvironment(environment); expect(result.valid).toBe(false); expect(result.issues[0]!.code).toBe("OPENING_WITHOUT_WALL"); });
  it("covers geometry conversion including degenerate defensive input", () => { const architecture = toArchitecture(wall), entity = toOpeningArchitecture(opening(), architecture); expect(openingOffset(entity, architecture)).toBeCloseTo(500); expect(fromOpeningArchitecture(entity, architecture)).toMatchObject({ offset: 500, sillHeight: 900 }); const degenerate = { ...architecture, referencePlane: structuredClone(architecture.position) }; expect(pointOnWall(degenerate, 100, 10)).toMatchObject({ x: 0, y: 10, z: 0 }); expect(openingOffset(entity, degenerate)).toBe(0); expect(() => toOpeningArchitecture({ ...opening(), hostWallId: "" }, architecture)).toThrow("OPENING_WITHOUT_WALL"); expect(() => toOpeningArchitecture({ ...opening(), height: 0 }, architecture)).toThrow("INVALID_OPENING_DIMENSIONS"); });
  it("builds Opening children under Wall nodes using public Presentation APIs", () => { const { controller, foundation, studio } = setup(), events: string[] = []; controller.create(opening(), "u", 1); studio.viewerHost.presentation.controller.subscribe(event => events.push(event.type)); new OpeningPresentation(studio.viewerHost.presentation).sync(foundation.getProject(), 2); const roots = studio.viewerHost.presentation.repository.scene.get().roots; expect(roots[0]!.children[0]).toMatchObject({ projectEntityId: openingId(1), category: "architecture" }); expect(events).toContain("SceneChanged"); });
  it("covers rejected Wall lifecycle references and geometry", () => { const { walls } = setup(); expect(walls.updateWall({ ...wall, id: openingId(99) }, "u", 1).success).toBe(false); expect(walls.deleteWall(ids.environment, openingId(99), "u", 2).success).toBe(false); expect(walls.splitWall(ids.environment, openingId(99), { x: 1, y: 0, z: 0 }, [openingId(20), openingId(21)], "u", 3).success).toBe(false); expect(walls.splitWall(ids.environment, wallId, { x: 0, y: 0, z: 0 }, [openingId(20), openingId(21)], "u", 4).success).toBe(false); expect(walls.mergeWalls(ids.environment, [wallId, openingId(99)], openingId(22), "u", 5).success).toBe(false); });
  it("covers non-collinear, disconnected and reverse-order merges", () => { const a = setup(); let project = a.foundation.getProject(), environment = project.environments[0]!; environment.architectures.push(toArchitecture({ ...wall, id: openingId(20), start: { x: 4000, y: 0, z: 0 }, end: { x: 4000, y: 0, z: 1000 } })); a.foundation.openProject(JSON.stringify(project)); expect(a.walls.mergeWalls(ids.environment, [wallId, openingId(20)], openingId(21), "u", 1).success).toBe(false); const b = setup(); project = b.foundation.getProject(); environment = project.environments[0]!; environment.architectures.push(toArchitecture({ ...wall, id: openingId(20), start: { x: 5000, y: 0, z: 0 }, end: { x: 6000, y: 0, z: 0 } })); b.foundation.openProject(JSON.stringify(project)); expect(b.walls.mergeWalls(ids.environment, [wallId, openingId(20)], openingId(21), "u", 2).success).toBe(false); const c = setup(); project = c.foundation.getProject(); environment = project.environments[0]!; environment.architectures = [toArchitecture({ ...wall, id: openingId(20), start: { x: 2000, y: 0, z: 0 }, end: { x: 4000, y: 0, z: 0 } }), toArchitecture({ ...wall, id: openingId(21), end: { x: 2000, y: 0, z: 0 } })]; c.foundation.openProject(JSON.stringify(project)); expect(c.walls.mergeWalls(ids.environment, [openingId(20), openingId(21)], wallId, "u", 3).success).toBe(true); });
  it("covers missing hosts, environments and concurrent-edit guard", () => { const s = setup(), value = opening(); const internal = s.controller as unknown as { busy: boolean }; internal.busy = true; expect(s.controller.create(value, "u", 1).code).toBe("EDIT_ALREADY_ACTIVE"); internal.busy = false; expect(s.controller.create({ ...value, environmentId: openingId(90) }, "u", 2).code).toBe("TRANSACTION_ROLLED_BACK"); expect(s.controller.update(value, "u", 3).code).toBe("TRANSACTION_ROLLED_BACK"); expect(s.walls.deleteWall(openingId(90), wallId, "u", 4).code).toBe("TRANSACTION_ROLLED_BACK"); const architecture = toOpeningArchitecture(value, toArchitecture(wall)); architecture.hostId = null; expect(fromOpeningArchitecture(architecture, toArchitecture(wall)).hostWallId).toBe(""); });
  it("preserves failed undo and redo entries for a later retry", () => { const s = setup(); let reject = false; const registry = new RuleRegistry(); registry.registerRule({ id: "toggle", displayName: "Toggle", description: "test", severity: "error", enabled: true, analyze: () => reject ? [{ code: "REJECT", severity: "error", path: "/", message: "reject" }] : [] }); const controller = new OpeningsController(s.studio, new RuleRunner(registry)); controller.create(opening(), "u", 1); reject = true; expect(controller.undo("u", 2).success).toBe(false); reject = false; expect(controller.undo("u", 3).success).toBe(true); reject = true; expect(controller.redo("u", 4).success).toBe(false); reject = false; expect(controller.redo("u", 5).success).toBe(true); });
  it("blocks Wall lifecycle when the resulting project is rejected", () => { const s = setup(), registry = new RuleRegistry(); registry.registerRule({ id: "reject", displayName: "Reject", description: "test", severity: "error", enabled: true, analyze: () => [{ code: "REJECT", severity: "error", path: "/", message: "reject" }] }); const walls = new OpeningAwareWallsController(s.studio, new RuleRunner(registry)), before = s.origin.getProject(); expect(walls.updateWall({ ...wall, start: { x: 10, y: 0, z: 0 }, end: { x: 4010, y: 0, z: 0 } }, "u", 1).success).toBe(false); expect(s.origin.getProject()).toEqual(before); });
});
