import type{Camera,Scene}from"three";import{describe,expect,it}from"vitest";import{ProjectBuilder}from"../../../builder/ProjectBuilder";import{environmentInput,ids,projectInput}from"../../../builder/tests/fixture";import{MobiCopilot}from"../../../copilot/MobiCopilot";import{RuleRegistry}from"../../../copilot/rules/RuleRegistry";import{RuleRunner}from"../../../copilot/rules/RuleRunner";import{MobiOrigin}from"../../../origin/MobiOrigin";import{PresentationCore}from"../../../presentation/PresentationCore";import{MobiStudio}from"../../../studio/MobiStudio";import{SyncManager}from"../../../sync/SyncManager";import{Viewer}from"../../../viewer/Viewer";import type{FrameScheduler,RenderBackend}from"../../../viewer/interfaces/ViewerTypes";import{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import{toArchitecture}from"../../mobi-studio-walls/src/WallGeometry";import type{WallDescriptor}from"../../mobi-studio-walls/src/WallTypes";import{RoomsController}from"../src/RoomsController";import{TopologyRule}from"../src/TopologyRule";import{TopologyValidator}from"../src/TopologyValidator";
class B implements RenderBackend{render(_s:Scene,_c:Camera){}setSize(){}dispose(){}}class S implements FrameScheduler{request(){return 1}cancel(){}}const wid=(n:number)=>`20000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;const wall=(n:number,a:number[],b:number[]):WallDescriptor=>({id:wid(n),environmentId:ids.environment,start:{x:a[0]!,y:0,z:a[1]!},end:{x:b[0]!,y:0,z:b[1]!},height:2700,thickness:100,finish:"paint"});
const rect=()=>[wall(1,[0,0],[10,0]),wall(2,[10,0],[10,10]),wall(3,[10,10],[0,10]),wall(4,[0,10],[0,0])];
function setup(walls=rect()){const origin=new MobiOrigin(),foundation=new MobiStudio(origin),p=new PresentationCore();p.createSession("p");const viewer=new Viewer(p,new B(),new S()),copilot=new MobiCopilot(origin,foundation),sync=new SyncManager(origin),studio=new MobiStudioApplication({origin,foundation,presentation:p,viewer,copilot,sync});studio.startSession("s");const project=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).build();project.environments[0]!.architectures=walls.map(toArchitecture);foundation.openProject(JSON.stringify(project));const reg=new RuleRegistry();reg.registerRule(new TopologyRule());return{c:new RoomsController(studio,new RuleRunner(reg)),origin,foundation,env:project.environments[0]!,studio}}
describe("topology",()=>{
 it("accepts rectangular and polygon loops deterministically",()=>{const{env}=setup();const v=new TopologyValidator(),a=v.validate(env,rect().map(x=>x.id)),b=v.validate(env,rect().map(x=>x.id));expect(a).toEqual(b);expect(a.valid).toBe(true);const pent=[wall(1,[0,0],[4,0]),wall(2,[4,0],[6,3]),wall(3,[6,3],[3,6]),wall(4,[3,6],[0,3]),wall(5,[0,3],[0,0])];const s=setup(pent);expect(v.validate(s.env,pent.map(x=>x.id)).valid).toBe(true)});
 it("detects open, zero, duplicate, overlap, crossing and missing references",()=>{const v=new TopologyValidator();let s=setup(rect().slice(0,3));expect(v.validate(s.env,s.env.architectures.map(x=>x.id)).issues.some(x=>x.code==="OPEN_LOOP")).toBe(true);s=setup([wall(1,[0,0],[1,0])]);s.env.architectures[0]!.referencePlane=structuredClone(s.env.architectures[0]!.position);expect(v.validate(s.env,[wid(1)]).issues.some(x=>x.code==="ZERO_LENGTH_SEGMENT")).toBe(true);s=setup([wall(1,[0,0],[5,0]),wall(2,[5,0],[0,0])]);expect(v.validate(s.env,[wid(1),wid(2)]).issues.some(x=>x.code==="DUPLICATE_WALL")).toBe(true);s=setup([wall(1,[0,0],[10,0]),wall(2,[5,0],[15,0])]);expect(v.validate(s.env,[wid(1),wid(2)]).issues.some(x=>x.code==="OVERLAPPING_WALLS")).toBe(true);s=setup([wall(1,[0,0],[10,10]),wall(2,[0,10],[10,0])]);expect(v.validate(s.env,[wid(1),wid(2)]).issues.some(x=>x.code==="SELF_INTERSECTION")).toBe(true);expect(v.validate(s.env,[wid(9)]).issues[0]!.code).toBe("MISSING_REFERENCE")});
 it("reports illegal L/T/X interior intersections",()=>{const s=setup([wall(1,[0,0],[10,0]),wall(2,[5,-5],[5,5])]);expect(new TopologyValidator().validateConnections(s.env)[0]!.code).toBe("ILLEGAL_INTERSECTION")});
});
describe("rooms",()=>{
 it("formalizes, updates and deletes an Environment room through transactions",()=>{const{c,origin}=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"Kitchen",code:"KITCHEN"};expect(c.create(d,"u",1).success).toBe(true);expect(origin.getProject().environments[0]).toMatchObject({displayName:"Kitchen",code:"ROOM:KITCHEN",status:"validated"});expect(c.update({...d,displayName:"New kitchen"},"u",2).success).toBe(true);expect(c.delete(ids.environment,"u",3).success).toBe(true);expect(origin.getProject().environments[0]!.status).toBe("draft")});
 it("blocks open rooms and missing rooms",()=>{const{c}=setup(rect().slice(0,3)),d={environmentId:ids.environment,wallIds:[wid(1),wid(2),wid(3)],displayName:"Open",code:"OPEN"};expect(c.create(d,"u",1).code).toBe("INVALID_ROOM_TOPOLOGY");expect(c.update(d,"u",2).code).toBe("ROOM_NOT_FOUND");expect(c.delete(ids.environment,"u",3).code).toBe("ROOM_NOT_FOUND")});
 it("detects duplicate room identity",()=>{const{c,foundation}=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"A",code:"A"};const p=foundation.getProject(),copy=structuredClone(p.environments[0]!);copy.id="30000000-0000-4000-8000-000000000001";copy.code="ROOM:A";copy.parentId=p.id;p.environments.push(copy);foundation.openProject(JSON.stringify(p));expect(c.create(d,"u",1).code).toBe("DUPLICATE_ROOM")});
 it("rolls back when a registered rule rejects the proposed room",()=>{const{c,origin}=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"A",code:"A"};const before=origin.getProject();const invalid={...d,wallIds:[...d.wallIds,wid(9)]};expect(c.create(invalid,"u",1).success).toBe(false);expect(origin.getProject()).toEqual(before)});
 it("handles a missing Environment and a non-room TopologyRule branch",()=>{const{c,env}=setup(),missing={environmentId:wid(99),wallIds:[],displayName:"X",code:"X"};expect(c.validate(missing).issues[0]!.code).toBe("MISSING_REFERENCE");const reg=new RuleRegistry();reg.registerRule(new TopologyRule());expect(new RuleRunner(reg).analyze({ ...projectInput,schemaVersion:"1.0.0",measurementUnit:"mm",rotationUnit:"degrees",environments:[env] })).toEqual([])});
 it("rolls back atomically when RuleRunner rejects a valid room",()=>{const{studio,origin}=setup(),reg=new RuleRegistry();reg.registerRule({id:"reject",displayName:"Reject",description:"test",severity:"error",enabled:true,analyze:()=>[{code:"REJECT",severity:"error",path:"/",message:"reject"}]});const c=new RoomsController(studio,new RuleRunner(reg)),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"A",code:"A"},before=origin.getProject();expect(c.create(d,"u",1).code).toBe("TRANSACTION_ROLLED_BACK");expect(origin.getProject()).toEqual(before)});
 it("covers invalid formal-room rules and malformed intent input",()=>{const{c,env}=setup(rect().slice(0,3)),reg=new RuleRegistry();reg.registerRule(new TopologyRule());env.code="ROOM:OPEN";expect(new RuleRunner(reg).analyze({ ...projectInput,schemaVersion:"1.0.0",measurementUnit:"mm",rotationUnit:"degrees",environments:[env] }).length).toBeGreaterThan(0);const valid=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"A",code:"A"};expect(valid.c.create(d,"",1).success).toBe(false)});
 it("rejects topology invalidated after formalization and duplicate update codes",()=>{const s=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"A",code:"A"};s.c.create(d,"u",1);let p=s.foundation.getProject();p.environments[0]!.architectures.pop();s.foundation.openProject(JSON.stringify(p));expect(s.c.update({...d,wallIds:d.wallIds.slice(0,3)},"u",2).code).toBe("INVALID_ROOM_TOPOLOGY");const q=setup();q.c.create(d,"u",1);p=q.foundation.getProject();const copy=structuredClone(p.environments[0]!);copy.id=wid(88);copy.parentId=p.id;copy.code="ROOM:B";p.environments.push(copy);q.foundation.openProject(JSON.stringify(p));expect(q.c.update({...d,code:"B"},"u",2).code).toBe("DUPLICATE_ROOM")});
 it("detects a closed room automatically and refreshes its identity",()=>{const s=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"Office",code:"OFFICE"};expect(s.c.detect(ids.environment)).toEqual([d.wallIds]);expect(s.c.create(d,"u",1).success).toBe(true);expect(s.c.refresh(ids.environment,"u",2).success).toBe(true);expect(s.origin.getProject().environments[0]).toMatchObject({displayName:"Office",code:"ROOM:OFFICE",status:"validated"})});
 it("reports multiple closed rooms as ambiguous",()=>{const second=[wall(5,[20,0],[30,0]),wall(6,[30,0],[30,10]),wall(7,[30,10],[20,10]),wall(8,[20,10],[20,0])],s=setup([...rect(),...second]),ids8=[...rect(),...second].map(x=>x.id),result=new TopologyValidator().validate(s.env,ids8);expect(s.c.detect(ids.environment)).toHaveLength(2);expect(result.valid).toBe(false);expect(result.issues.some(x=>x.code==="AMBIGUOUS_LOOPS")).toBe(true)});
 it("detects rooms independently across multiple environments",()=>{const s=setup(),p=s.foundation.getProject(),copy=structuredClone(p.environments[0]!);copy.id="30000000-0000-4000-8000-000000000002";copy.parentId=p.id;copy.code="SECOND";copy.architectures=copy.architectures.map((a,i)=>({...a,id:wid(i+20),parentId:copy.id}));p.environments.push(copy);s.foundation.openProject(JSON.stringify(p));const detected=s.c.detectAll();expect(detected[ids.environment]).toHaveLength(1);expect(detected[copy.id]).toHaveLength(1)});
 it("refuses refresh and preserves the room after an open-loop mutation",()=>{const s=setup(),d={environmentId:ids.environment,wallIds:rect().map(x=>x.id),displayName:"Safe",code:"SAFE"};s.c.create(d,"u",1);const p=s.foundation.getProject();p.environments[0]!.architectures.pop();s.foundation.openProject(JSON.stringify(p));const before=s.origin.getProject(),result=s.c.refresh(ids.environment,"u",2);expect(result.code).toBe("INVALID_ROOM_TOPOLOGY");expect(s.origin.getProject()).toEqual(before)});
 it("handles absent and empty automatic-detection targets",()=>{const missing=setup();expect(missing.c.detect(wid(99))).toEqual([]);expect(missing.c.refresh(wid(99),"u",1).code).toBe("ROOM_NOT_FOUND");const empty=setup([]);expect(empty.c.detect(ids.environment)).toEqual([]);expect(new TopologyValidator().validate(empty.env,[]).issues.some(x=>x.code==="OPEN_LOOP")).toBe(true)});
 it("covers vertical overlap and branched open geometry",()=>{const vertical=setup([wall(1,[0,0],[0,10]),wall(2,[0,5],[0,15])]);expect(new TopologyValidator().validate(vertical.env,[wid(1),wid(2)]).issues.some(x=>x.code==="OVERLAPPING_WALLS")).toBe(true);const branch=setup([wall(1,[0,0],[5,0]),wall(2,[5,0],[10,0]),wall(3,[5,0],[5,5])]);expect(new TopologyValidator().validate(branch.env,[wid(1),wid(2),wid(3)]).valid).toBe(false)});
});
