import type { Architecture, Project } from "../../../builder/types/ProjectTypes";
import { RuleContext } from "../../../copilot/rules/RuleContext";
import type { RuleRunner } from "../../../copilot/rules/RuleRunner";
import type { MobiStudioApplication } from "../../mobi-studio/src/MobiStudioApplication";
import type { EditIntentInput } from "../../mobi-studio/src/interfaces/StudioApplicationTypes";
import { fromOpeningArchitecture, toOpeningArchitecture } from "./OpeningGeometry";
import type { OpeningDescriptor, OpeningHistoryEntry, OpeningOperation, OpeningResult } from "./OpeningTypes";
import { OpeningValidator } from "./OpeningValidator";

export class OpeningsController {
  private readonly undoStack: OpeningHistoryEntry[] = []; private readonly redoStack: OpeningHistoryEntry[] = []; private busy = false;
  constructor(private readonly studio: MobiStudioApplication, private readonly rules: RuleRunner, private readonly validator = new OpeningValidator()) {}
  create(opening: OpeningDescriptor, author: string, timestamp: number): OpeningResult { return this.change("CREATE_OPENING", opening, author, timestamp, project => { const environment = this.environment(project, opening.environmentId); if (!this.validator.validateDescriptor(environment, opening).valid) throw new Error("INVALID_OPENING"); const wall = environment.architectures.find(value => value.id === opening.hostWallId && value.type === "wall")!; environment.architectures.push(toOpeningArchitecture(opening, wall)); }); }
  update(opening: OpeningDescriptor, author: string, timestamp: number): OpeningResult { return this.change("UPDATE_OPENING", opening, author, timestamp, project => this.replace(project, opening)); }
  move(id: string, environmentId: string, offset: number, sillHeight: number, author: string, timestamp: number): OpeningResult { const current = this.get(environmentId, id); if (!current) return { success: false, code: "OPENING_NOT_FOUND" }; return this.change("MOVE_OPENING", { ...current, offset, sillHeight }, author, timestamp, project => this.replace(project, { ...current, offset, sillHeight })); }
  resize(id: string, environmentId: string, width: number, height: number, author: string, timestamp: number): OpeningResult { const current = this.get(environmentId, id); if (!current) return { success: false, code: "OPENING_NOT_FOUND" }; return this.change("RESIZE_OPENING", { ...current, width, height }, author, timestamp, project => this.replace(project, { ...current, width, height })); }
  rehost(id: string, environmentId: string, hostWallId: string, offset: number, author: string, timestamp: number): OpeningResult { const current = this.get(environmentId, id); if (!current) return { success: false, code: "OPENING_NOT_FOUND" }; return this.change("REHOST_OPENING", { ...current, hostWallId, offset }, author, timestamp, project => this.replace(project, { ...current, hostWallId, offset })); }
  delete(environmentId: string, id: string, author: string, timestamp: number): OpeningResult { const current = this.get(environmentId, id); if (!current) return { success: false, code: "OPENING_NOT_FOUND" }; return this.change("DELETE_OPENING", current, author, timestamp, project => { const environment = this.environment(project, environmentId), index = environment.architectures.findIndex(value => value.id === id && value.type === "opening"); environment.architectures.splice(index, 1); }); }
  undo(author: string, timestamp: number): OpeningResult { const entry = this.undoStack.pop(); if (!entry) return { success: false, code: "NOTHING_TO_UNDO" }; const result = this.restore(entry.before, author, timestamp); if (result.success) this.redoStack.push(entry); else this.undoStack.push(entry); return result; }
  redo(author: string, timestamp: number): OpeningResult { const entry = this.redoStack.pop(); if (!entry) return { success: false, code: "NOTHING_TO_REDO" }; const result = this.restore(entry.after, author, timestamp); if (result.success) this.undoStack.push(entry); else this.redoStack.push(entry); return result; }
  get(environmentId: string, id: string): OpeningDescriptor | undefined { const project = this.studio.foundation.getProject(), environment = project.environments.find(value => value.id === environmentId), opening = environment?.architectures.find(value => value.id === id && value.type === "opening"); if (!environment || !opening) return undefined; const wall = environment.architectures.find(value => value.id === opening.hostId && value.type === "wall"); return wall ? fromOpeningArchitecture(opening, wall) : undefined; }
  private replace(project: Project, opening: OpeningDescriptor): void { const environment = this.environment(project, opening.environmentId), index = environment.architectures.findIndex(value => value.id === opening.id && value.type === "opening"); if (index < 0) throw new Error("OPENING_NOT_FOUND"); const validation = this.validator.validateDescriptor(environment, opening, opening.id); if (!validation.valid) throw new Error("INVALID_OPENING"); const wall = environment.architectures.find(value => value.id === opening.hostWallId && value.type === "wall")!; environment.architectures[index] = toOpeningArchitecture(opening, wall); }
  private change(operation: OpeningOperation, opening: OpeningDescriptor, author: string, timestamp: number, mutate: (project: Project) => void): OpeningResult { if (this.busy) return { success: false, code: "EDIT_ALREADY_ACTIVE" }; const before = this.openings(this.studio.foundation.getProject()); const result = this.transact(operation, opening.id, opening, author, timestamp, mutate); if (result.success) { this.undoStack.push({ before, after: this.openings(this.studio.foundation.getProject()) }); this.redoStack.length = 0; } return result; }
  private restore(snapshot: Architecture[], author: string, timestamp: number): OpeningResult { return this.transact("UPDATE_OPENING", "opening-history", snapshot, author, timestamp, project => { for (const environment of project.environments) environment.architectures = environment.architectures.filter(value => value.type !== "opening"); for (const opening of snapshot) this.environment(project, opening.parentId).architectures.push(structuredClone(opening)); }); }
  private transact(operationName: OpeningOperation, entityId: string, value: unknown, author: string, timestamp: number, mutate: (project: Project) => void): OpeningResult { this.busy = true; try { const input: EditIntentInput = { id: `${operationName}:${entityId}:${timestamp}`, entityId, property: "architecture.opening", value: structuredClone(value), author, logicalTimestamp: timestamp, operationName, operation: origin => { const project = origin.getProject(); mutate(project); const validation = project.environments.flatMap(environment => this.validator.validateEnvironment(environment).issues); if (validation.length) throw new Error("INVALID_OPENING"); if (this.rules.runAll(new RuleContext(project)).some(result => result.severity === "error")) throw new Error("RULE_VALIDATION_FAILED"); origin.openProject(JSON.stringify(project)); }, preview: { apply: () => {}, revert: () => {} } }; this.studio.beginEdit(input); const transaction = this.studio.commitEdit(); return { success: transaction.success, code: transaction.success ? "COMMITTED" : "TRANSACTION_ROLLED_BACK", transaction }; } catch (error) { return { success: false, code: (error as Error).message }; } finally { this.busy = false; } }
  private openings(project: Project): Architecture[] { return project.environments.flatMap(environment => environment.architectures.filter(value => value.type === "opening").map(value => structuredClone(value))); }
  private environment(project: Project, id: string) { const environment = project.environments.find(value => value.id === id); if (!environment) throw new Error("ENVIRONMENT_NOT_FOUND"); return environment; }
}
