import type { Architecture, Environment, Project, Vector3 } from "../../../builder/types/ProjectTypes";
import { RuleContext } from "../../../copilot/rules/RuleContext";
import type { RuleRunner } from "../../../copilot/rules/RuleRunner";
import type { MobiStudioApplication } from "../../mobi-studio/src/MobiStudioApplication";
import type { EditIntentInput } from "../../mobi-studio/src/interfaces/StudioApplicationTypes";
import { collinear, fromArchitecture, samePoint, toArchitecture, wallLength } from "../../mobi-studio-walls/src/WallGeometry";
import type { WallDescriptor, WallResult } from "../../mobi-studio-walls/src/WallTypes";
import { fromOpeningArchitecture, toOpeningArchitecture } from "./OpeningGeometry";
import { OpeningValidator } from "./OpeningValidator";

const EPS = 1e-7;
export class OpeningAwareWallsController {
  constructor(private readonly studio: MobiStudioApplication, private readonly rules: RuleRunner, private readonly validator = new OpeningValidator()) {}
  updateWall(wall: WallDescriptor, author: string, timestamp: number): WallResult { return this.transact("UPDATE_WALL", wall.id, wall, author, timestamp, project => { const environment = this.environment(project, wall.environmentId), index = environment.architectures.findIndex(value => value.id === wall.id && value.type === "wall"); if (index < 0) throw new Error("WALL_NOT_FOUND"); const oldWall = environment.architectures[index]!, openings = this.hosted(environment, wall.id).map(opening => fromOpeningArchitecture(opening, oldWall)); environment.architectures[index] = toArchitecture(wall); for (const descriptor of openings) this.replaceOpening(environment, descriptor, environment.architectures[index]!); }); }
  deleteWall(environmentId: string, wallId: string, author: string, timestamp: number): WallResult { return this.transact("DELETE_WALL", wallId, null, author, timestamp, project => { const environment = this.environment(project, environmentId), index = environment.architectures.findIndex(value => value.id === wallId && value.type === "wall"); if (index < 0) throw new Error("WALL_NOT_FOUND"); environment.architectures = environment.architectures.filter(value => value.id !== wallId && !(value.type === "opening" && value.hostId === wallId)); }); }
  splitWall(environmentId: string, wallId: string, splitPoint: Vector3, newIds: [string, string], author: string, timestamp: number): WallResult { return this.transact("SPLIT_WALL", wallId, splitPoint, author, timestamp, project => { const environment = this.environment(project, environmentId), index = environment.architectures.findIndex(value => value.id === wallId && value.type === "wall"); if (index < 0) throw new Error("WALL_NOT_FOUND"); const old = environment.architectures[index]!, descriptor = fromArchitecture(old), split = wallLength(descriptor.start, splitPoint); if (Math.abs(split + wallLength(splitPoint, descriptor.end) - wallLength(descriptor.start, descriptor.end)) > EPS || split < EPS || wallLength(splitPoint, descriptor.end) < EPS) throw new Error("SPLIT_POINT_OUTSIDE_WALL"); const first = toArchitecture({ ...descriptor, id: newIds[0], end: splitPoint }), second = toArchitecture({ ...descriptor, id: newIds[1], start: splitPoint }); const hosted = this.hosted(environment, wallId).map(opening => fromOpeningArchitecture(opening, old)); environment.architectures.splice(index, 1, first, second); for (const opening of hosted) { if (opening.offset + opening.width <= split + EPS) this.replaceOpening(environment, { ...opening, hostWallId: first.id }, first); else if (opening.offset >= split - EPS) this.replaceOpening(environment, { ...opening, hostWallId: second.id, offset: opening.offset - split }, second); else throw new Error("OPENING_CROSSES_SPLIT"); } }); }
  mergeWalls(environmentId: string, ids: [string, string], newId: string, author: string, timestamp: number): WallResult { return this.transact("MERGE_WALLS", newId, ids, author, timestamp, project => { const environment = this.environment(project, environmentId), firstArchitecture = this.wall(environment, ids[0]), secondArchitecture = this.wall(environment, ids[1]); if (!firstArchitecture || !secondArchitecture) throw new Error("WALL_NOT_FOUND"); const a = fromArchitecture(firstArchitecture), b = fromArchitecture(secondArchitecture); if (!collinear(a, b)) throw new Error("WALLS_NOT_COLLINEAR"); let leading: Architecture, trailing: Architecture, start: Vector3, end: Vector3; if (samePoint(a.end, b.start)) { leading = firstArchitecture; trailing = secondArchitecture; start = a.start; end = b.end; } else if (samePoint(b.end, a.start)) { leading = secondArchitecture; trailing = firstArchitecture; start = b.start; end = a.end; } else throw new Error("WALLS_NOT_CONNECTED"); const leadingDescriptor = fromArchitecture(leading), merged = toArchitecture({ ...leadingDescriptor, id: newId, start, end }), leadingLength = wallLength(start, fromArchitecture(leading).end); const openings = [...this.hosted(environment, leading.id).map(value => ({ value, offset: fromOpeningArchitecture(value, leading).offset })), ...this.hosted(environment, trailing.id).map(value => ({ value, offset: leadingLength + fromOpeningArchitecture(value, trailing).offset }))]; environment.architectures = environment.architectures.filter(value => !ids.includes(value.id)); environment.architectures.push(merged); for (const item of openings) { const descriptor = fromOpeningArchitecture(item.value, item.value.hostId === leading.id ? leading : trailing); this.replaceOpening(environment, { ...descriptor, hostWallId: newId, offset: item.offset }, merged); } }); }
  private replaceOpening(environment: Environment, descriptor: ReturnType<typeof fromOpeningArchitecture>, wall: Architecture): void { const validation = this.validator.validateDescriptor(environment, descriptor, descriptor.id); if (!validation.valid) throw new Error("INVALID_OPENING_AFTER_WALL_CHANGE"); const index = environment.architectures.findIndex(value => value.id === descriptor.id && value.type === "opening"); environment.architectures[index] = toOpeningArchitecture(descriptor, wall); }
  private transact(operationName: string, entityId: string, value: unknown, author: string, timestamp: number, mutate: (project: Project) => void): WallResult { try { const input: EditIntentInput = { id: `${operationName}:${entityId}:${timestamp}`, entityId, property: "architecture.wall.openings", value: structuredClone(value), author, logicalTimestamp: timestamp, operationName, operation: origin => { const project = origin.getProject(); mutate(project); if (project.environments.some(environment => !this.validator.validateEnvironment(environment).valid)) throw new Error("INVALID_OPENING_AFTER_WALL_CHANGE"); if (this.rules.runAll(new RuleContext(project)).some(result => result.severity === "error")) throw new Error("RULE_VALIDATION_FAILED"); origin.openProject(JSON.stringify(project)); }, preview: { apply: () => {}, revert: () => {} } }; this.studio.beginEdit(input); const transaction = this.studio.commitEdit(); return { success: transaction.success, code: transaction.success ? "COMMITTED" : "TRANSACTION_ROLLED_BACK", transaction }; } catch (error) { return { success: false, code: (error as Error).message }; } }
  private hosted(environment: Environment, wallId: string): Architecture[] { return environment.architectures.filter(value => value.type === "opening" && value.hostId === wallId); }
  private wall(environment: Environment, id: string): Architecture | undefined { return environment.architectures.find(value => value.type === "wall" && value.id === id); }
  private environment(project: Project, id: string): Environment { const environment = project.environments.find(value => value.id === id); if (!environment) throw new Error("ENVIRONMENT_NOT_FOUND"); return environment; }
}
