import { describe, expect, it, vi } from "vitest"; import { architectureInput, environmentInput, hardwareInput, ids, infrastructureInput, moduleInput, partInput, projectInput } from "../../../builder/tests/fixture"; import { MobiConstructor } from "../../mobi-constructor/src/MobiConstructor"; import type { ConstructionDescriptor } from "../../mobi-constructor/src/interfaces/ConstructorTypes"; import { AdapterContext } from "../src/AdapterContext"; import { AdapterError } from "../src/AdapterError"; import { AdapterReport } from "../src/AdapterReport"; import { AdapterRepository } from "../src/AdapterRepository"; import { AdapterResult } from "../src/AdapterResult"; import { AdapterSession } from "../src/AdapterSession"; import { AdapterEvent } from "../src/events/AdapterEvent"; import { AdapterEventBus } from "../src/events/AdapterEventBus"; import { ComponentExtractor } from "../src/extraction/ComponentExtractor"; import { EntityExtractor } from "../src/extraction/EntityExtractor"; import { GroupExtractor } from "../src/extraction/GroupExtractor"; import { LayerExtractor } from "../src/extraction/LayerExtractor"; import { MaterialExtractor } from "../src/extraction/MaterialExtractor"; import { MetadataExtractor } from "../src/extraction/MetadataExtractor"; import { ModelExtractor } from "../src/extraction/ModelExtractor"; import { SketchUpAdapter as PublicAdapter } from "../src/index"; import type { AdapterInput, SketchUpModelInput } from "../src/interfaces/SketchUpAdapterTypes"; import { GeometryMapper } from "../src/mapping/GeometryMapper"; import { MaterialMapper } from "../src/mapping/MaterialMapper"; import { MetadataMapper } from "../src/mapping/MetadataMapper"; import { SketchUpInputMapper } from "../src/mapping/SketchUpInputMapper"; import { ConstructorPipeline } from "../src/pipeline/ConstructorPipeline"; import { ExtractionPipeline } from "../src/pipeline/ExtractionPipeline"; import { MappingPipeline } from "../src/pipeline/MappingPipeline"; import { SketchUpAdapter } from "../src/SketchUpAdapter";

const descriptor = (): ConstructionDescriptor => ({ project: structuredClone(projectInput), environments: [{ environment: structuredClone(environmentInput), architectures: [structuredClone(architectureInput)], infrastructures: [structuredClone(infrastructureInput)], modules: [{ module: structuredClone(moduleInput), parts: [structuredClone(partInput)], hardwares: [structuredClone(hardwareInput)] }] }] });
const transform = { matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 20, 30, 1] };
const bounds = { min: { x: 0, y: 0, z: 0 }, max: { x: 100, y: 200, z: 300 } };
const model = (): SketchUpModelInput => ({ id: "skp-model", name: "Kitchen", groups: [{ id: "group-1", kind: "group", name: "Room", bounds, transform, attributes: { dictionary: "value" }, children: [{ id: "component-child", kind: "component", name: "Cabinet", definitionId: "definition-1", materialId: "material-1", layerId: "layer-1", dynamicAttributes: { lenx: 100 }, bounds, transform }] }], components: [{ id: "component-2", kind: "component", name: "Appliance", definitionId: "definition-2" }], materials: [{ id: "material-1", name: "MDF", color: "#ffffff", opacity: 0.8 }], layers: [{ id: "layer-1", name: "Furniture", visible: true }], attributes: { author: "SketchUp" }, metadata: { mobiConstructionDescriptor: descriptor(), source: "explicit" } });
const input = (value = model()): AdapterInput => ({ model: value, transactionId: "adapter-tx-1", logicalTimestamp: 8 });

describe("Mobi SketchUp Adapter Foundation v1", () => {
  it("exports the official public entry point", () => { expect(new PublicAdapter(new MobiConstructor())).toBeInstanceOf(SketchUpAdapter); });
  it("extracts groups, nested components, definitions, attributes and dynamic attributes", () => { const entities = new EntityExtractor(); const groups = new GroupExtractor(entities).extract(model().groups!); const components = new ComponentExtractor(entities); expect(groups).toHaveLength(1); expect(components.extract(model().groups!)[0]?.dynamicAttributes).toEqual({ lenx: 100 }); expect(components.definitions(model().groups!)).toEqual(["definition-1"]); });
  it("extracts complete model, materials, layers and metadata defensively", () => { const entities = new EntityExtractor(); const extractor = new ModelExtractor(new GroupExtractor(entities), new ComponentExtractor(entities), new MaterialExtractor(), new LayerExtractor(), new MetadataExtractor()); const original = model(); const extracted = extractor.extract(original); extracted.metadata.source = "changed"; expect(extracted).toMatchObject({ id: "skp-model", groups: [{ id: "group-1" }], components: [{ id: "component-2" }], materials: [{ id: "material-1" }], layers: [{ id: "layer-1" }] }); expect(original.metadata?.source).toBe("explicit"); });
  it("maps bounding boxes and transformations as neutral facts", () => { const facts = new GeometryMapper().map(model().groups!); expect(facts[0]).toEqual({ entityId: "group-1", bounds, transform }); const missing = new GeometryMapper().map([{ id: "x", kind: "group", name: "X" }]); expect(missing[0]).toEqual({ entityId: "x", bounds: null, transform: null }); });
  it("maps materials, tags metadata and explicit Constructor descriptor without semantics", () => { const extracted = new ExtractionPipeline().execute(model()); const materials = new MaterialMapper().map(extracted.materials); expect(materials[0]).toEqual({ id: "material-1", name: "MDF", color: "#ffffff", opacity: 0.8 }); expect(new MaterialMapper().map([{ id: "x", name: "X" }])[0]).toMatchObject({ color: null, opacity: null }); const metadata = new MetadataMapper().map(extracted.metadata, extracted.attributes); expect(metadata.author).toBe("SketchUp"); expect(new SketchUpInputMapper().map(extracted, [], materials, metadata).descriptor.project.id).toBe(ids.project); });
  it("rejects semantic inference when explicit Mobi descriptor is absent", () => { const extracted = new ExtractionPipeline().execute({ ...model(), metadata: {} }); expect(() => new SketchUpInputMapper().map(extracted, [], [], {})).toThrow(AdapterError); });
  it("runs SketchUp → Extractors → Mapper → Constructor → TransactionRequest → AdapterResult", () => { const constructor = new MobiConstructor(); const adapter = new SketchUpAdapter(constructor); adapter.createSession("s"); const result = adapter.adapt(input()); expect(result.success).toBe(true); expect(result.constructorResult?.entity?.id).toBe(ids.project); expect(result.transactionRequest).toMatchObject({ id: "adapter-tx-1", source: "mobi-constructor", status: "PREPARED" }); expect(result.report.statistics).toMatchObject({ groups: 1, components: 1, materials: 1, layers: 1, imported: 4, ignored: 0 }); });
  it("reports incomplete geometry as warnings without inventing geometry", () => { const constructor = new MobiConstructor(); const adapter = new SketchUpAdapter(constructor); adapter.createSession("s"); const result = adapter.adapt(input()); expect(result.report.entries.filter(entry => entry.code === "INCOMPLETE_GEOMETRY_FACT")).toHaveLength(1); expect(result.report.statistics.warnings).toBe(1); });
  it("propagates Constructor schema rejection without exposing entity or transaction", () => { const invalid = model(); (invalid.metadata!.mobiConstructionDescriptor as ConstructionDescriptor).project.id = "invalid"; const constructor = new MobiConstructor(); const adapter = new SketchUpAdapter(constructor); adapter.createSession("s"); const result = adapter.adapt(input(invalid)); expect(result.success).toBe(false); expect(result.constructorResult?.failures.some(item => item.code === "INVALID_FORMAT")).toBe(true); expect(result.transactionRequest).toBeUndefined(); expect(result.report.statistics.errors).toBe(1); });
  it("returns controlled Adapter failure for missing descriptors and extraction errors", () => { const constructor = new MobiConstructor(); const adapter = new SketchUpAdapter(constructor); adapter.createSession("s"); const missing = adapter.adapt(input({ ...model(), metadata: {} })); expect(missing).toMatchObject({ success: false, report: { statistics: { errors: 1 } } }); const invalid = adapter.adapt(input({ ...model(), id: "" })); expect(invalid.report.entries.at(-1)?.code).toBe("ADAPTER_ERROR"); });
  it("emits deterministic lifecycle and stage events", () => { const adapter = new SketchUpAdapter(new MobiConstructor()); const received: string[] = []; const listener = (event: { type: string; stage?: string }) => received.push(event.stage ?? event.type); adapter.subscribe(listener); adapter.createSession("s"); adapter.adapt(input()); expect(received).toEqual(["ADAPTER_STARTED", "EXTRACTION", "MAPPING", "CONSTRUCTOR", "ADAPTER_SUCCEEDED"]); adapter.unsubscribe(listener); });
  it("manages sessions, repositories and defensive results", () => { const adapter = new SketchUpAdapter(new MobiConstructor()); expect(() => adapter.adapt(input())).toThrow("No active"); adapter.createSession("s"); const result = adapter.adapt(input()); result.report.entries.length = 0; expect(adapter.getLastResult()?.report.entries.length).toBeGreaterThan(0); expect(adapter.closeSession().active).toBe(false); expect(adapter.getLastResult()).toBeNull(); });
  it("validates extraction entities, models, adapter context and session errors", () => { const entities = new EntityExtractor(); expect(() => entities.extract({ id: "", kind: "group", name: "x" })).toThrow("id"); expect(() => entities.extract({ id: "x", kind: "group", name: "" })).toThrow("name"); expect(() => new ExtractionPipeline().execute({ ...model(), name: "" })).toThrow("required"); expect(() => new AdapterContext({ ...input(), transactionId: "" })).toThrow("transactionId"); expect(() => new AdapterContext({ ...input(), logicalTimestamp: -1 })).toThrow("timestamp"); const session = new AdapterSession(); expect(() => session.create(" ")).toThrow(AdapterError); expect(() => session.close()).toThrow(AdapterError); session.create("x"); expect(session.require()).toBe("x"); });
  it("guards ConstructorPipeline and runs standalone pipelines", () => { const constructor = new MobiConstructor(); constructor.createSession("c"); const context = new AdapterContext(input()); expect(() => new ConstructorPipeline(constructor).execute(context)).toThrow("not been mapped"); context.extracted = new ExtractionPipeline().execute(model()); context.mapped = new MappingPipeline().execute(context.extracted); expect(new ConstructorPipeline(constructor).execute(context).success).toBe(true); });
  it("provides reports, Result, Repository, Error and EventBus contracts", () => { const times = [1, 2, 4]; const report = new AdapterReport(() => times.shift() ?? 4); report.setStatistics({ ignored: 2 }); report.add({ stage: "EXTRACTION", code: "W", message: "warning", element: "x", severity: "warning" }, 1); expect(report.get()).toMatchObject({ durationMs: 1, statistics: { ignored: 2, warnings: 1 } }); const empty = { success: false, report: report.get() }; const result = new AdapterResult(empty).get(); result.report.entries.length = 0; expect(new AdapterResult(empty).get().report.entries).toHaveLength(1); const repository = new AdapterRepository(); expect(repository.get()).toBeNull(); repository.save(empty); expect(repository.get()?.success).toBe(false); repository.clear(); const error = new AdapterError("X", "x"); expect(error).toMatchObject({ name: "AdapterError", code: "X" }); expect(() => new AdapterEvent("ADAPTER_STARTED", "s", -1)).toThrow("non-negative"); expect(new AdapterEvent("STAGE_COMPLETED", "s", 1, "MAPPING").get().stage).toBe("MAPPING"); const bus = new AdapterEventBus(); const listener = vi.fn(); bus.subscribe(listener); bus.publish({ type: "ADAPTER_STARTED", sessionId: "s", logicalTimestamp: 0 }); bus.unsubscribe(listener); bus.clear(); expect(listener).toHaveBeenCalledOnce(); });
  it("supports deterministic default clocks", () => { const context = new AdapterContext(input()); expect(context.now()).toBe(0); const report = new AdapterReport(); report.add({ stage: "EXTRACTION", code: "X", message: "x", element: "x", severity: "info" }); expect(report.get().durationMs).toBe(0); });
});
