import type { Project } from "../../../builder/types/ProjectTypes";
import type { RuleRunner } from "../../../copilot/rules/RuleRunner";
import { RuleContext } from "../../../copilot/rules/RuleContext";
import type { MobiStudioApplication } from "../../mobi-studio/src/MobiStudioApplication";
import type { EditIntentInput } from "../../mobi-studio/src/interfaces/StudioApplicationTypes";
import { TopologyValidator } from "./TopologyValidator";
import type { RoomDescriptor, RoomResult } from "./TopologyTypes";
export class RoomsController{private busy=false;constructor(private readonly studio:MobiStudioApplication,private readonly rules:RuleRunner,private readonly validator=new TopologyValidator()){}
 detect(environmentId:string):string[][]{const p=this.studio.foundation.getProject(),e=p.environments.find(x=>x.id===environmentId);return e?this.validator.detectClosedLoops(e):[]}
 detectAll():Record<string,string[][]>{const p=this.studio.foundation.getProject();return Object.fromEntries(p.environments.map(e=>[e.id,this.validator.detectClosedLoops(e)]))}
 validate(room:RoomDescriptor){const p=this.studio.foundation.getProject(),e=p.environments.find(x=>x.id===room.environmentId);if(!e)return{valid:false,issues:[{code:"MISSING_REFERENCE" as const,wallIds:[room.environmentId],path:"/environments"}],orderedWallIds:[]};return this.validator.validate(e,room.wallIds)}
 create(room:RoomDescriptor,author:string,timestamp:number):RoomResult{if(this.busy)return{success:false,code:"EDIT_ALREADY_ACTIVE"};const topology=this.validate(room);if(!topology.valid)return{success:false,code:"INVALID_ROOM_TOPOLOGY",topology};const p=this.studio.foundation.getProject();if(p.environments.some(e=>e.id!==room.environmentId&&e.code===`ROOM:${room.code}`))return{success:false,code:"DUPLICATE_ROOM",topology};return this.transact("CREATE_ROOM",room,author,timestamp,project=>{const e=project.environments.find(x=>x.id===room.environmentId)!;e.displayName=room.displayName;e.code=`ROOM:${room.code}`;e.status="validated"})}
 update(room:RoomDescriptor,author:string,timestamp:number):RoomResult{const p=this.studio.foundation.getProject(),e=p.environments.find(x=>x.id===room.environmentId);if(!e||!e.code.startsWith("ROOM:"))return{success:false,code:"ROOM_NOT_FOUND"};const topology=this.validate(room);if(!topology.valid)return{success:false,code:"INVALID_ROOM_TOPOLOGY",topology};if(p.environments.some(x=>x.id!==room.environmentId&&x.code===`ROOM:${room.code}`))return{success:false,code:"DUPLICATE_ROOM",topology};return this.transact("UPDATE_ROOM",room,author,timestamp,project=>{const target=project.environments.find(x=>x.id===room.environmentId)!;target.displayName=room.displayName;target.code=`ROOM:${room.code}`})}
 delete(environmentId:string,author:string,timestamp:number):RoomResult{const p=this.studio.foundation.getProject(),e=p.environments.find(x=>x.id===environmentId);if(!e||!e.code.startsWith("ROOM:"))return{success:false,code:"ROOM_NOT_FOUND"};return this.transact("DELETE_ROOM",{environmentId,wallIds:[],displayName:e.displayName,code:e.code},author,timestamp,project=>{const target=project.environments.find(x=>x.id===environmentId)!;target.code=target.code.slice(5);target.status="draft"})}
 refresh(environmentId:string,author:string,timestamp:number):RoomResult{const p=this.studio.foundation.getProject(),e=p.environments.find(x=>x.id===environmentId);if(!e||!e.code.startsWith("ROOM:"))return{success:false,code:"ROOM_NOT_FOUND"};const loops=this.validator.detectClosedLoops(e);if(loops.length!==1)return{success:false,code:"INVALID_ROOM_TOPOLOGY",topology:this.validator.validate(e,e.architectures.filter(x=>x.type==="wall").map(x=>x.id))};return this.update({environmentId,wallIds:loops[0]!,displayName:e.displayName,code:e.code.slice(5)},author,timestamp)}
 private transact(operationName:string,room:RoomDescriptor,author:string,timestamp:number,mutate:(p:Project)=>void):RoomResult{this.busy=true;try{const input:EditIntentInput={id:`${operationName}:${room.environmentId}:${timestamp}`,entityId:room.environmentId,property:"environment.topology",value:structuredClone(room),author,logicalTimestamp:timestamp,operationName,operation:origin=>{const p=origin.getProject();mutate(p);const results=this.rules.runAll(new RuleContext(p));if(results.some(x=>x.severity==="error"))throw new Error("RULE_VALIDATION_FAILED");origin.openProject(JSON.stringify(p))},preview:{apply:()=>{},revert:()=>{}}};this.studio.beginEdit(input);const transaction=this.studio.commitEdit();return{success:transaction.success,code:transaction.success?"COMMITTED":"TRANSACTION_ROLLED_BACK",transaction}}catch(e){return{success:false,code:(e as Error).message}}finally{this.busy=false}}
}
