import type { Architecture, Environment, Vector3 } from "../../../builder/types/ProjectTypes";
import type { Segment, TopologyIssue, TopologyResult } from "./TopologyTypes";
const E=1e-7,eq=(a:number,b:number)=>Math.abs(a-b)<E,point=(a:Vector3,b:Vector3)=>eq(a.x,b.x)&&eq(a.z,b.z),cross=(a:Vector3,b:Vector3,c:Vector3)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);
export class TopologyValidator{
 validate(environment:Environment,wallIds:string[]):TopologyResult{const issues:TopologyIssue[]=[];const walls=environment.architectures.filter(a=>a.type==="wall");const selected:Architecture[]=[];for(const id of wallIds){const w=walls.find(x=>x.id===id);if(!w)issues.push(this.issue("MISSING_REFERENCE",[id]));else selected.push(w)}const segments=selected.map(this.segment);for(const s of segments)if(point(s.start,s.end))issues.push(this.issue("ZERO_LENGTH_SEGMENT",[s.id]));for(let i=0;i<segments.length;i++)for(let j=i+1;j<segments.length;j++){const a=segments[i]!,b=segments[j]!;if((point(a.start,b.start)&&point(a.end,b.end))||(point(a.start,b.end)&&point(a.end,b.start)))issues.push(this.issue("DUPLICATE_WALL",[a.id,b.id]));else if(this.collinearOverlap(a,b))issues.push(this.issue("OVERLAPPING_WALLS",[a.id,b.id]));else if(this.intersects(a,b)&&!this.shareEndpoint(a,b))issues.push(this.issue("SELF_INTERSECTION",[a.id,b.id]))}const loops=this.detectClosedLoopsFromSegments(segments),ordered=loops.length===1?loops[0]!:[];if(loops.length>1)issues.push(this.issue("AMBIGUOUS_LOOPS",segments.map(x=>x.id)));if(segments.length<3||ordered.length!==segments.length)issues.push(this.issue("OPEN_LOOP",segments.map(x=>x.id)));const degrees=new Map<string,number>();for(const s of segments){for(const p of [s.start,s.end]){const k=this.key(p);degrees.set(k,(degrees.get(k)??0)+1)}}if([...degrees.values()].some(v=>v!==2))issues.push(this.issue("OPEN_LOOP",segments.map(x=>x.id)));return{valid:issues.length===0,issues:this.unique(issues),orderedWallIds:ordered}}
 detectClosedLoops(environment:Environment):string[][]{return this.detectClosedLoopsFromSegments(environment.architectures.filter(x=>x.type==="wall").map(this.segment))}
 validateConnections(environment:Environment):TopologyIssue[]{const s=environment.architectures.filter(x=>x.type==="wall").map(this.segment),issues:TopologyIssue[]=[];for(let i=0;i<s.length;i++)for(let j=i+1;j<s.length;j++)if(this.intersects(s[i]!,s[j]!)&&!this.shareEndpoint(s[i]!,s[j]!))issues.push(this.issue("ILLEGAL_INTERSECTION",[s[i]!.id,s[j]!.id]));return issues}
 private segment=(w:Architecture):Segment=>({id:w.id,start:w.position,end:w.referencePlane});
 private orderLoop(s:Segment[]):string[]{if(!s.length)return[];const used=new Set<number>([0]),out=[s[0]!.id];let end=s[0]!.end;while(used.size<s.length){const i=s.findIndex((x,n)=>!used.has(n)&&(point(x.start,end)||point(x.end,end)));if(i<0)return[];used.add(i);const n=s[i]!;out.push(n.id);end=point(n.start,end)?n.end:n.start}return point(end,s[0]!.start)?out:[]}
 private detectClosedLoopsFromSegments(segments:Segment[]):string[][]{const remaining=new Set(segments.map((_,i)=>i)),loops:string[][]=[];while(remaining.size){const seed=remaining.values().next().value as number,component=new Set<number>(),queue=[seed];while(queue.length){const i=queue.shift()!;if(component.has(i))continue;component.add(i);remaining.delete(i);const a=segments[i]!;for(const j of [...remaining]){const b=segments[j]!;if(this.shareEndpoint(a,b))queue.push(j)}}const part=[...component].map(i=>segments[i]!);const ordered=this.orderLoop(part);if(ordered.length===part.length&&ordered.length>=3)loops.push(ordered)}return loops}
 private intersects(a:Segment,b:Segment){const c1=cross(a.start,a.end,b.start),c2=cross(a.start,a.end,b.end),c3=cross(b.start,b.end,a.start),c4=cross(b.start,b.end,a.end);return c1*c2<=E&&c3*c4<=E}
 private shareEndpoint(a:Segment,b:Segment){return point(a.start,b.start)||point(a.start,b.end)||point(a.end,b.start)||point(a.end,b.end)}
 private collinearOverlap(a:Segment,b:Segment){if(Math.abs(cross(a.start,a.end,b.start))>E||Math.abs(cross(a.start,a.end,b.end))>E)return false;const axis=Math.abs(a.end.x-a.start.x)>=Math.abs(a.end.z-a.start.z)?"x":"z";const aa=[a.start[axis],a.end[axis]].sort((x,y)=>x-y),bb=[b.start[axis],b.end[axis]].sort((x,y)=>x-y);return Math.min(aa[1]!,bb[1]!)-Math.max(aa[0]!,bb[0]!)>E}
 private key(p:Vector3){return `${p.x.toFixed(7)},${p.z.toFixed(7)}`}
 private issue(code:TopologyIssue["code"],ids:string[]):TopologyIssue{return{code,wallIds:ids,path:"/architectures"}}
 private unique(items:TopologyIssue[]){const seen=new Set<string>();return items.filter(x=>{const k=x.code+":"+x.wallIds.join(",");if(seen.has(k))return false;seen.add(k);return true})}
}
