import type{Project}from"../../../builder/types/ProjectTypes";import{RuleContext}from"../../../copilot/rules/RuleContext";import type{RuleRunner}from"../../../copilot/rules/RuleRunner";import type{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import type{EditIntentInput}from"../../mobi-studio/src/interfaces/StudioApplicationTypes";import{fromInfrastructure,isTechnicalPoint,toInfrastructure}from"./TechnicalPointCodec";import type{TechnicalPointDescriptor,TechnicalPointResult}from"./TechnicalPointTypes";import{TechnicalPointValidator}from"./TechnicalPointValidator";
export class TechnicalPointsController{constructor(private readonly studio:MobiStudioApplication,private readonly rules:RuleRunner,private readonly validator=new TechnicalPointValidator()){}
 add(point:TechnicalPointDescriptor,author:string,time:number){return this.change("ADD_TECHNICAL_POINT",point,author,time,p=>{const e=this.env(p,point.environmentId),v=this.validator.validate(e,point);if(!v.valid)throw new Error("INVALID_TECHNICAL_POINT");e.infrastructures.push(toInfrastructure(point))})}
 update(point:TechnicalPointDescriptor,author:string,time:number){return this.change("UPDATE_TECHNICAL_POINT",point,author,time,p=>{const e=this.env(p,point.environmentId),i=e.infrastructures.findIndex(v=>v.id===point.id&&isTechnicalPoint(v));if(i<0)throw new Error("TECHNICAL_POINT_NOT_FOUND");if(!this.validator.validate(e,point,point.id).valid)throw new Error("INVALID_TECHNICAL_POINT");e.infrastructures[i]=toInfrastructure(point)})}
 delete(environmentId:string,id:string,author:string,time:number){return this.change("DELETE_TECHNICAL_POINT",{id,environmentId},author,time,p=>{const e=this.env(p,environmentId),i=e.infrastructures.findIndex(v=>v.id===id&&isTechnicalPoint(v));if(i<0)throw new Error("TECHNICAL_POINT_NOT_FOUND");e.infrastructures.splice(i,1)})}
 get(environmentId:string,id:string){const e=this.studio.foundation.getProject().environments.find(v=>v.id===environmentId),v=e?.infrastructures.find(x=>x.id===id&&isTechnicalPoint(x));return v?fromInfrastructure(v):undefined}
 private change(operationName:string,value:{id:string;environmentId:string},author:string,time:number,mutate:(p:Project)=>void):TechnicalPointResult{try{const input:EditIntentInput={id:`${operationName}:${value.id}:${time}`,entityId:value.id,property:"environment.infrastructure.technical",value:structuredClone(value),author,logicalTimestamp:time,operationName,operation:origin=>{const p=origin.getProject();mutate(p);if(p.environments.some(e=>!this.validator.validateEnvironment(e).valid))throw new Error("INVALID_TECHNICAL_POINT");if(this.rules.runAll(new RuleContext(p)).some(r=>r.severity==="error"))throw new Error("RULE_VALIDATION_FAILED");origin.openProject(JSON.stringify(p))},preview:{apply:()=>{},revert:()=>{}}};this.studio.beginEdit(input);const transaction=this.studio.commitEdit();return{success:transaction.success,code:transaction.success?"COMMITTED":"TRANSACTION_ROLLED_BACK",transaction}}catch(error){return{success:false,code:(error as Error).message}}}
 private env(p:Project,id:string){const e=p.environments.find(v=>v.id===id);if(!e)throw new Error("ENVIRONMENT_NOT_FOUND");return e}}

