import{describe,expect,it,vi}from"vitest";import{ProjectBuilder,environmentInput,ids,moduleInput,partInput,projectInput}from"./fixtures";import{TraceabilityTransaction}from"../src/adapters/TraceabilityTransaction";import{BOMManager}from"../src/bom-manager/BOMManager";import{CAMBridge}from"../src/cam-bridge/CAMBridge";import type{CognitiveEventPort,FeedbackSnapshot,IndustrialLog,SheetSpecification,TraceabilityRegistrar}from"../src/closed-loop/Phase3Types";import{FeedbackLoop}from"../src/feedback-loop/FeedbackLoop";import{NestingEngine}from"../src/nesting-engine/NestingEngine";import{ConstructorIndustrialRuleSet}from"../src/part-generator/IndustrialRuleSet";import{PartGenerator}from"../src/part-generator/PartGenerator";import{ClosedLoopPipeline}from"../src/pipeline/ClosedLoopPipeline";import{VerificationEngine}from"../src/verification-engine/VerificationEngine";
function project(){const p=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addModule(ids.environment,moduleInput).addPart(ids.module,partInput).build(),part=p.environments[0]!.modules[0]!.parts[0]!,copy={...structuredClone(part),id:"22222222-2222-4222-8222-222222222222",size:{...part.size,width:500,height:300}};return{...p,environments:p.environments.map((environment,index)=>index?environment:{...environment,modules:environment.modules.map((module,moduleIndex)=>moduleIndex?module:{...module,parts:[...module.parts,copy]})})}}const generator=new PartGenerator(new ConstructorIndustrialRuleSet()),nesting=new NestingEngine(),feedback=new FeedbackLoop(),spec:SheetSpecification={width:1500,height:1000,margin:10,kerf:4};const pkg=()=>generator.generate(project());const goodLogs=():IndustrialLog[]=>pkg().parts.map((p,i)=>({id:`log-${i}`,partId:p.sourceProductId,timestamp:i,status:"COMPLETED",actual:{width:p.width,height:p.height,thickness:p.thickness}}));
describe("Closed-loop operational intelligence",()=>{
 it("generates the same nesting for the same logical input",()=>{const source=pkg(),a=nesting.generate(source,spec),b=nesting.generate({...source,parts:[...source.parts].reverse()},spec);expect(a).toEqual(b);expect(a.placementCount).toBe(2);expect(a.fingerprint).toMatch(/^[0-9a-f]{8}$/);expect(a.sheets.every(s=>s.utilization>0&&s.utilization<=1)).toBe(true)});
 it("respects margins, kerf and creates additional sheets deterministically",()=>{const source=pkg(),small={width:800,height:600,margin:10,kerf:4},out=nesting.generate(source,small);expect(out.sheets.length).toBeGreaterThanOrEqual(2);for(const s of out.sheets)for(const p of s.placements){expect(p.x).toBeGreaterThanOrEqual(10);expect(p.y).toBeGreaterThanOrEqual(10);expect(p.x+p.width).toBeLessThanOrEqual(790);expect(p.y+p.height).toBeLessThanOrEqual(590)}});
 it("rejects invalid sheet specifications and oversized parts",()=>{for(const bad of[{...spec,width:0},{...spec,height:0},{...spec,margin:-1},{...spec,kerf:-1},{...spec,width:Number.NaN},{...spec,margin:800},{...spec,height:20,margin:10}])expect(()=>nesting.generate(pkg(),bad)).toThrow("INVALID_SHEET_SPECIFICATION");expect(()=>nesting.generate(pkg(),{width:100,height:100,margin:1,kerf:0})).toThrow("PART_EXCEEDS_SHEET")});
 it("ingests logs and telemetry read-only with PartID traceability",()=>{const source=pkg(),logs=goodLogs(),telemetry=[{id:"tel-1",partId:source.parts[0]!.sourceProductId,timestamp:3,metric:"temperature",value:20,unit:"C"}],out=feedback.ingest(source,logs,telemetry);logs[0]!.status="REJECTED";telemetry[0]!.value=99;expect(out.logs[0]!.status).toBe("COMPLETED");expect(out.telemetry[0]!.value).toBe(20);expect(out.traceability[source.parts[0]!.sourceProductId]).toEqual(["log-0","tel-1"])});
 it("blocks malformed or inconsistent feedback",()=>{const source=pkg(),partId=source.parts[0]!.sourceProductId,base={id:"x",partId,timestamp:0,status:"COMPLETED"as const};for(const logs of[[{...base,id:""}],[base,{...base}],[{...base,partId:"unknown"}],[{...base,timestamp:-1}],[{...base,timestamp:1.2}],[{...base,actual:{width:0,height:1,thickness:1}}],[{...base,actual:{width:Number.NaN,height:1,thickness:1}}]])expect(()=>feedback.ingest(source,logs,[])).toThrow("INVALID_FEEDBACK");for(const t of[{id:"t",partId,timestamp:0,metric:"",value:1,unit:"u"},{id:"t",partId,timestamp:0,metric:"m",value:1,unit:""},{id:"t",partId,timestamp:0,metric:"m",value:Number.NaN,unit:"u"}])expect(()=>feedback.ingest(source,[],[t])).toThrow("INVALID_TELEMETRY")});
 it("verifies compliant production and emits a cognitive event",()=>{const events={publish:vi.fn()}as CognitiveEventPort,engine=new VerificationEngine(events),source=pkg(),report=engine.verify(source,feedback.ingest(source,goodLogs(),[]));expect(report).toMatchObject({compliant:true,blocked:false});expect(report.verifiedPartIds).toHaveLength(2);expect(events.publish).toHaveBeenCalledWith(expect.objectContaining({type:"INDUSTRIAL_VERIFICATION",compliant:true}))});
 it("audits dimensional deviations and rejected production",()=>{const events={publish:vi.fn()},engine=new VerificationEngine(events),source=pkg(),logs=goodLogs();logs[0]!.actual!.width+=2;logs[0]!.status="REJECTED";const report=engine.verify(source,feedback.ingest(source,logs,[]));expect(report).toMatchObject({compliant:false,blocked:true});expect(report.deviations.map(v=>v.field)).toEqual(["width","status"]);expect(events.publish).toHaveBeenCalledWith(expect.objectContaining({compliant:false}))});
 it("blocks feedback forged after ingestion",()=>{const source=pkg(),engine=new VerificationEngine({publish:vi.fn()}),snapshot={logs:[{id:"x",partId:"unknown",timestamp:0,status:"COMPLETED"}],telemetry:[],traceability:{}}as FeedbackSnapshot;expect(()=>engine.verify(source,snapshot)).toThrow("INCONSISTENT_FEEDBACK");expect(()=>engine.verify(source,{logs:[],telemetry:[],traceability:{unknown:[]}})).toThrow("INCONSISTENT_FEEDBACK")});
 it("executes the full closed-loop pipeline without confirming production",()=>{const source=pkg(),events={publish:vi.fn()},registrar={register:vi.fn(()=>({success:true,transactionId:"trace-tx"}))},pipeline=new ClosedLoopPipeline(generator,nesting,new BOMManager(),new CAMBridge(),feedback,new VerificationEngine(events),registrar),out=pipeline.execute(project(),spec,goodLogs(),[]);expect(out.traceTransactionId).toBe("trace-tx");expect(out.cam).toHaveLength(3);expect(registrar.register).toHaveBeenCalledWith(projectInput.id,out.verification.auditId)});
 it("rolls back rejected traceability registration",()=>{const registrar:TraceabilityRegistrar={register:()=>({success:false})},pipeline=new ClosedLoopPipeline(generator,nesting,new BOMManager(),new CAMBridge(),feedback,new VerificationEngine({publish:vi.fn()}),registrar);expect(()=>pipeline.execute(project(),spec,goodLogs(),[])).toThrow("TRACEABILITY_EVENT_ROLLED_BACK")});
 it("registers only an industrial traceability event",()=>{const execute=vi.fn((command:any)=>{expect(command.operationName).toBe("INDUSTRIAL_TRACEABILITY_EVENT");command.operation({});command.preview.apply({});command.preview.revert({});return{success:true,transactionId:"official"}}),adapter=new TraceabilityTransaction({execute}as any);expect(adapter.register(projectInput.id,"audit")).toEqual({success:true,transactionId:"official"});expect(adapter.register(projectInput.id,"audit2").success).toBe(true);expect(execute).toHaveBeenCalledTimes(2)});
 it("reports coordinator rollback without transaction identity",()=>{expect(new TraceabilityTransaction({execute:()=>({success:false})}as any).register(projectInput.id,"audit")).toEqual({success:false})});
});
