import{describe,expect,it}from"vitest";import{ProjectBuilder,environmentInput,ids,moduleInput,partInput,projectInput}from"./fixtures";import{ConstructorApplication}from"../src/application/ConstructorApplication";import{DependencyRegistry}from"../src/core/DependencyRegistry";import{ProductBootstrap}from"../src/core/ProductBootstrap";import{OutputFramework}from"../src/outputs/OutputFramework";import{ConstructorPipeline}from"../src/pipeline/ConstructorPipeline";import{ProjectReader}from"../src/readers/ProjectReader";import{CognitiveEventService}from"../src/services/CognitiveEventService";import{TranslationEngine}from"../src/translators/TranslationEngine";import{ConstructorStatusView}from"../src/ui/ConstructorStatusView";import{ProjectValidator}from"../src/validators/ProjectValidator";import{ResultWriter}from"../src/writers/ResultWriter";import{ConstructorOrchestrator}from"../src/orchestrators/ConstructorOrchestrator";
const project=()=>new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addModule(ids.environment,moduleInput).addPart(ids.module,partInput).build();const source=()=>({getProject:()=>project()});const pipeline=()=>new ConstructorPipeline(new ProjectValidator(),new TranslationEngine(),new OutputFramework());
describe("Mobi Constructor product foundation",()=>{
 it("registers and resolves isolated dependencies",()=>{const r=new DependencyRegistry().register("x",0);expect(r.has("x")).toBe(true);expect(r.resolve<number>("x")).toBe(0);expect(()=>r.register("x",1)).toThrow("INVALID_DEPENDENCY");expect(()=>new DependencyRegistry().register("",1)).toThrow("INVALID_DEPENDENCY");expect(()=>new DependencyRegistry().register("x",undefined)).toThrow("INVALID_DEPENDENCY");expect(()=>r.resolve("missing")).toThrow("MISSING_DEPENDENCY")});
 it("reads a defensive snapshot through a public project source",()=>{const p=project(),reader=new ProjectReader({getProject:()=>p}),copy=reader.read();(copy as typeof p).displayName="changed";expect(p.displayName).not.toBe("changed")});
 it("validates official project contracts",()=>{const validator=new ProjectValidator(),p=project();expect(validator.validate({project:p}).project.id).toBe(p.id);for(const invalid of[{...p,id:""},{...p,schemaVersion:"2"},{...p,measurementUnit:"cm"},{...p,rotationUnit:"radians"},{...p,environments:null}])expect(()=>validator.validate({project:invalid as never})).toThrow("INVALID_PROJECT")});
 it("translates deterministically without industrial packages",()=>{const t=new TranslationEngine(),a=t.translate({project:project()}),b=t.translate({project:project()});expect(a).toEqual(b);expect(a).toMatchObject({environmentCount:1,moduleCount:1,partCount:1});expect(a.sourceFingerprint).toMatch(/^[0-9a-f]{8}$/)});
 it("exposes output contracts only",()=>{const f=new OutputFramework(),o=f.prepare(new TranslationEngine().translate({project:project()}));expect(o.packages).toEqual([]);expect(o.outputs.map(v=>v.kind)).toEqual(["MANUFACTURING","CAM","GCODE","DETAILING","REPORT"]);expect(o.outputs.every(v=>!v.implemented)).toBe(true);o.model.projectId="changed";expect(f.contracts()).toHaveLength(5)});
 it("runs Input Validation Translation Output in order",()=>{const run=pipeline().execute({project:project()});expect(run.stages).toEqual(["Input","Validation","Translation","Output"]);expect(run.output.model.projectId).toBe(projectInput.id)});
 it("bootstraps only with every public dependency",()=>{const r=new DependencyRegistry().register("projectReader",source()).register("transactionCoordinator",{}).register("ruleRunner",{}).register("constructorApi",{}).register("cognitiveEvents",{}),app=new ProductBootstrap(r).start();expect(app).toBeInstanceOf(ConstructorApplication);expect(app.run().output.packages).toEqual([]);expect(()=>new ProductBootstrap(new DependencyRegistry()).start()).toThrow("MISSING_DEPENDENCY")});
 it("writes immutable run snapshots and orchestrates",()=>{const writer=new ResultWriter();expect(writer.read()).toBeUndefined();const app=new ConstructorApplication(new ProjectReader(source()),pipeline(),writer),run=new ConstructorOrchestrator(app).execute();run.output.model.projectId="mutated";expect(writer.read()?.output.model.projectId).toBe(projectInput.id)});
 it("observes cognitive events without actions",()=>{const service=new CognitiveEventService(),event={type:"DIAGNOSTIC",timestamp:1,detail:"read-only"};service.observe(event);event.detail="changed";expect(service.snapshot()).toEqual([{type:"DIAGNOSTIC",timestamp:1,detail:"read-only"}])});
 it("renders a disabled industrial status",()=>{const run=pipeline().execute({project:project()});expect(new ConstructorStatusView().render(run)).toEqual({status:"READY",projectId:projectInput.id,industrialOutputsEnabled:false})});
});
