import{describe,expect,it,vi}from"vitest";import{ProjectBuilder,environmentInput,hardwareInput,ids,moduleInput,partInput,projectInput}from"./fixtures";import{IndustrialExportTransaction}from"../src/adapters/IndustrialExportTransaction";import{BOMManager}from"../src/bom-manager/BOMManager";import{CAMBridge}from"../src/cam-bridge/CAMBridge";import type{CognitiveGate,IndustrialExportRegistrar,ManufacturingPackage,RuleRunnerPort}from"../src/industrial/IndustrialTypes";import{ConstructorIndustrialRuleSet}from"../src/part-generator/IndustrialRuleSet";import{PartGenerator}from"../src/part-generator/PartGenerator";import{IndustrializationPipeline}from"../src/pipeline/IndustrializationPipeline";
function project(){const p=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addModule(ids.environment,moduleInput).addPart(ids.module,{...partInput,edgeBanding:{...partInput.edgeBanding,top:{applied:true,materialId:"edge"}}}).addHardware(ids.module,hardwareInput).build(),part=p.environments[0]!.modules[0]!.parts[0]!,copy={...structuredClone(part),id:"22222222-2222-4222-8222-222222222222"};return{...p,environments:p.environments.map((environment,index)=>index?environment:{...environment,modules:environment.modules.map((module,moduleIndex)=>moduleIndex?module:{...module,parts:[...module.parts,copy]})})}}const rules=new ConstructorIndustrialRuleSet(),generator=new PartGenerator(rules),bom=new BOMManager(),cam=new CAMBridge();const healthy:CognitiveGate={analyze:()=>({status:"HEALTHY",diagnostics:[]})};
describe("Industrialization Engine",()=>{
 it("applies the stateless industrial rule set",()=>{const part=project().environments[0]!.modules[0]!.parts[0]!,a=rules.operations(part),b=rules.operations(part);expect(a).toEqual(b);expect(a.map(v=>v.kind)).toEqual(["PROFILE","EDGE","EDGE"])});
 it("generates parts, hardware, operations and traceability",()=>{const out=generator.generate(project());expect(out.parts).toHaveLength(2);expect(out.hardware).toHaveLength(1);expect(out.parts[0]!.operations).toHaveLength(3);expect(out.traceability[partInput.id]).toEqual([`mfg:${partInput.id}`,`op:${partInput.id}:profile`,`op:${partInput.id}:edge:top`,`op:${partInput.id}:edge:front`]);expect(out.traceability[hardwareInput.id]).toEqual([`mfg:${hardwareInput.id}`])});
 it("consolidates and mathematically validates BOM",()=>{const pkg=generator.generate(project()),out=bom.generate(pkg,.1),material=out.lines.find(v=>v.kind==="MATERIAL")!;expect(material.quantity).toBe(2.2);expect(out.totals).toMatchObject({partCount:2,hardwareCount:1});expect(out.stockPrepared&&out.wastePrepared).toBe(true);expect(out.lines.find(v=>v.kind==="HARDWARE")?.quantity).toBe(1)});
 it("blocks invalid BOM inputs",()=>{const pkg=generator.generate(project());expect(()=>bom.generate(pkg,-1)).toThrow("INVALID_WASTE_FACTOR");expect(()=>bom.generate(pkg,Number.NaN)).toThrow("INVALID_WASTE_FACTOR");expect(()=>bom.generate({...pkg,parts:[{...pkg.parts[0]!,width:0}]})).toThrow("INVALID_MANUFACTURING_PART");expect(()=>bom.generate({...pkg,hardware:[{...pkg.hardware[0]!,catalogId:""}]})).toThrow("INVALID_HARDWARE");expect(()=>bom.generate({...pkg,parts:[{...pkg.parts[0]!,width:Number.POSITIVE_INFINITY}]})).toThrow("INVALID_BOM_MATH")});
 it("prepares only neutral CAM contracts",()=>{const pkg=generator.generate(project()),bill=bom.generate(pkg),artifacts=cam.prepare(pkg,bill);expect(artifacts.map(v=>v.format)).toEqual(["GENERIC_GCODE","DXF","NEUTRAL_CAM"]);expect(artifacts.every(v=>v.payload.length===0&&v.postProcessor===null)).toBe(true);expect(()=>cam.prepare(pkg,{...bill,projectId:"other"})).toThrow("CAM_PROJECT_MISMATCH")});
 it("runs the deterministic industrial pipeline and registers export",()=>{const runner:RuleRunnerPort={analyze:vi.fn(()=>[])},registrar:IndustrialExportRegistrar={register:vi.fn(()=>({success:true,transactionId:"tx-1"}))},pipe=new IndustrializationPipeline(generator,runner,bom,cam,healthy,registrar),a=pipe.execute(project(),1,.05),b=pipe.execute(project(),1,.05);expect(a.manufacturing).toEqual(b.manufacturing);expect(a.exportTransactionId).toBe("tx-1");expect(runner.analyze).toHaveBeenCalledTimes(2);expect(registrar.register).toHaveBeenCalledWith(projectInput.id,expect.stringMatching(/^[0-9a-f]{8}$/))});
 it("blocks invalid, incomplete or cognitively blocked projects",()=>{const registrar={register:vi.fn()}as unknown as IndustrialExportRegistrar,runner={analyze:vi.fn(()=>[])};for(const gate of[{analyze:()=>({status:"ISSUES"as const,diagnostics:[]})},{analyze:()=>({status:"HEALTHY"as const,diagnostics:[{severity:"error"as const}]})}])expect(()=>new IndustrializationPipeline(generator,runner,bom,cam,gate,registrar).execute(project(),2)).toThrow("COGNITIVE_EXPORT_BLOCKED");expect(registrar.register).not.toHaveBeenCalled()});
 it("rolls back a rejected industrial export",()=>{const pipe=new IndustrializationPipeline(generator,{analyze:()=>[]},bom,cam,healthy,{register:()=>({success:false})});expect(()=>pipe.execute(project(),3)).toThrow("INDUSTRIAL_EXPORT_ROLLED_BACK")});
 it("registers only INDUSTRIAL_EXPORT through the coordinator",()=>{const execute=vi.fn((command:any)=>{expect(command.operationName).toBe("INDUSTRIAL_EXPORT");expect(command.property).toBe("industrialExport");command.operation({});command.preview.apply({});command.preview.revert({});return{success:true,transactionId:"official-tx"}}),adapter=new IndustrialExportTransaction({execute}as any);expect(adapter.register(projectInput.id,"abc")).toEqual({success:true,transactionId:"official-tx"});expect(adapter.register(projectInput.id,"def").success).toBe(true);expect(execute).toHaveBeenCalledTimes(2)});
 it("propagates coordinator rollback without inventing a transaction id",()=>{const adapter=new IndustrialExportTransaction({execute:()=>({success:false})}as any);expect(adapter.register(projectInput.id,"abc")).toEqual({success:false})});
});
