import type{Camera,Scene}from"three";import{describe,expect,it}from"vitest";import{ProjectBuilder}from"../../../builder/ProjectBuilder";import{environmentInput,ids,projectInput}from"../../../builder/tests/fixture";import{MobiCopilot}from"../../../copilot/MobiCopilot";import{RuleRegistry}from"../../../copilot/rules/RuleRegistry";import{RuleRunner}from"../../../copilot/rules/RuleRunner";import{MobiOrigin}from"../../../origin/MobiOrigin";import{PresentationCore}from"../../../presentation/PresentationCore";import{MobiStudio}from"../../../studio/MobiStudio";import{SyncManager}from"../../../sync/SyncManager";import{Viewer}from"../../../viewer/Viewer";import type{FrameScheduler,RenderBackend}from"../../../viewer/interfaces/ViewerTypes";import{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import{toOpeningArchitecture}from"../../mobi-studio-openings/src/OpeningGeometry";import{toInfrastructure as toTechnicalInfrastructure}from"../../mobi-studio-technical-points/src/TechnicalPointCodec";import{toArchitecture}from"../../mobi-studio-walls/src/WallGeometry";import{ApplianceRule}from"../src/ApplianceRule";import{encodeAppliance}from"../src/ApplianceCodec";import type{ApplianceDescriptor,ApplianceKind}from"../src/ApplianceTypes";import{AppliancesController}from"../src/AppliancesController";import{CollisionEngine}from"../src/CollisionEngine";import{EnvironmentalCascadeController}from"../src/EnvironmentalCascadeController";import{EnvironmentalPresentation}from"../src/EnvironmentalPresentation";
import{decodeAppliance,isAppliance,isClearance}from"../src/ApplianceCodec";
class B implements RenderBackend{render(_s:Scene,_c:Camera){}setSize(){}dispose(){}}class S implements FrameScheduler{request(){return 1}cancel(){}}
const aid=(n:number)=>`71000000-0000-4000-8000-${n.toString().padStart(12,"0")}`,wallId=(n:number)=>`70000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;const walls=[{id:wallId(1),start:{x:0,y:0,z:0},end:{x:4000,y:0,z:0}},{id:wallId(2),start:{x:4000,y:0,z:0},end:{x:4000,y:0,z:3000}},{id:wallId(3),start:{x:4000,y:0,z:3000},end:{x:0,y:0,z:3000}},{id:wallId(4),start:{x:0,y:0,z:3000},end:{x:0,y:0,z:0}}].map(v=>({...v,environmentId:ids.environment,height:2700,thickness:100,finish:"paint"}));
const appliance=(n=1,kind:ApplianceKind="refrigerator"):ApplianceDescriptor=>({id:aid(n),clearanceId:aid(n+100),environmentId:ids.environment,kind,category:"electrical",position:{x:1000,y:0,z:1000},collisionVolume:{width:500,height:2000,depth:600},clearanceVolume:{width:700,height:2200,depth:800}});
function setup(){const origin=new MobiOrigin(),foundation=new MobiStudio(origin),p=new PresentationCore();p.createSession("p");const studio=new MobiStudioApplication({origin,foundation,presentation:p,viewer:new Viewer(p,new B(),new S()),copilot:new MobiCopilot(origin,foundation),sync:new SyncManager(origin)});studio.startSession("s");const project=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).build();project.environments[0]!.architectures=walls.map(toArchitecture);foundation.openProject(JSON.stringify(project));const registry=new RuleRegistry();registry.registerRule(new ApplianceRule());return{c:new AppliancesController(studio,new RuleRunner(registry)),origin,foundation,studio}}
function inject(s:ReturnType<typeof setup>,...items:ApplianceDescriptor[]){const p=s.foundation.getProject();p.environments[0]!.infrastructures.push(...items.flatMap(encodeAppliance));s.foundation.openProject(JSON.stringify(p));return p.environments[0]!}
describe("appliances",()=>{
 it("adds, moves, updates and deletes reference volumes",()=>{const{c}=setup(),a=appliance();expect(c.add(a,"u",1).success).toBe(true);expect(c.move(ids.environment,a.id,{x:1800,y:0,z:1000},"u",2).success).toBe(true);expect(c.update({...a,position:{x:1800,y:0,z:1000},collisionVolume:{width:600,height:1900,depth:600}},"u",3).success).toBe(true);expect(c.get(ids.environment,a.id)).toMatchObject({position:{x:1800},collisionVolume:{width:600}});expect(c.delete(ids.environment,a.id,"u",4).success).toBe(true);expect(c.get(ids.environment,a.id)).toBeUndefined()});
 it.each(["refrigerator","cooktop","oven","microwave","dishwasher","washing_machine","television","hood","air_purifier","generic"]as ApplianceKind[])("supports %s reference volume",kind=>{const{c}=setup();expect(c.add(appliance(1,kind),"u",1).success).toBe(true)});
 it("detects Appliance x Appliance overlap and collision",()=>{const s=setup(),e=inject(s,appliance(1),{...appliance(2),position:{x:1200,y:0,z:1100}}),r=new CollisionEngine().validate(e);expect(r.issues.some(i=>i.code==="APPLIANCE_COLLISION_APPLIANCE")).toBe(true);expect(r.issues.some(i=>i.code==="APPLIANCE_OVERLAP")).toBe(true)});
 it("detects insufficient clearance without solid overlap",()=>{const s=setup(),e=inject(s,appliance(1),{...appliance(2),position:{x:1600,y:0,z:1000}}),r=new CollisionEngine().validate(e);expect(r.issues.some(i=>i.code==="CLEARANCE_INSUFFICIENT")).toBe(true);expect(r.issues.some(i=>i.code==="APPLIANCE_COLLISION_APPLIANCE")).toBe(false)});
 it("detects Wall collision and invasion",()=>{const s=setup(),e=inject(s,{...appliance(),position:{x:1000,y:0,z:0}}),r=new CollisionEngine().validate(e);expect(r.issues.some(i=>i.code==="APPLIANCE_COLLISION_WALL")).toBe(true);expect(r.issues.some(i=>i.code==="APPLIANCE_INVADES_WALL")).toBe(true)});
 it("detects outside and partially external Appliances",()=>{const a=setup(),outside=new CollisionEngine().validate(inject(a,{...appliance(),position:{x:5000,y:0,z:5000}}));expect(outside.issues.some(i=>i.code==="APPLIANCE_OUTSIDE_ENVIRONMENT")).toBe(true);const b=setup(),partial=new CollisionEngine().validate(inject(b,{...appliance(),position:{x:3700,y:0,z:1000}}));expect(partial.issues.some(i=>i.code==="APPLIANCE_PARTIALLY_EXTERNAL")).toBe(true)});
 it("detects an Appliance blocking an Opening",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,wall=e.architectures[0]!;e.architectures.push(toOpeningArchitecture({id:aid(90),environmentId:e.id,hostWallId:wall.id,offset:1000,sillHeight:0,width:1000,height:2100,finish:"raw"},wall));s.foundation.openProject(JSON.stringify(p));const r=new CollisionEngine().validate(inject(s,{...appliance(),position:{x:1100,y:0,z:0}}));expect(r.issues.some(i=>i.code==="APPLIANCE_BLOCKS_OPENING")).toBe(true)});
 it("rejects invalid volumes and missing hosts",()=>{const a=setup();expect(a.c.add({...appliance(),collisionVolume:{width:0,height:1,depth:1}},"u",1).success).toBe(false);const b=setup();expect(b.c.add({...appliance(),hostSurfaceId:aid(99)},"u",1).success).toBe(false)});
 it("rejects duplicate and missing references",()=>{const{c}=setup(),a=appliance();c.add(a,"u",1);expect(c.add(a,"u",2).success).toBe(false);expect(c.move(ids.environment,aid(99),{x:0,y:0,z:0},"u",3).success).toBe(false);expect(c.update({...a,id:aid(99)},"u",4).success).toBe(false);expect(c.delete(ids.environment,aid(99),"u",5).success).toBe(false)});
 it("rolls back on collision and RuleRunner rejection",()=>{const s=setup(),a=appliance();s.c.add(a,"u",1);const before=s.origin.getProject();expect(s.c.move(ids.environment,a.id,{x:0,y:0,z:0},"u",2).success).toBe(false);expect(s.origin.getProject()).toEqual(before);const registry=new RuleRegistry();registry.registerRule({id:"r",displayName:"r",description:"r",severity:"error",enabled:true,analyze:()=>[{code:"R",severity:"error",path:"/",message:"R"}]});const c=new AppliancesController(s.studio,new RuleRunner(registry));expect(c.add(appliance(2),"u",3).success).toBe(false)});
 it("cascades Surface deletion through Opening, Technical Point and hosted Appliance",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,host=e.architectures[0]!,opening=toOpeningArchitecture({id:aid(90),environmentId:e.id,hostWallId:host.id,offset:500,sillHeight:500,width:500,height:1000,finish:"raw"},host),technical=toTechnicalInfrastructure({id:aid(91),environmentId:e.id,hostSurfaceId:host.id,kind:"outlet",category:"electrical",position:{x:1000,y:1000,z:0}}),hosted={...appliance(),hostSurfaceId:host.id};e.architectures.push(opening);e.infrastructures.push(technical,...encodeAppliance(hosted));s.foundation.openProject(JSON.stringify(p));const cascade=new EnvironmentalCascadeController(s.studio,new RuleRunner(new RuleRegistry()));expect(cascade.deleteSurface(e.id,host.id,"u",1).success).toBe(true);const after=s.origin.getProject().environments[0]!;expect(after.architectures.some(v=>v.id===host.id||v.id===opening.id)).toBe(false);expect(after.infrastructures).toHaveLength(0)});
 it("rolls back cascade when RuleRunner rejects and handles missing Surface",()=>{const s=setup(),registry=new RuleRegistry();registry.registerRule({id:"r",displayName:"r",description:"r",severity:"error",enabled:true,analyze:()=>[{code:"R",severity:"error",path:"/",message:"R"}]});const c=new EnvironmentalCascadeController(s.studio,new RuleRunner(registry)),before=s.origin.getProject();expect(c.deleteSurface(ids.environment,wallId(1),"u",1).success).toBe(false);expect(s.origin.getProject()).toEqual(before);expect(c.deleteSurface(ids.environment,aid(99),"u",2).success).toBe(false)});
 it("projects Technical Points and Appliances as derived public Presentation state",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,host=e.architectures[0]!;e.infrastructures.push(toTechnicalInfrastructure({id:aid(91),environmentId:e.id,hostSurfaceId:host.id,kind:"outlet",category:"electrical",position:{x:1000,y:1000,z:0}}),...encodeAppliance({...appliance(1),hostSurfaceId:host.id}),...encodeAppliance(appliance(2)));s.foundation.openProject(JSON.stringify(p));const presentation=s.studio.viewerHost.presentation,events:string[]=[];presentation.controller.subscribe(v=>events.push(v.type));new EnvironmentalPresentation(presentation).sync(p,1);const roots=presentation.repository.scene.get().roots;expect(roots.find(v=>v.projectEntityId===host.id)!.children).toHaveLength(2);expect(roots.some(v=>v.projectEntityId===aid(2))).toBe(true);expect(events).toContain("SceneChanged")});
 it("covers codec defaults, optional host and type predicates",()=>{const [main,clearance]=encodeAppliance(appliance());expect(isAppliance(main)).toBe(true);expect(isClearance(main)).toBe(false);expect(isClearance(clearance)).toBe(true);const decoded=decodeAppliance({...main,type:"appliance:",installationVolume:null},{...clearance,installationVolume:null});expect(decoded.kind).toBe("generic");expect(decoded.hostSurfaceId).toBeUndefined();expect(decoded.collisionVolume).toEqual({width:0,height:0,depth:0});expect(decodeAppliance({...main,hostId:wallId(1)},clearance).hostSurfaceId).toBe(wallId(1))});
 it("handles environments without boundary Walls and incomplete appliance pairs",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!;e.architectures=[];const pair=encodeAppliance(appliance());e.infrastructures.push(pair[0]);expect(new CollisionEngine().validate(e).valid).toBe(true);e.infrastructures.push(pair[1]);expect(new CollisionEngine().validate(e).valid).toBe(true)});
 it("covers invalid clearance and vertical environment bounds",()=>{const a=setup(),r=new CollisionEngine().validate(inject(a,{...appliance(),clearanceVolume:{width:0,height:0,depth:0}}));expect(r.issues.some(i=>i.code==="INVALID_APPLIANCE_VOLUME")).toBe(true);const b=setup(),vertical=new CollisionEngine().validate(inject(b,{...appliance(),position:{x:1000,y:2600,z:1000}}));expect(vertical.issues.some(i=>i.code==="APPLIANCE_PARTIALLY_EXTERNAL")).toBe(true)});
 it("covers orphan Opening collision fallback",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,orphan={...toOpeningArchitecture({id:aid(90),environmentId:e.id,hostWallId:wallId(1),offset:0,sillHeight:0,width:1000,height:1000,finish:"raw"},e.architectures[0]!),hostId:aid(99),position:{x:1000,y:0,z:1000},size:{width:500,height:1000,depth:500}};e.architectures.push(orphan);s.foundation.openProject(JSON.stringify(p));const result=new CollisionEngine().validate(inject(s,appliance()));expect(result.issues.some(i=>i.code==="APPLIANCE_BLOCKS_OPENING")).toBe(true)});
 it("handles missing environments across Appliance and cascade controllers",()=>{const s=setup();expect(s.c.add({...appliance(),environmentId:aid(99)},"u",1).success).toBe(false);expect(s.c.get(aid(99),aid(1))).toBeUndefined();const cascade=new EnvironmentalCascadeController(s.studio,new RuleRunner(new RuleRegistry()));expect(cascade.deleteSurface(aid(99),wallId(1),"u",2).success).toBe(false)});
});
