import type { InputMapper } from "../mapping/InputMapper"; import type { ConstructorContext } from "../ConstructorContext"; import { ConstructorReport } from "../ConstructorReport"; import { ConstructorResult } from "../ConstructorResult"; import type { ConstructorResultSnapshot, ConstructionReportEntry, ConstructionStage } from "../interfaces/ConstructorTypes"; import type { BuildStage } from "./BuildStage"; import type { CommitStage } from "./CommitStage"; import type { ValidationStage } from "./ValidationStage";
export class ConstructionPipeline {
  constructor(private readonly inputMapper: InputMapper, private readonly build: BuildStage, private readonly validation: ValidationStage, private readonly commit: CommitStage, private readonly onStage: (stage: ConstructionStage) => void = () => {}) {}
  run(context: ConstructorContext): ConstructorResultSnapshot {
    const report = new ConstructorReport(context.now); const failures: ConstructionReportEntry[] = []; const warnings: ConstructionReportEntry[] = [];
    try {
      let started = context.now(); context.mapped = this.inputMapper.map(context.input.descriptor); report.add({ stage: "INPUT_MAPPING", rule: null, code: "INPUT_MAPPED", message: "Input mapped", entity: context.input.transactionId, severity: "info" }, started); this.onStage("INPUT_MAPPING");
      started = context.now(); this.build.execute(context); report.add({ stage: "BUILD", rule: null, code: "ENTITY_BUILT", message: "Project hierarchy built", entity: context.project?.id ?? "", severity: "info" }, started); this.onStage("BUILD");
      started = context.now(); const validation = this.validation.execute(context); for (const error of validation.schemaErrors) { const entry = { stage: "SCHEMA_VALIDATION" as const, rule: null, code: error.code, message: error.message, entity: error.path, severity: "error" as const, durationMs: 0 }; failures.push(entry); report.add(entry, started); } report.add({ stage: "SCHEMA_VALIDATION", rule: "SchemaValidator", code: validation.schemaErrors.length ? "SCHEMA_FAILED" : "SCHEMA_VALID", message: validation.schemaErrors.length ? "Schema validation failed" : "Schema validation passed", entity: context.project?.id ?? "", severity: validation.schemaErrors.length ? "error" : "info" }, started); this.onStage("SCHEMA_VALIDATION");
      if (validation.schemaErrors.length) return new ConstructorResult({ success: false, failures, warnings, report: report.get() }).get();
      started = context.now(); for (const result of validation.ruleResults) { const entry = { stage: "RULE_VALIDATION" as const, rule: result.code, code: result.code, message: result.message, entity: result.path, severity: result.severity, durationMs: 0 }; (result.severity === "error" ? failures : warnings).push(entry); report.add(entry, started); } report.add({ stage: "RULE_VALIDATION", rule: "RuleRunner", code: failures.length ? "RULES_FAILED" : "RULES_EXECUTED", message: failures.length ? "Rule validation failed" : "Official rules executed", entity: context.project?.id ?? "", severity: failures.length ? "error" : "info" }, started); this.onStage("RULE_VALIDATION");
      if (failures.length) return new ConstructorResult({ success: false, failures, warnings, report: report.get() }).get();
      started = context.now(); const request = this.commit.execute(context); report.add({ stage: "COMMIT", rule: null, code: "TRANSACTION_PREPARED", message: "TransactionRequest prepared", entity: context.project?.id ?? "", severity: "info" }, started); this.onStage("COMMIT");
      if (!context.project) throw new Error("Construction project was lost before result");
      return new ConstructorResult({ success: true, failures, warnings, entity: context.project, report: report.get(), transactionRequest: request }).get();
    } catch (error: unknown) { const message = error instanceof Error ? error.message : "Unknown construction error"; const entry = { stage: "INPUT_MAPPING" as const, rule: null, code: "CONSTRUCTION_ERROR", message, entity: context.input.transactionId, severity: "error" as const, durationMs: 0 }; failures.push(entry); report.add(entry); return new ConstructorResult({ success: false, failures, warnings, report: report.get() }).get(); }
  }
}
