import { describe, expect, it, vi } from "vitest";
import type { CAMPackageSnapshot, ToolpathOperationSnapshot } from "../../mobi-cam/src/interfaces/CAMTypes";
import { GCodeContext } from "../src/GCodeContext"; import { GCodeController } from "../src/GCodeController"; import { GCodeReport } from "../src/GCodeReport"; import { GCodeRepository } from "../src/GCodeRepository"; import { GCodeResult } from "../src/GCodeResult"; import { GCodeSession } from "../src/GCodeSession"; import { MachineProfileRegistry } from "../src/MachineProfileRegistry"; import { MobiGCode } from "../src/MobiGCode"; import { PostProcessorRegistry } from "../src/PostProcessorRegistry"; import { GCodeEvent } from "../src/events/GCodeEvent"; import { GCodeEventBus } from "../src/events/GCodeEventBus"; import { GCodePackage } from "../src/export/GCodePackage"; import { CommandGenerator } from "../src/generator/CommandGenerator"; import { FooterGenerator } from "../src/generator/FooterGenerator"; import { GCodeGenerator } from "../src/generator/GCodeGenerator"; import { HeaderGenerator } from "../src/generator/HeaderGenerator"; import { MobiGCode as PublicGCode } from "../src/index"; import type { ControllerType, GCodeInput, GCodeMachineProfile, PostProcessor } from "../src/interfaces/GCodeTypes"; import { NeutralToolpathReader } from "../src/parser/NeutralToolpathReader"; import { BiessePostProcessor } from "../src/processors/BiessePostProcessor"; import { FanucPostProcessor } from "../src/processors/FanucPostProcessor"; import { HomagPostProcessor } from "../src/processors/HomagPostProcessor"; import { MorbidelliPostProcessor } from "../src/processors/MorbidelliPostProcessor"; import { SCMPostProcessor } from "../src/processors/SCMPostProcessor"; import { SiemensPostProcessor } from "../src/processors/SiemensPostProcessor"; import { DryRunValidator } from "../src/simulation/DryRunValidator"; import { FingerprintValidator } from "../src/validation/FingerprintValidator"; import { MachineValidator } from "../src/validation/MachineValidator"; import { SyntaxValidator } from "../src/validation/SyntaxValidator";

const fingerprint = { algorithm: "sha256" as const, value: "abc123", version: "1.0.0" as const, logicalTimestamp: 7, projectId: "project-1" };
const operation: ToolpathOperationSnapshot = { id: "op-1", partId: "part-1", type: "PROFILE", toolId: "router", contour: { points: [{ x: 2, y: 3 }], closed: true }, depth: 18 };
function cam(): CAMPackageSnapshot { return { projectId: "project-1", fingerprint: structuredClone(fingerprint), toolpath: { format: "mobi-neutral-toolpath-v1", fingerprint: structuredClone(fingerprint), machineCode: [], plan: { id: "plan", projectId: "project-1", fingerprint: structuredClone(fingerprint), stage: "PACKAGED", operations: [structuredClone(operation)], sequence: { operations: [structuredClone(operation)] }, machine: null } } }; }
function profile(controller: ControllerType = "FANUC", id = controller.toLowerCase()): GCodeMachineProfile { return { id, displayName: `${controller} profile`, controller, supportedOperations: ["PROFILE", "POCKET", "DRILL", "GROOVE", "ENGRAVING"], version: "1.0" }; }
function input(machineProfileId = "fanuc"): GCodeInput { return { camPackage: cam(), currentFingerprint: "abc123", machineProfileId, logicalTimestamp: 10 }; }

describe("Mobi G-Code Foundation v1", () => {
  it("runs the complete validated export pipeline", () => { const app = new PublicGCode(); app.createSession("g"); app.registerMachine(profile()); const result = app.generate(input()); expect(result.success).toBe(true); expect(result.package?.files[0]).toMatchObject({ controller: "FANUC", fingerprint: "abc123", projectId: "project-1", machineProfileId: "fanuc" }); expect(result.package?.files[0]?.content).toContain("FINGERPRINT=abc123"); });
  it("generates isolated syntax for all six controllers", () => { const processors = [new FanucPostProcessor(), new HomagPostProcessor(), new BiessePostProcessor(), new SCMPostProcessor(), new MorbidelliPostProcessor(), new SiemensPostProcessor()]; const markers = ["G01", "HOP PROFILE", "BPP:PROFILE", "SCM_OP", "MORB PROFILE", "G1 X="]; for (const [index, processor] of processors.entries()) { const file = processor.process(cam(), profile(processor.controller), 10); expect(file.content).toContain(markers[index]); expect(new SyntaxValidator().validate(file)).toEqual([]); expect(new DryRunValidator().validate(file, [operation])).toEqual([]); } });
  it("supports multiple profiles deterministically", () => { const app = new MobiGCode(); app.createSession("g"); app.registerMachine(profile("FANUC")); app.registerMachine(profile("SIEMENS")); expect(app.generate(input("fanuc")).package).toEqual(app.generate(input("fanuc")).package); expect(app.generate(input("siemens")).package?.files[0]?.controller).toBe("SIEMENS"); });
  it("blocks invalid fingerprints", () => { const app = new MobiGCode(); app.createSession("g"); app.registerMachine(profile()); const value = input(); value.currentFingerprint = "changed"; expect(app.generate(value)).toMatchObject({ success: false, blocked: true, package: null }); expect(new FingerprintValidator().validate(value)).toBe(false); });
  it("blocks missing profiles, processors and unsupported operations", () => { const profiles = new MachineProfileRegistry(); const processors = new PostProcessorRegistry(); expect(new GCodeController(profiles, processors).generate(input()).report.entries[0]?.code).toBe("MACHINE_PROFILE_NOT_FOUND"); profiles.register({ ...profile(), supportedOperations: ["DRILL"] }); expect(new GCodeController(profiles, processors).generate(input()).report.entries[0]?.code).toContain("UNSUPPORTED_OPERATION"); profiles.unregister("fanuc"); profiles.register(profile()); expect(new GCodeController(profiles, processors).generate(input()).report.entries[0]?.code).toBe("POST_PROCESSOR_NOT_FOUND"); });
  it("rejects invalid neutral input, timestamp and processor mismatch", () => { const bad = input(); bad.camPackage.toolpath.plan.stage = "VALIDATED"; const profiles = new MachineProfileRegistry(); profiles.register(profile()); const processors = new PostProcessorRegistry(); processors.register(new FanucPostProcessor()); expect(new GCodeController(profiles, processors).generate(bad).report.entries[0]?.code).toContain("Invalid neutral"); expect(new GCodeController(profiles, processors).generate({ ...input(), logicalTimestamp: -1 }).report.entries[0]?.code).toBe("INVALID_TIMESTAMP"); expect(() => new GCodeGenerator().generate(new FanucPostProcessor(), cam(), profile("SIEMENS"), 1)).toThrow("mismatch"); });
  it("validates syntax and dry-run inconsistencies", () => { const file = new FanucPostProcessor().process(cam(), profile(), 1); expect(new SyntaxValidator().validate({ ...file, content: "NaN\0" })).toEqual(expect.arrayContaining(["MISSING_HEADER:PROJECT", "INVALID_NUMERIC_COMMAND", "INVALID_CHARACTER"])); expect(new DryRunValidator().validate(file, [])).toEqual(["NO_OPERATIONS"]); expect(new DryRunValidator().validate({ ...file, content: file.content.replace("op-1", "missing") }, [{ ...operation, depth: 0 }])).toEqual(["INVALID_DEPTH:op-1", "MISSING_COMMAND:op-1"]); });
  it("rolls back repository export after failure", () => { const app = new MobiGCode(); app.createSession("g"); app.registerMachine(profile()); const good = app.generate(input()); const bad = input(); bad.currentFingerprint = "bad"; app.generate(bad); expect(app.getPackage()).toEqual(good.package); app.clear(); expect(app.getPackage()).toBeNull(); });
  it("manages registries", () => { const machines = new MachineProfileRegistry(); machines.register(profile()); expect(machines.get("fanuc")?.id).toBe("fanuc"); expect(machines.list()).toHaveLength(1); expect(() => machines.register(profile())).toThrow("Duplicate"); expect(() => new MachineProfileRegistry().register({ ...profile(), id: "" })).toThrow("Invalid"); expect(machines.unregister("fanuc")).toBe(true); const processors = new PostProcessorRegistry(); processors.register(new FanucPostProcessor()); expect(processors.get("FANUC")).toBeInstanceOf(FanucPostProcessor); expect(processors.list()).toEqual(["FANUC"]); expect(() => processors.register(new FanucPostProcessor())).toThrow("Duplicate"); expect(processors.unregister("FANUC")).toBe(true); });
  it("provides component contracts", () => { expect(new NeutralToolpathReader().read(cam())).toEqual([operation]); const positioned: ToolpathOperationSnapshot = { id: "p", partId: "part", type: "DRILL", toolId: "drill", position: { x: 4, y: 5 }, depth: 18 }; expect(new CommandGenerator().coordinates(positioned)).toEqual({ x: 4, y: 5, z: -18 }); expect(new HeaderGenerator().create(";", "p", "f", profile(), 1)).toHaveLength(5); expect(new FooterGenerator().create("M30")).toBe("M30"); expect(() => new FooterGenerator().create(" ")).toThrow("empty"); const context = new GCodeContext(input()); context.setProfile(profile()); context.setOperations([operation]); const file = new FanucPostProcessor().process(cam(), profile(), 1); const pkg = new GCodePackage().build(file, profile()); context.setOutput(pkg); expect(context.get().output).toEqual(pkg); const report = new GCodeReport(() => 2); report.add({ stage: "READ", code: "OK", message: "ok", severity: "info", entity: "p" }); expect(report.get().durationMs).toBe(0); expect(new GCodeResult({ success: true, blocked: false, package: pkg, report: report.get() }).get().success).toBe(true); const repository = new GCodeRepository(); repository.save(pkg); pkg.files[0]!.content = "changed"; expect(repository.get()?.files[0]?.content).not.toBe("changed"); repository.clear(); });
  it("publishes isolated events", () => { const app = new MobiGCode(); const listener = vi.fn(); app.subscribe(listener); app.createSession("g"); app.registerMachine(profile()); app.generate(input()); const bad = input(); bad.currentFingerprint = "bad"; app.generate(bad); expect(listener.mock.calls.map(call => call[0].type)).toEqual(["GCODE_STARTED", "GCODE_VALIDATED", "GCODE_EXPORTED", "GCODE_STARTED", "GCODE_BLOCKED"]); app.unsubscribe(listener); expect(() => new GCodeEvent("GCODE_STARTED", "g", "p", -1)).toThrow("non-negative"); const bus = new GCodeEventBus(); const first = vi.fn(event => { event.projectId = "changed"; }); const second = vi.fn(); bus.subscribe(first); bus.subscribe(second); bus.publish(new GCodeEvent("GCODE_FAILED", "g", "p", 0).get()); expect(second).toHaveBeenCalledWith(expect.objectContaining({ projectId: "p" })); bus.unsubscribe(first); bus.clear(); });
  it("enforces session lifecycle", () => { const app = new MobiGCode(); expect(() => app.generate(input())).toThrow("No active"); expect(app.createSession("g").active).toBe(true); expect(app.closeSession().active).toBe(false); expect(() => new GCodeSession().create(" ")).toThrow("empty"); expect(app.unregisterMachine("missing")).toBe(false); });
  it("rejects malformed generated files", () => { expect(new MachineValidator().validate({ ...profile(), id: "", version: "" }, [operation])).toContain("INVALID_MACHINE_PROFILE"); const broken: PostProcessor = { controller: "FANUC", process: () => ({ name: "x.nc", controller: "FANUC", content: "", projectId: "p", fingerprint: "f", version: "v", logicalTimestamp: 0, machineProfileId: "m" }) }; const profiles = new MachineProfileRegistry(); profiles.register(profile()); const processors = new PostProcessorRegistry(); processors.register(broken); expect(new GCodeController(profiles, processors).generate(input()).report.entries[0]?.code).toContain("EMPTY_FILE"); });
});
