import{describe,expect,it}from"vitest";import type{Diagnostic,IntegrityReport}from"../../mobi-cognitive-analyzer/src/DiagnosticTypes";import{ChecklistPanel}from"../src/ChecklistPanel";import{CognitiveDashboard}from"../src/CognitiveDashboard";import{DiagnosticsPanel}from"../src/DiagnosticsPanel";import{ProjectStatusPanel}from"../src/ProjectStatusPanel";
const diagnostic=(severity:Diagnostic["severity"],origin:string,entityId:string):Diagnostic=>({id:`${origin}:${entityId}`,origin,ruleId:`RULE_${origin}`,severity,entityId,message:`${origin} message`,traceability:{pipeline:origin,ruleId:`RULE_${origin}`,path:`/entities/${entityId}`,projectId:"project",sequence:7}});const report:IntegrityReport={projectId:"project",generatedAtSequence:7,status:"ISSUES",diagnostics:[diagnostic("error","topology","wall"),diagnostic("warning","architecture","room"),diagnostic("info","production","project")],checklist:[{id:"check:topology",label:"topology",status:"FAIL",diagnosticIds:["topology:wall"]},{id:"check:materials",label:"materials",status:"PASS",diagnosticIds:[]}],counts:{info:1,warning:1,error:1},projectFingerprint:"abcdef01"};
describe("cognitive ui",()=>{
 it("starts as an empty read-only status view",()=>{expect(new CognitiveDashboard().get()).toEqual({status:"HEALTHY",projectId:"",checklist:[],diagnostics:[],alerts:[],inconsistencies:[],events:[],readOnly:true,empty:true})});
 it("presents checklist, diagnostics, alerts, inconsistencies and project status",()=>{const dashboard=new CognitiveDashboard(),view=dashboard.present(report,[{source:"event-bus",type:"SESSION_STARTED",sequence:1}]);expect(view).toMatchObject({status:"ISSUES",projectId:"project",readOnly:true,empty:false});expect(view.diagnostics).toHaveLength(3);expect(view.alerts).toHaveLength(2);expect(view.inconsistencies).toHaveLength(1);expect(view.events).toHaveLength(1)});
 it("filters diagnostics deterministically",()=>{const dashboard=new CognitiveDashboard();dashboard.present(report);expect(dashboard.filter({severity:"error"})).toHaveLength(1);expect(dashboard.filter({origin:"architecture"})[0]!.entityId).toBe("room");expect(dashboard.filter({entityId:"project"})[0]!.severity).toBe("info");expect(dashboard.filter({severity:"error",origin:"architecture"})).toEqual([]);expect(dashboard.filter({})).toHaveLength(3)});
 it("renders checklist rows without actions",()=>{expect(new ChecklistPanel().render(report.checklist)).toEqual([{id:"check:topology",label:"topology",status:"FAIL",count:1},{id:"check:materials",label:"materials",status:"PASS",count:0}])});
 it("renders diagnostic rule and traceability fields",()=>{const row=new DiagnosticsPanel().render(report.diagnostics)[0]!;expect(row).toMatchObject({id:"topology:wall",severity:"error",origin:"topology",rule:"RULE_topology",entity:"wall",message:"topology message",trace:"/entities/wall@7"})});
 it("renders immutable project integrity status",()=>{const status=new ProjectStatusPanel().render(report);expect(status).toEqual({projectId:"project",status:"ISSUES",fingerprint:"abcdef01",counts:{info:1,warning:1,error:1},sequence:7});status.counts.error=99;expect(report.counts.error).toBe(1)});
 it("does not expose suggestion, correction, automation or mutation commands",()=>{const view=new CognitiveDashboard().present(report);expect("suggestions"in view).toBe(false);expect("fix"in view).toBe(false);expect("actions"in view).toBe(false)});
});
