import type { Environment, Project, Vector3 } from "../../../builder/types/ProjectTypes";
import type { MobiStudioApplication } from "../../mobi-studio/src/MobiStudioApplication";
import type { EditIntentInput } from "../../mobi-studio/src/interfaces/StudioApplicationTypes";
import { collinear, connectEndpoint, fromArchitecture, samePoint, toArchitecture, wallLength } from "./WallGeometry";
import type { WallDescriptor, WallOperation, WallPreview, WallResult } from "./WallTypes";
export class WallsController{
 private active:WallPreview|undefined;
 constructor(private readonly studio:MobiStudioApplication){}
 preview(operation:WallOperation,walls:WallDescriptor[]):WallResult{if(this.active)return{success:false,code:"EDIT_ALREADY_ACTIVE"};try{walls.forEach(toArchitecture)}catch(e){return{success:false,code:(e as Error).message}}this.active={operation,walls:structuredClone(walls)};return{success:true,code:"PREVIEW_STARTED"}}
 cancel():WallResult{if(!this.active)return{success:false,code:"NO_ACTIVE_EDIT"};this.active=undefined;return{success:true,code:"CANCELLED"}}
 create(wall:WallDescriptor,author:string,timestamp:number){return this.start("CREATE_WALL",[wall],author,timestamp,p=>{const env=this.env(p,wall.environmentId);if(env.architectures.some(x=>x.id===wall.id))throw new Error("DUPLICATE_WALL");this.rejectDuplicate(env,wall);env.architectures.push(toArchitecture(wall))})}
 update(wall:WallDescriptor,author:string,timestamp:number){return this.start("UPDATE_WALL",[wall],author,timestamp,p=>{const env=this.env(p,wall.environmentId),i=env.architectures.findIndex(x=>x.id===wall.id&&x.type==="wall");if(i<0)throw new Error("WALL_NOT_FOUND");this.rejectDuplicate(env,wall,wall.id);env.architectures[i]=toArchitecture(wall)})}
 delete(environmentId:string,id:string,author:string,timestamp:number){return this.start("DELETE_WALL",[],author,timestamp,p=>{const env=this.env(p,environmentId),i=env.architectures.findIndex(x=>x.id===id&&x.type==="wall");if(i<0)throw new Error("WALL_NOT_FOUND");env.architectures.splice(i,1)},id)}
 split(environmentId:string,id:string,point:Vector3,newIds:[string,string],author:string,timestamp:number){const current=this.wall(environmentId,id);if(!current)return{success:false,code:"WALL_NOT_FOUND"};const a={...current,id:newIds[0],end:point},b={...current,id:newIds[1],start:point};if(Math.abs(wallLength(current.start,point)+wallLength(point,current.end)-wallLength(current.start,current.end))>1e-6)return{success:false,code:"SPLIT_POINT_OUTSIDE_WALL"};return this.start("SPLIT_WALL",[a,b],author,timestamp,p=>{const env=this.env(p,environmentId);env.architectures=env.architectures.filter(x=>x.id!==id);env.architectures.push(toArchitecture(a),toArchitecture(b))},id)}
 merge(environmentId:string,ids:[string,string],newId:string,author:string,timestamp:number){const a=this.wall(environmentId,ids[0]),b=this.wall(environmentId,ids[1]);if(!a||!b)return{success:false,code:"WALL_NOT_FOUND"};if(!collinear(a,b))return{success:false,code:"WALLS_NOT_COLLINEAR"};let start:Vector3,end:Vector3;if(samePoint(a.end,b.start)){start=a.start;end=b.end}else if(samePoint(b.end,a.start)){start=b.start;end=a.end}else return{success:false,code:"WALLS_NOT_CONNECTED"};const merged={...a,id:newId,start,end};return this.start("MERGE_WALLS",[merged],author,timestamp,p=>{const env=this.env(p,environmentId);env.architectures=env.architectures.filter(x=>!ids.includes(x.id));env.architectures.push(toArchitecture(merged))},newId)}
 connect(kind:"L"|"T"|"X",environmentId:string,ids:string[],point:Vector3,author:string,timestamp:number){const expected={L:2,T:3,X:4}[kind];if(ids.length!==expected||new Set(ids).size!==ids.length)return{success:false,code:"INVALID_CONNECTION_CARDINALITY"};const walls=ids.map(id=>this.wall(environmentId,id));if(walls.some(x=>!x))return{success:false,code:"WALL_NOT_FOUND"};const updated=walls.map(w=>connectEndpoint(w!,point));try{updated.forEach(toArchitecture)}catch(e){return{success:false,code:(e as Error).message}}return this.start(`CONNECT_WALLS_${kind}` as WallOperation,updated,author,timestamp,p=>{const env=this.env(p,environmentId);for(const w of updated){const i=env.architectures.findIndex(x=>x.id===w.id);env.architectures[i]=toArchitecture(w)}},ids.join("+"))}
 commit(author:string,timestamp:number):WallResult{if(!this.active)return{success:false,code:"NO_ACTIVE_EDIT"};const active=this.active;return this.execute(active.operation,active.walls[0]?.id??"walls",author,timestamp,p=>{for(const wall of active.walls){const env=this.env(p,wall.environmentId),i=env.architectures.findIndex(x=>x.id===wall.id);if(i>=0)env.architectures[i]=toArchitecture(wall);else env.architectures.push(toArchitecture(wall))}})}
 private start(op:WallOperation,walls:WallDescriptor[],author:string,timestamp:number,mutation:(p:Project)=>void,entityId=walls[0]?.id??"walls"){if(this.active)return{success:false,code:"EDIT_ALREADY_ACTIVE"};try{walls.forEach(toArchitecture)}catch(e){return{success:false,code:(e as Error).message}}this.active={operation:op,walls:structuredClone(walls)};return this.execute(op,entityId,author,timestamp,mutation)}
 private execute(op:WallOperation,entityId:string,author:string,timestamp:number,mutation:(p:Project)=>void):WallResult{const preview=this.active!;let input:EditIntentInput;try{input={id:`${op}:${entityId}:${timestamp}`,entityId,property:"architecture",value:structuredClone(preview.walls),author,logicalTimestamp:timestamp,operationName:op,operation:origin=>{const p=origin.getProject();mutation(p);origin.openProject(JSON.stringify(p))},preview:{apply:()=>{},revert:()=>{}}};this.studio.beginEdit(input);const transaction=this.studio.commitEdit();this.active=undefined;return{success:transaction.success,code:transaction.success?"COMMITTED":"TRANSACTION_ROLLED_BACK",transaction}}catch(e){this.active=undefined;return{success:false,code:(e as Error).message}}}
 private env(p:Project,id:string):Environment{const e=p.environments.find(x=>x.id===id);if(!e)throw new Error("ENVIRONMENT_NOT_FOUND");return e}
 private wall(envId:string,id:string){try{const e=this.env(this.studio.foundation.getProject(),envId),w=e.architectures.find(x=>x.id===id&&x.type==="wall");return w?fromArchitecture(w):undefined}catch{return undefined}}
 private rejectDuplicate(e:Environment,w:WallDescriptor,ignore?:string){const duplicate=e.architectures.filter(x=>x.type==="wall"&&x.id!==ignore).map(fromArchitecture).some(x=>(samePoint(x.start,w.start)&&samePoint(x.end,w.end))||(samePoint(x.start,w.end)&&samePoint(x.end,w.start)));if(duplicate)throw new Error("DUPLICATE_WALL")}
}
