import type{Camera,Scene}from"three";import{describe,expect,it}from"vitest";import{ProjectBuilder}from"../../../builder/ProjectBuilder";import{environmentInput,ids,moduleInput,partInput,projectInput}from"../../../builder/tests/fixture";import{MobiCopilot}from"../../../copilot/MobiCopilot";import{MissingMaterialRule}from"../../../copilot/rulebook/packages/Cabinetry/MissingMaterialRule";import{RuleRegistry}from"../../../copilot/rules/RuleRegistry";import{RuleRunner}from"../../../copilot/rules/RuleRunner";import{MobiOrigin}from"../../../origin/MobiOrigin";import{PresentationCore}from"../../../presentation/PresentationCore";import{MobiStudio}from"../../../studio/MobiStudio";import{SyncManager}from"../../../sync/SyncManager";import{Viewer}from"../../../viewer/Viewer";import type{FrameScheduler,RenderBackend}from"../../../viewer/interfaces/ViewerTypes";import{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import type{Diagnostic}from"../../mobi-cognitive-analyzer/src/DiagnosticTypes";import{PropositionFactory}from"../../mobi-cognitive-engine/src/PropositionFactory";import type{Proposition}from"../../mobi-cognitive-engine/src/PropositionTypes";import{AutoFixAuditLog}from"../src/AutoFixAuditLog";import{AutoFixCoordinator}from"../src/AutoFixCoordinator";import{AutoFixNotifier}from"../src/AutoFixNotifier";import{AutoFixPolicyEngine}from"../src/AutoFixPolicyEngine";import type{GoldenAutoFixRule}from"../src/AutoFixTypes";import{GoldenRules}from"../src/GoldenRules";
class B implements RenderBackend{render(_s:Scene,_c:Camera){}setSize(){}dispose(){}}class S implements FrameScheduler{request(){return 1}cancel(){}}
const diagnostic=(origin="materials",ruleId="MATERIAL_MISSING_REFERENCE",entityId:string=ids.part):Diagnostic=>({id:`diagnostic:${ruleId}:${entityId}`,origin,ruleId,severity:"error",entityId,message:"missing material",traceability:{pipeline:origin,ruleId,path:`/parts/${entityId}/materialId`,projectId:ids.project,sequence:1}});const proposition=(d=diagnostic())=>new PropositionFactory().create(d,{action:"ASSIGN_REFERENCE",expectedImpact:"Assign deterministic material"},0,2);
function setup(rule:Parameters<RuleRegistry["registerRule"]>[0]=new MissingMaterialRule()){const origin=new MobiOrigin(),foundation=new MobiStudio(origin),presentation=new PresentationCore();presentation.createSession("p");const studio=new MobiStudioApplication({origin,foundation,presentation,viewer:new Viewer(presentation,new B(),new S()),copilot:new MobiCopilot(origin,foundation),sync:new SyncManager(origin)});studio.startSession("s");const project=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addModule(ids.environment,moduleInput).addPart(ids.module,{...partInput,materialId:""}).build();foundation.openProject(JSON.stringify(project));const registry=new RuleRegistry();registry.registerRule(rule);const runner=new RuleRunner(registry),policy=new AutoFixPolicyEngine(runner),audit=new AutoFixAuditLog(),notifier=new AutoFixNotifier(presentation),coordinator=new AutoFixCoordinator(studio,runner,policy,audit,notifier);return{origin,foundation,presentation,studio,runner,policy,audit,notifier,coordinator}}
const material=(s:ReturnType<typeof setup>)=>s.foundation.getProject().environments[0]!.modules[0]!.parts[0]!.materialId;
describe("autofix policy",()=>{
 it("marks only the documented Golden Rule as eligible",()=>{const s=setup(),decision=s.policy.evaluate(proposition(),s.foundation.getProject());expect(decision).toMatchObject({eligible:true,code:"ELIGIBLE",rule:{id:"GOLDEN_ASSIGN_MISSING_MATERIAL",autoFixable:true,sourceRuleId:"CABINETRY_MISSING_MATERIAL"}});expect(new GoldenRules().list()).toHaveLength(1)});
 it("blocks non-PENDING, non-golden and prohibited-domain proposals",()=>{const s=setup(),pending=proposition(),nonPending=structuredClone(pending);(nonPending as unknown as{status:string}).status="EXECUTING";expect(s.policy.evaluate(nonPending,s.foundation.getProject()).code).toBe("NOT_PENDING");expect(s.policy.evaluate(proposition(diagnostic("materials","UNKNOWN_RULE")),s.foundation.getProject()).code).toBe("RULE_NOT_GOLDEN");expect(s.policy.evaluate(proposition(diagnostic("topology")),s.foundation.getProject()).code).toBe("PROHIBITED_DOMAIN")});
 it("blocks action mismatch, missing entity, unsafe state and inactive RuleRunner rule",()=>{const a=setup(),wrong=proposition();(wrong.request as unknown as{action:string}).action="REVIEW_ENTITY";expect(a.policy.evaluate(wrong,a.foundation.getProject()).code).toBe("ACTION_NOT_ALLOWED");expect(a.policy.evaluate(proposition(diagnostic("materials","MATERIAL_MISSING_REFERENCE","missing")),a.foundation.getProject()).code).toBe("ENTITY_NOT_FOUND");const p=a.foundation.getProject();p.environments[0]!.modules[0]!.parts[0]!.materialId="MDF";expect(a.policy.evaluate(proposition(),p).code).toBe("UNSAFE_REQUEST");const b=setup({id:"CABINETRY_MISSING_MATERIAL",displayName:"Inactive",description:"Inactive",severity:"error",enabled:true,analyze:()=>[]});expect(b.policy.evaluate(proposition(),b.foundation.getProject()).code).toBe("RULE_NOT_ACTIVE")});
 it("blocks missing RuleRunner rules and malformed Golden flags",()=>{const empty=new RuleRunner(new RuleRegistry()),s=setup(),policy=new AutoFixPolicyEngine(empty);expect(policy.evaluate(proposition(),s.foundation.getProject()).code).toBe("RULE_NOT_ACTIVE");const base=new GoldenRules().list()[0]!,fake={getByDiagnostic:()=>({...base,autoFixable:false})}as unknown as GoldenRules;expect(new AutoFixPolicyEngine(s.runner,fake).evaluate(proposition(),s.foundation.getProject()).code).toBe("NOT_AUTOFIXABLE");const prohibited={getByDiagnostic:()=>({...base,prohibitedDomain:true})}as unknown as GoldenRules;expect(new AutoFixPolicyEngine(s.runner,prohibited).evaluate(proposition(),s.foundation.getProject()).code).toBe("PROHIBITED_DOMAIN")});
});
describe("autofix coordinator",()=>{
 it("executes an eligible correction exclusively through TransactionCoordinator",()=>{const s=setup(),result=s.coordinator.execute(proposition(),10);expect(result).toMatchObject({success:true,code:"AUTOMATED_CORRECTION",state:"COMMITTED",audit:{type:"AUTOMATED_CORRECTION",state:"COMMITTED",metadata:{sourceRuleId:"CABINETRY_MISSING_MATERIAL",originDiagnosisId:diagnostic().id,autoFixTimestamp:10,transactionRequestId:proposition().transactionRequestId}}});expect(result.audit.metadata.automatedSignature).toMatch(/^AUTO-[0-9a-f]{8}$/);expect(material(s)).toBe("MDF-15");expect((result.transaction as{status:string}).status).toBe("COMMITTED")});
 it("emits only the required discrete success notification",()=>{const s=setup();s.coordinator.execute(proposition(),11);expect(s.notifier.get()).toEqual([{message:"Ação corretiva automática aplicada.",timestamp:11,presentationSnapshotId:"0::inspection"}])});
 it("records audit entries as immutable snapshots",()=>{const s=setup();s.coordinator.execute(proposition(),12);const entries=s.audit.get();expect(entries).toHaveLength(1);entries[0]!.message="changed";expect(s.audit.get()[0]!.message).toBe("AUTOMATED_CORRECTION");expect(s.audit.forProposal(proposition().proposalId)).toHaveLength(1)});
 it("blocks an ineligible proposal without executing",()=>{const s=setup(),before=s.foundation.getProject(),result=s.coordinator.execute(proposition(diagnostic("topology")),13);expect(result).toMatchObject({success:false,state:"ROLLED_BACK",code:"PROHIBITED_DOMAIN"});expect(s.foundation.getProject()).toEqual(before);expect(s.notifier.get()).toEqual([])});
 it("rolls back integrally when the official rule remains active",()=>{const stubborn={id:"CABINETRY_MISSING_MATERIAL",displayName:"Stubborn",description:"Stubborn",severity:"error"as const,enabled:true,analyze:()=>[{code:"CABINETRY_MISSING_MATERIAL",severity:"error"as const,path:"/",message:`missing ${ids.part}`}]},s=setup(stubborn),before=s.foundation.getProject(),result=s.coordinator.execute(proposition(),14);expect(result).toMatchObject({success:false,state:"ROLLED_BACK",code:"TRANSACTION_ROLLED_BACK"});expect((result.transaction as{status:string;log:{rollbackExecuted:boolean}}).status).toBe("ROLLED_BACK");expect((result.transaction as{log:{rollbackExecuted:boolean}}).log.rollbackExecuted).toBe(true);expect(s.foundation.getProject()).toEqual(before)});
 it("supports atomic Undo and Redo through new transactions",()=>{const s=setup();s.coordinator.execute(proposition(),20);expect(material(s)).toBe("MDF-15");const undo=s.coordinator.undo(21);expect(undo).toMatchObject({success:true,state:"UNDONE"});expect(material(s)).toBe("");const redo=s.coordinator.redo(22);expect(redo).toMatchObject({success:true,state:"REDONE"});expect(material(s)).toBe("MDF-15");expect(s.audit.get().map(e=>e.state)).toEqual(["COMMITTED","UNDONE","REDONE"]);expect(s.notifier.get()).toHaveLength(2)});
 it("handles empty Undo and Redo histories",()=>{const s=setup();expect(s.coordinator.undo(1).code).toBe("NOTHING_TO_UNDO");expect(s.coordinator.redo(2).code).toBe("NOTHING_TO_REDO")});
 it("preserves Undo history when stale state forces rollback",()=>{const s=setup();s.coordinator.execute(proposition(),30);const p=s.foundation.getProject();p.environments[0]!.modules[0]!.parts[0]!.materialId="OTHER";s.foundation.openProject(JSON.stringify(p));expect(s.coordinator.undo(31).code).toBe("UNDO_ROLLED_BACK");expect(material(s)).toBe("OTHER");p.environments[0]!.modules[0]!.parts[0]!.materialId="MDF-15";s.foundation.openProject(JSON.stringify(p));expect(s.coordinator.undo(32).success).toBe(true)});
 it("preserves Redo history when stale state forces rollback",()=>{const s=setup();s.coordinator.execute(proposition(),40);s.coordinator.undo(41);const p=s.foundation.getProject();p.environments[0]!.modules[0]!.parts[0]!.materialId="OTHER";s.foundation.openProject(JSON.stringify(p));expect(s.coordinator.redo(42).code).toBe("REDO_ROLLED_BACK");p.environments[0]!.modules[0]!.parts[0]!.materialId="";s.foundation.openProject(JSON.stringify(p));expect(s.coordinator.redo(43).success).toBe(true)});
 it("has no direct commit method and never handles prohibited topology",()=>{const s=setup();expect("commit"in s.coordinator).toBe(false);expect("fixWall"in s.coordinator).toBe(false);for(const origin of["walls","rooms","openings","topology"])expect(s.policy.evaluate(proposition(diagnostic(origin)),s.foundation.getProject()).eligible).toBe(false)});
});
