import type { MobiCopilot } from "../../../copilot/MobiCopilot"; import type { MobiOrigin } from "../../../origin/MobiOrigin"; import type { PresentationCore } from "../../../presentation/PresentationCore"; import { MobiStudio } from "../../../studio/MobiStudio"; import type { SyncManager } from "../../../sync/SyncManager"; import { TransactionEngine } from "../../../transaction/TransactionEngine"; import type { Viewer } from "../../../viewer/Viewer";
import { EditIntent } from "./editor/EditIntent"; import { EditorController } from "./editor/EditorController"; import { EditorState } from "./editor/EditorState"; import { CommandDispatcher } from "./editor/CommandDispatcher"; import { StudioApplicationEvent } from "./events/StudioApplicationEvent"; import { StudioEventBus } from "./events/StudioEventBus"; import { InteractionController } from "./interaction/InteractionController"; import { KeyboardInteraction } from "./interaction/KeyboardInteraction"; import { PointerInteraction } from "./interaction/PointerInteraction"; import { SelectionInteraction } from "./interaction/SelectionInteraction"; import { ShortcutRegistry } from "./interaction/ShortcutRegistry"; import type { EditIntentInput, StudioApplicationEventType, StudioApplicationListener, StudioCommand } from "./interfaces/StudioApplicationTypes"; import { MobiStudioSession } from "./MobiStudioSession"; import { StudioCommandBus } from "./StudioCommandBus"; import { StudioRepository } from "./StudioRepository"; import { TransactionCoordinator } from "./transactions/TransactionCoordinator"; import { TransactionFeedback } from "./transactions/TransactionFeedback"; import { TransactionRequestFactory } from "./transactions/TransactionRequestFactory"; import { CopilotPanel } from "./ui/CopilotPanel"; import { DockManager } from "./ui/DockManager"; import { InspectorPanel } from "./ui/InspectorPanel"; import { ProjectTreePanel } from "./ui/ProjectTreePanel"; import { PropertyGrid } from "./ui/PropertyGrid"; import { StudioLayout } from "./ui/StudioLayout"; import { StudioMenu } from "./ui/StudioMenu"; import { StudioShell } from "./ui/StudioShell"; import { StudioStatusBar } from "./ui/StudioStatusBar"; import { StudioToolbar } from "./ui/StudioToolbar"; import { StudioWorkspace } from "./ui/StudioWorkspace"; import { ThemeManager } from "./ui/ThemeManager"; import { TransactionPanel } from "./ui/TransactionPanel"; import { ViewerHost } from "./ui/ViewerHost"; import { CopilotViewModel } from "./viewmodel/CopilotViewModel"; import { InspectorViewModel } from "./viewmodel/InspectorViewModel"; import { ProjectTreeViewModel } from "./viewmodel/ProjectTreeViewModel"; import { StudioViewModel } from "./viewmodel/StudioViewModel"; import { TransactionViewModel } from "./viewmodel/TransactionViewModel";

export interface MobiStudioDependencies { origin: MobiOrigin; presentation: PresentationCore; viewer: Viewer; copilot: MobiCopilot; sync: SyncManager; foundation?: MobiStudio }
export class MobiStudioApplication {
  readonly foundation: MobiStudio; readonly session: MobiStudioSession; readonly feedback = new TransactionFeedback(); readonly editorState = new EditorState(); readonly theme = new ThemeManager(); readonly dock = new DockManager(); readonly events = new StudioEventBus(); readonly shortcuts = new ShortcutRegistry(); readonly pointer = new PointerInteraction();
  readonly transactions: TransactionCoordinator; readonly editor: EditorController; readonly commands: StudioCommandBus; readonly repository: StudioRepository; readonly layout: StudioLayout; readonly workspace: StudioWorkspace; readonly shell: StudioShell; readonly viewerHost: ViewerHost; readonly tree: ProjectTreePanel; readonly inspector: InspectorPanel; readonly propertyGrid = new PropertyGrid(); readonly transactionPanel: TransactionPanel; readonly copilotPanel: CopilotPanel; readonly interactions: InteractionController; readonly viewModel: StudioViewModel; readonly statusBar = new StudioStatusBar();
  private logicalTimestamp = 0;
  constructor(private readonly dependencies: MobiStudioDependencies) {
    this.foundation = dependencies.foundation ?? new MobiStudio(dependencies.origin); this.session = new MobiStudioSession(this.foundation);
    this.transactions = new TransactionCoordinator(new TransactionEngine(dependencies.origin), new TransactionRequestFactory(), this.feedback); this.editor = new EditorController(dependencies.presentation, this.editorState, this.transactions);
    this.commands = new StudioCommandBus(new CommandDispatcher(this.foundation, dependencies.presentation, this.editor)); this.repository = new StudioRepository(this.session, dependencies.presentation, this.editorState, this.theme, this.feedback);
    this.layout = new StudioLayout(this.dock); this.workspace = new StudioWorkspace(this.layout); this.shell = new StudioShell(new StudioMenu(), new StudioToolbar(), this.layout, this.theme); this.viewerHost = new ViewerHost(dependencies.viewer, dependencies.presentation);
    const tree = new ProjectTreeViewModel(dependencies.presentation); const inspector = new InspectorViewModel(dependencies.presentation); const transaction = new TransactionViewModel(this.feedback); const copilot = new CopilotViewModel(dependencies.copilot);
    this.tree = new ProjectTreePanel(dependencies.presentation); this.inspector = new InspectorPanel(inspector); this.transactionPanel = new TransactionPanel(transaction); this.copilotPanel = new CopilotPanel(copilot, dependencies.presentation); this.viewModel = new StudioViewModel(this.repository, tree, inspector, transaction, copilot);
    this.interactions = new InteractionController(new KeyboardInteraction(this.shortcuts), this.pointer, new SelectionInteraction(dependencies.presentation));
  }
  startSession(id: string): void { this.session.start(id); this.viewerHost.open(`viewer:${id}`); this.repository.setStatus("Ready"); this.emit("SESSION_STARTED", id); }
  endSession(): void { this.editor.cancel(); this.viewerHost.close(); this.session.end(); this.repository.setStatus("Closed"); this.emit("SESSION_ENDED"); this.events.clear(); }
  beginEdit(input: EditIntentInput): EditIntent { const intent = new EditIntent(input); this.editor.begin(intent); this.repository.setStatus("Preview"); this.emit("PREVIEW_STARTED", intent.get().id); return intent; }
  cancelEdit(): void { this.editor.cancel(); this.repository.setStatus("Edit cancelled"); this.emit("PREVIEW_CANCELLED"); }
  commitEdit() { const result = this.editor.commit(); this.repository.setStatus(result.success ? "Committed" : "Rolled back"); this.emit(result.success ? "TRANSACTION_COMMITTED" : "TRANSACTION_ROLLED_BACK", result.transactionId); return result; }
  execute(command: StudioCommand): unknown { const result = this.commands.dispatch(command); this.emit("COMMAND_EXECUTED", command.name); return result; }
  publishNavigableProject(): "NOT_IMPLEMENTED" { return "NOT_IMPLEMENTED"; }
  setTheme(theme: "light" | "dark"): void { this.theme.set(theme); this.emit("THEME_CHANGED", theme); }
  subscribe(listener: StudioApplicationListener): void { this.events.subscribe(listener); } unsubscribe(listener: StudioApplicationListener): void { this.events.unsubscribe(listener); }
  getState() { return this.repository.get(); }
  private emit(type: StudioApplicationEventType, detail?: string): void { this.events.publish(new StudioApplicationEvent(type, this.logicalTimestamp++, detail).get()); }
}
