import type{Camera,Scene}from"three";import{describe,expect,it}from"vitest";import{ProjectBuilder}from"../../../builder/ProjectBuilder";import{environmentInput,ids,projectInput}from"../../../builder/tests/fixture";import{MobiCopilot}from"../../../copilot/MobiCopilot";import{MobiOrigin}from"../../../origin/MobiOrigin";import{PresentationCore}from"../../../presentation/PresentationCore";import{MobiStudio}from"../../../studio/MobiStudio";import{SyncManager}from"../../../sync/SyncManager";import{Viewer}from"../../../viewer/Viewer";import type{FrameScheduler,RenderBackend}from"../../../viewer/interfaces/ViewerTypes";import{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import{WallsController}from"../src/WallsController";import type{WallDescriptor}from"../src/WallTypes";
class B implements RenderBackend{render(_s:Scene,_c:Camera){}setSize(){}dispose(){}}class S implements FrameScheduler{request(){return 1}cancel(){}}
const wid=(n:number)=>`10000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;const w=(id:string,sx:number,sz:number,ex:number,ez:number):WallDescriptor=>({id,environmentId:ids.environment,start:{x:sx,y:0,z:sz},end:{x:ex,y:0,z:ez},height:2700,thickness:100,finish:"paint"});
function setup(){const origin=new MobiOrigin(),foundation=new MobiStudio(origin),p=new PresentationCore();p.createSession("p");const viewer=new Viewer(p,new B(),new S()),copilot=new MobiCopilot(origin,foundation),sync=new SyncManager(origin),studio=new MobiStudioApplication({origin,foundation,presentation:p,viewer,copilot,sync});studio.startSession("s");foundation.openProject(JSON.stringify(new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).build()));return{c:new WallsController(studio),origin,foundation}}
describe("mobi-studio-walls",()=>{
 it("creates, edits dimensions and deletes a wall transactionally",()=>{const{c,origin}=setup(),a=w(wid(1),0,0,4000,0);expect(c.create(a,"u",1).code).toBe("COMMITTED");a.height=3000;a.thickness=120;expect(c.update(a,"u",2).success).toBe(true);expect(origin.getProject().environments[0]!.architectures[0]!.size).toMatchObject({height:3000,depth:120});expect(c.delete(ids.environment,a.id,"u",3).success).toBe(true);expect(origin.getProject().environments[0]!.architectures).toHaveLength(0)});
 it("rejects zero and duplicate walls",()=>{const{c}=setup();expect(c.create(w(wid(1),0,0,0,0),"u",1).code).toBe("ZERO_LENGTH_WALL");expect(c.create(w(wid(2),0,0,2,0),"u",2).success).toBe(true);expect(c.create(w(wid(2),0,1,2,1),"u",3).code).toBe("TRANSACTION_ROLLED_BACK");expect(c.create(w(wid(3),2,0,0,0),"u",4).code).toBe("TRANSACTION_ROLLED_BACK")});
 it("splits and merges collinear walls",()=>{const{c,origin}=setup(),a=w(wid(1),0,0,10,0);c.create(a,"u",1);expect(c.split(ids.environment,a.id,{x:5,y:0,z:0},[wid(2),wid(3)],"u",2).success).toBe(true);expect(origin.getProject().environments[0]!.architectures).toHaveLength(2);expect(c.merge(ids.environment,[wid(2),wid(3)],wid(4),"u",3).success).toBe(true);expect(origin.getProject().environments[0]!.architectures[0]!.size.width).toBe(10)});
 it("rejects invalid split and non-collinear merge",()=>{const{c}=setup();c.create(w(wid(1),0,0,10,0),"u",1);c.create(w(wid(2),10,0,10,10),"u",2);expect(c.split(ids.environment,wid(1),{x:4,y:0,z:2},[wid(3),wid(4)],"u",3).code).toBe("SPLIT_POINT_OUTSIDE_WALL");expect(c.merge(ids.environment,[wid(1),wid(2)],wid(5),"u",4).code).toBe("WALLS_NOT_COLLINEAR")});
 it.each([["L",2],["T",3],["X",4]]as const)("creates %s connections",(kind,count)=>{const{c}=setup();for(let i=0;i<count;i++)c.create(w(wid(i+1),i*10,0,i*10+5,0),"u",i+1);expect(c.connect(kind,ids.environment,Array.from({length:count},(_,i)=>wid(i+1)),{x:20,y:0,z:20},"u",20).success).toBe(true)});
 it("supports volatile preview, cancel, commit and concurrency guard",()=>{const{c}=setup(),a=w(wid(1),0,0,10,0);expect(c.preview("CREATE_WALL",[a]).success).toBe(true);expect(c.preview("CREATE_WALL",[a]).code).toBe("EDIT_ALREADY_ACTIVE");expect(c.cancel().code).toBe("CANCELLED");expect(c.cancel().code).toBe("NO_ACTIVE_EDIT");c.preview("CREATE_WALL",[a]);expect(c.commit("u",1).success).toBe(true);expect(c.commit("u",2).code).toBe("NO_ACTIVE_EDIT")});
 it("rejects missing references and bad connection cardinality",()=>{const{c}=setup();expect(c.delete(ids.environment,wid(9),"u",1).code).toBe("TRANSACTION_ROLLED_BACK");expect(c.connect("L",ids.environment,[],{x:0,y:0,z:0},"u",2).code).toBe("INVALID_CONNECTION_CARDINALITY")});
 it("covers defensive references, dimensions and disconnected geometry",()=>{const{c}=setup(),a=w(wid(1),0,0,5,0),b=w(wid(2),10,0,15,0);expect(c.update(a,"u",1).code).toBe("TRANSACTION_ROLLED_BACK");expect(c.split(ids.environment,wid(9),{x:1,y:0,z:0},[wid(3),wid(4)],"u",2).code).toBe("WALL_NOT_FOUND");expect(c.merge(ids.environment,[wid(8),wid(9)],wid(5),"u",3).code).toBe("WALL_NOT_FOUND");c.create(a,"u",4);c.create(b,"u",5);expect(c.merge(ids.environment,[a.id,b.id],wid(6),"u",6).code).toBe("WALLS_NOT_CONNECTED");expect(c.connect("L",ids.environment,[a.id,wid(9)],{x:5,y:0,z:0},"u",7).code).toBe("WALL_NOT_FOUND");const bad={...a,id:wid(7),height:0};expect(c.preview("CREATE_WALL",[bad]).code).toBe("INVALID_WALL_DIMENSIONS")});
 it("merges reversed collinear orientation and blocks concurrent command",()=>{const{c}=setup(),a=w(wid(1),5,0,0,0),b=w(wid(2),10,0,5,0);c.create(a,"u",1);c.create(b,"u",2);expect(c.merge(ids.environment,[a.id,b.id],wid(3),"u",3).success).toBe(true);const x=w(wid(4),0,1,2,1);c.preview("CREATE_WALL",[x]);expect(c.create(x,"u",4).code).toBe("EDIT_ALREADY_ACTIVE");c.cancel()});
 it("handles absent environments and empty previews defensively",()=>{const{c}=setup(),a=w(wid(1),0,0,1,0);a.environmentId=wid(99);expect(c.create(a,"u",1).code).toBe("TRANSACTION_ROLLED_BACK");expect(c.split(wid(99),wid(1),{x:0,y:0,z:0},[wid(2),wid(3)],"u",2).code).toBe("WALL_NOT_FOUND");expect(c.preview("CREATE_WALL",[]).success).toBe(true);expect(c.commit("u",3).success).toBe(true)});
 it("moves the nearest endpoint of every connected wall to the junction",()=>{const{c,origin}=setup(),junction={x:5,y:0,z:5};c.create(w(wid(1),0,0,4,4),"u",1);c.create(w(wid(2),10,10,6,6),"u",2);expect(c.connect("L",ids.environment,[wid(1),wid(2)],junction,"u",3).success).toBe(true);for(const architecture of origin.getProject().environments[0]!.architectures)expect([architecture.position,architecture.referencePlane]).toContainEqual(junction)});
 it("rejects repeated wall identifiers in a connection",()=>{const{c}=setup();c.create(w(wid(1),0,0,5,0),"u",1);expect(c.connect("L",ids.environment,[wid(1),wid(1)],{x:5,y:0,z:0},"u",2).code).toBe("INVALID_CONNECTION_CARDINALITY")});
});
