import type { Camera, Scene } from "three";
import { ProjectBuilder } from "../../../builder/ProjectBuilder";
import { architectureInput, environmentInput, hardwareInput, ids, infrastructureInput, moduleInput, partInput, projectInput } from "../../../builder/tests/fixture";
import { MobiCopilot } from "../../../copilot/MobiCopilot"; import { MobiOrigin } from "../../../origin/MobiOrigin"; import { PresentationCore } from "../../../presentation/PresentationCore"; import { MobiStudio } from "../../../studio/MobiStudio"; import { SyncManager } from "../../../sync/SyncManager"; import { Viewer } from "../../../viewer/Viewer"; import type { FrameScheduler, RenderBackend } from "../../../viewer/interfaces/ViewerTypes"; import { MobiStudioApplication } from "../../mobi-studio/src/MobiStudioApplication"; import { SpatialTransaction } from "../src/SpatialTransaction";
class Backend implements RenderBackend { render(_scene:Scene,_camera:Camera):void{} setSize():void{} dispose():void{} } class Scheduler implements FrameScheduler { request():unknown{return 1;} cancel():void{} }
export const secondPartId="00000000-0000-4000-8000-000000000088";
export function setup(overlap=false){ const origin=new MobiOrigin(); const foundation=new MobiStudio(origin); const presentation=new PresentationCore(); presentation.createSession("p"); const viewer=new Viewer(presentation,new Backend(),new Scheduler()); const app=new MobiStudioApplication({origin,foundation,presentation,viewer,copilot:new MobiCopilot(origin,foundation),sync:new SyncManager(origin)}); app.startSession("s"); const second={...structuredClone(partInput),id:secondPartId,position:{x:overlap?0:2000,y:0,z:0}}; const project=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addArchitecture(ids.environment,architectureInput).addInfrastructure(ids.environment,infrastructureInput).addModule(ids.environment,moduleInput).addPart(ids.module,partInput).addPart(ids.module,second).addHardware(ids.module,hardwareInput).build(); foundation.openProject(JSON.stringify(project)); presentation.repository.selection.selectMany([ids.part]); return {origin,foundation,presentation,app,spatial:new SpatialTransaction(app,presentation)}; }
export function part(project:ReturnType<MobiOrigin["getProject"]>,id:string=ids.part){return project.environments[0]!.modules[0]!.parts.find(value=>value.id===id)!;}
export { ids };
