import type{Camera,Scene}from"three";import{describe,expect,it}from"vitest";import{ProjectBuilder}from"../../../builder/ProjectBuilder";import{architectureInput,environmentInput,hardwareInput,ids,moduleInput,partInput,projectInput}from"../../../builder/tests/fixture";import{MobiCopilot}from"../../../copilot/MobiCopilot";import{RuleRegistry}from"../../../copilot/rules/RuleRegistry";import{RuleRunner}from"../../../copilot/rules/RuleRunner";import{MobiOrigin}from"../../../origin/MobiOrigin";import{PresentationCore}from"../../../presentation/PresentationCore";import{MobiStudio}from"../../../studio/MobiStudio";import{SyncManager}from"../../../sync/SyncManager";import{Viewer}from"../../../viewer/Viewer";import type{FrameScheduler,RenderBackend}from"../../../viewer/interfaces/ViewerTypes";import{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import{toOpeningArchitecture}from"../../mobi-studio-openings/src/OpeningGeometry";import{encodeAppliance}from"../../mobi-studio-appliances/src/ApplianceCodec";import{toArchitecture}from"../../mobi-studio-walls/src/WallGeometry";import{WallsController}from"../../mobi-studio-walls/src/WallsController";import{createCognitiveAnalyzer}from"../src/AnalyzerFactory";import{ArchitecturePipeline}from"../src/pipelines/ArchitecturePipeline";import{ProductsPipeline}from"../src/pipelines/ProductsPipeline";import{MaterialsPipeline}from"../src/pipelines/MaterialsPipeline";import{HardwarePipeline}from"../src/pipelines/HardwarePipeline";import{TopologyPipeline}from"../src/pipelines/TopologyPipeline";import{OpeningsPipeline}from"../src/pipelines/OpeningsPipeline";import{TechnicalPointsPipeline}from"../src/pipelines/TechnicalPointsPipeline";import{AppliancesPipeline}from"../src/pipelines/AppliancesPipeline";import{ProductionPipeline}from"../src/pipelines/ProductionPipeline";import{TraceabilityReporter}from"../src/TraceabilityReporter";
class B implements RenderBackend{render(_s:Scene,_c:Camera){}setSize(){}dispose(){}}class S implements FrameScheduler{request(){return 1}cancel(){}}
const wid=(n:number)=>`81000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;const rectangle=()=>[{id:wid(1),start:{x:0,y:0,z:0},end:{x:4000,y:0,z:0}},{id:wid(2),start:{x:4000,y:0,z:0},end:{x:4000,y:0,z:3000}},{id:wid(3),start:{x:4000,y:0,z:3000},end:{x:0,y:0,z:3000}},{id:wid(4),start:{x:0,y:0,z:3000},end:{x:0,y:0,z:0}}].map(v=>({...v,environmentId:ids.environment,height:2700,thickness:100,finish:"paint"}));
function setup(){const origin=new MobiOrigin(),foundation=new MobiStudio(origin),presentation=new PresentationCore();presentation.createSession("p");const studio=new MobiStudioApplication({origin,foundation,presentation,viewer:new Viewer(presentation,new B(),new S()),copilot:new MobiCopilot(origin,foundation),sync:new SyncManager(origin)});studio.startSession("s");const project=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).build();project.environments[0]!.architectures=rectangle().map(toArchitecture);foundation.openProject(JSON.stringify(project));const runner=new RuleRunner(new RuleRegistry());return{studio,presentation,foundation,origin,runner,analyzer:createCognitiveAnalyzer(studio,presentation,runner)}}
describe("cognitive analyzer",()=>{
 it("produces a healthy deterministic report without false positives",()=>{const s=setup(),before=s.foundation.getProject(),a=s.analyzer.analyze(1),b=s.analyzer.analyze(1);expect(a.status).toBe("HEALTHY");expect(a.diagnostics).toEqual([]);expect(a.checklist).toHaveLength(9);expect(a).toEqual(b);expect(s.foundation.getProject()).toEqual(before)});
 it("diagnoses an Environment without architecture",()=>{const s=setup(),p=s.foundation.getProject();p.environments[0]!.architectures=[];const d=new ArchitecturePipeline().run(p,2);expect(d[0]).toMatchObject({origin:"architecture",ruleId:"ARCH_ENVIRONMENT_WITHOUT_ARCHITECTURE",severity:"warning",entityId:ids.environment})});
 it("runs product, material and hardware pipelines independently",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,m={...moduleInput,parts:[{...partInput,materialId:""}],hardwares:[{...hardwareInput,catalogId:""}]},copy={...m,id:wid(20)};e.modules.push(m,copy);expect(new ProductsPipeline().run(p,3)[0]!.ruleId).toBe("PRODUCT_DUPLICATE_MODULE_CODE");expect(new MaterialsPipeline().run(p,3)).toHaveLength(2);expect(new HardwarePipeline().run(p,3)).toHaveLength(2)});
 it("diagnoses formal-room topology and ignores draft topology",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!;e.architectures.pop();expect(new TopologyPipeline().run(p,4)).toEqual([]);e.code="ROOM:OPEN";expect(new TopologyPipeline().run(p,4).some(d=>d.ruleId==="TOPOLOGY_OPEN_LOOP")).toBe(true)});
 it("diagnoses orphan Openings and Technical Points",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,host=e.architectures[0]!,opening=toOpeningArchitecture({id:wid(30),environmentId:e.id,hostWallId:host.id,offset:500,sillHeight:500,width:500,height:1000,finish:"raw"},host);opening.hostId=wid(99);e.architectures.push(opening);e.infrastructures.push({id:wid(31),parentId:e.id,hostId:wid(99),category:"electrical",type:"technical:outlet",position:{x:0,y:0,z:0}});expect(new OpeningsPipeline().run(p,5)[0]!.ruleId).toBe("OPENING_WITHOUT_WALL");expect(new TechnicalPointsPipeline().run(p,5)[0]!.ruleId).toBe("TECHNICAL_POINT_WITHOUT_SURFACE")});
 it("diagnoses appliance collision volumes",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!;e.infrastructures.push(...encodeAppliance({id:wid(40),clearanceId:wid(41),environmentId:e.id,kind:"generic",category:"electrical",position:{x:0,y:0,z:0},collisionVolume:{width:500,height:500,depth:500},clearanceVolume:{width:600,height:600,depth:600}}));expect(new AppliancesPipeline().run(p,6).some(d=>d.ruleId==="APPLIANCE_COLLISION_WALL")).toBe(true)});
 it("converts public RuleRunner results into production diagnostics",()=>{const s=setup(),registry=new RuleRegistry();registry.registerRule({id:"audit",displayName:"Audit",description:"Audit",severity:"warning",enabled:true,analyze:()=>[{code:"PRODUCTION_AUDIT",severity:"warning",path:`/modules/${ids.module}`,message:"audit"}]});const d=new ProductionPipeline(new RuleRunner(registry)).run(s.foundation.getProject(),7)[0]!;expect(d).toMatchObject({origin:"production",ruleId:"PRODUCTION_AUDIT",entityId:ids.module,message:"audit"})});
 it("monitors EventBus, TransactionCoordinator, Presentation and project changes",()=>{const s=setup();s.analyzer.monitors.start();s.studio.events.publish({type:"THEME_CHANGED",logicalTimestamp:0});s.presentation.controller.notify("ViewChanged",1);const walls=new WallsController(s.studio),wall={...rectangle()[0]!,id:wid(50),start:{x:500,y:0,z:500},end:{x:1000,y:0,z:500}};walls.create(wall,"u",1);s.analyzer.analyze(2);const p=s.foundation.getProject();p.displayName="Observed change";s.foundation.openProject(JSON.stringify(p));s.analyzer.analyze(3);s.analyzer.monitors.stop();const records=s.analyzer.monitors.get();expect(records.some(r=>r.source==="event-bus")).toBe(true);expect(records.some(r=>r.source==="presentation")).toBe(true);expect(records.some(r=>r.source==="transaction"&&r.type==="TRANSACTION_COMMITTED")).toBe(true);expect(records.filter(r=>r.source==="project").map(r=>r.type)).toEqual(["PROJECT_OBSERVED","PROJECT_CHANGED"]);s.analyzer.monitors.clear();expect(s.analyzer.monitors.get()).toEqual([])});
 it("provides complete traceability and immutable history snapshots",()=>{const s=setup(),p=s.foundation.getProject();p.environments[0]!.architectures=[];s.foundation.openProject(JSON.stringify(p));const report=s.analyzer.analyze(9),trace=new TraceabilityReporter().render(report)[0]!;expect(trace).toMatchObject({origin:"architecture",ruleId:"ARCH_ENVIRONMENT_WITHOUT_ARCHITECTURE",projectId:ids.project,sequence:9});const history=s.analyzer.history();history[0]!.diagnostics.length=0;expect(s.analyzer.history()[0]!.diagnostics).toHaveLength(1)});
});
