import type{Architecture,Environment,Size3D,Vector3}from"../../../builder/types/ProjectTypes";import{fromArchitecture}from"../../mobi-studio-walls/src/WallGeometry";import{decodeAppliance,isAppliance,isClearance}from"./ApplianceCodec";import type{ApplianceDescriptor,CollisionCode,CollisionIssue,CollisionResult}from"./ApplianceTypes";
type Box={min:Vector3;max:Vector3};const E=1e-7,box=(p:Vector3,s:Size3D):Box=>({min:p,max:{x:p.x+s.width,y:p.y+s.height,z:p.z+s.depth}}),hit=(a:Box,b:Box)=>Math.min(a.max.x,b.max.x)-Math.max(a.min.x,b.min.x)>E&&Math.min(a.max.y,b.max.y)-Math.max(a.min.y,b.min.y)>E&&Math.min(a.max.z,b.max.z)-Math.max(a.min.z,b.min.z)>E;
export class CollisionEngine{
 validate(environment:Environment):CollisionResult{const issues:CollisionIssue[]=[],appliances=this.appliances(environment),walls=environment.architectures.filter(a=>a.type==="wall"),openings=environment.architectures.filter(a=>a.type==="opening"),bounds=this.bounds(walls);for(const a of appliances){if(!this.positive(a.collisionVolume)||!this.positive(a.clearanceVolume))issues.push(this.issue("INVALID_APPLIANCE_VOLUME",[a.id]));if(a.hostSurfaceId&&!environment.architectures.some(v=>v.id===a.hostSurfaceId))issues.push(this.issue("APPLIANCE_HOST_NOT_FOUND",[a.id,a.hostSurfaceId]));const b=box(a.position,a.collisionVolume);if(bounds){const overlap=hit(b,bounds),inside=this.inside(b,bounds);if(!overlap)issues.push(this.issue("APPLIANCE_OUTSIDE_ENVIRONMENT",[a.id]));else if(!inside)issues.push(this.issue("APPLIANCE_PARTIALLY_EXTERNAL",[a.id]))}for(const wall of walls)if(hit(b,this.wallBox(wall))){issues.push(this.issue("APPLIANCE_COLLISION_WALL",[a.id,wall.id]));issues.push(this.issue("APPLIANCE_INVADES_WALL",[a.id,wall.id]))}for(const opening of openings)if(hit(b,this.openingBox(opening,walls.find(w=>w.id===opening.hostId))))issues.push(this.issue("APPLIANCE_BLOCKS_OPENING",[a.id,opening.id]))}
 for(let i=0;i<appliances.length;i++)for(let j=i+1;j<appliances.length;j++){const a=appliances[i]!,b=appliances[j]!;if(hit(box(a.position,a.collisionVolume),box(b.position,b.collisionVolume))){issues.push(this.issue("APPLIANCE_COLLISION_APPLIANCE",[a.id,b.id]));issues.push(this.issue("APPLIANCE_OVERLAP",[a.id,b.id]))}if(hit(box(a.position,a.clearanceVolume),box(b.position,b.collisionVolume))||hit(box(b.position,b.clearanceVolume),box(a.position,a.collisionVolume)))issues.push(this.issue("CLEARANCE_INSUFFICIENT",[a.id,b.id]))}return{valid:issues.length===0,issues:this.unique(issues)}}
 private appliances(e:Environment){return e.infrastructures.filter(isAppliance).flatMap(v=>{const c=e.infrastructures.find(x=>isClearance(x)&&x.hostId===v.id);return c?[decodeAppliance(v,c)]:[]})}
 private bounds(walls:Architecture[]):Box|undefined{if(!walls.length)return undefined;const points=walls.flatMap(w=>[w.position,w.referencePlane]),height=Math.max(...walls.map(w=>w.position.y+w.size.height));return{min:{x:Math.min(...points.map(p=>p.x)),y:Math.min(...points.map(p=>p.y)),z:Math.min(...points.map(p=>p.z))},max:{x:Math.max(...points.map(p=>p.x)),y:height,z:Math.max(...points.map(p=>p.z))}}}
 private wallBox(w:Architecture):Box{const d=fromArchitecture(w),half=w.size.depth/2;return{min:{x:Math.min(d.start.x,d.end.x)-half,y:d.start.y,z:Math.min(d.start.z,d.end.z)-half},max:{x:Math.max(d.start.x,d.end.x)+half,y:d.start.y+d.height,z:Math.max(d.start.z,d.end.z)+half}}}
 private openingBox(o:Architecture,w?:Architecture):Box{if(!w)return box(o.position,o.size);const d=fromArchitecture(w),length=Math.hypot(d.end.x-d.start.x,d.end.z-d.start.z),ux=length?Math.abs((d.end.x-d.start.x)/length):1,uz=length?Math.abs((d.end.z-d.start.z)/length):0;return box({x:o.position.x-w.size.depth/2,z:o.position.z-w.size.depth/2,y:o.position.y},{width:o.size.width*ux+w.size.depth,height:o.size.height,depth:o.size.width*uz+w.size.depth})}
 private positive(s:Size3D){return s.width>0&&s.height>0&&s.depth>0}private inside(a:Box,b:Box){return a.min.x>=b.min.x-E&&a.min.y>=b.min.y-E&&a.min.z>=b.min.z-E&&a.max.x<=b.max.x+E&&a.max.y<=b.max.y+E&&a.max.z<=b.max.z+E}private issue(code:CollisionCode,ids:string[]):CollisionIssue{return{code,ids,path:"/infrastructures"}}private unique(v:CollisionIssue[]){const s=new Set<string>();return v.filter(i=>{const k=i.code+i.ids.join();if(s.has(k))return false;s.add(k);return true})}}

