import{describe,expect,it,vi}from"vitest";import{ProjectBuilder,environmentInput,ids,moduleInput,partInput,projectInput}from"./fixtures";import{InteractionEngine}from"../src/interaction-engine/InteractionEngine";import{IntentFactory}from"../src/intent-factory/IntentFactory";import type{OperationResolver,RuleRunnerReadPort,TransactionCoordinatorPort}from"../src/interaction/Phase2Types";import{SceneGraph}from"../src/mobi-studio-scene-graph/SceneGraph";import{SelectionController}from"../src/mobi-studio-selection/SelectionController";import{PreviewManager}from"../src/preview-manager/PreviewManager";import{TransactionBridge}from"../src/transaction-bridge/TransactionBridge";
function project(){return new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).addModule(ids.environment,moduleInput).addPart(ids.module,partInput).build()}function setup(findings:readonly unknown[]=[]){const p=project(),scene=new SceneGraph();scene.build(p);const renderer={render:vi.fn()},preview=new PreviewManager(scene,renderer),rules:RuleRunnerReadPort={analyze:vi.fn(()=>findings)},coordinator:TransactionCoordinatorPort={execute:vi.fn(()=>({success:true,transactionId:"tx-1"}))},resolver:OperationResolver={resolve:vi.fn(()=>vi.fn())},bridge=new TransactionBridge({read:()=>structuredClone(p)},rules,coordinator,resolver,preview),selection=new SelectionController(scene),factory=new IntentFactory(),engine=new InteractionEngine(factory,preview,bridge,selection);return{p,scene,renderer,preview,rules,coordinator,resolver,bridge,selection,factory,engine}}
describe("Mobi Studio interaction and transactions",()=>{
 it("generates all deterministic PENDING intents statelessly",()=>{const f=new IntentFactory(),values=[f.move(ids.part,1,{x:1,y:2,z:3}),f.createEntity("new",2,{kind:"module"}),f.delete(ids.part,3),f.rotate(ids.part,4,{x:0,y:90,z:0}),f.resize(ids.part,5,{width:1,height:2,depth:3}),f.select(ids.part,6)];expect(values.map(v=>v.kind)).toEqual(["MOVE","CREATE","DELETE","ROTATE","RESIZE","SELECT"]);expect(values.every(v=>v.status==="PENDING")).toBe(true);expect(f.move(ids.part,1,{x:1,y:2,z:3})).toEqual(values[0]);expect(()=>f.select("",0)).toThrow("INVALID_INTENT_INPUT");expect(()=>f.select(ids.part,-1)).toThrow("INVALID_INTENT_INPUT");expect(()=>f.select(ids.part,1.2)).toThrow("INVALID_INTENT_INPUT")});
 it("creates a move preview without mutating permanent Scene Graph",()=>{const s=setup(),before=s.scene.get(ids.part)!,intent=s.factory.move(ids.part,1,{x:10,y:20,z:30}),state=s.preview.create(intent);expect(state.before).toEqual(before);expect(state.after?.position).toEqual({x:before.position.x+10,y:before.position.y+20,z:before.position.z+30});expect(s.scene.get(ids.part)).toEqual(before);expect(s.renderer.render).toHaveBeenCalled()});
 it("previews resize, rotate, delete and create overlays",()=>{const s=setup();expect(s.preview.create(s.factory.resize(ids.part,1,{width:2,height:3,depth:4})).after?.size).toEqual({width:2,height:3,depth:4});expect(s.preview.create(s.factory.rotate(ids.part,2,{x:0,y:1,z:0})).after?.materialKey).toContain("rotation-preview");expect(s.preview.create(s.factory.delete(ids.part,3)).after).toBeNull();const created=s.preview.create(s.factory.createEntity("new",4,{parentId:ids.environment,kind:"module",position:{x:1,y:2,z:3}}));expect(created.after).toMatchObject({entityId:"new",parentId:ids.environment,kind:"module",position:{x:1,y:2,z:3}});expect(s.scene.has("new")).toBe(false)});
 it("updates, rolls back and discards preview immediately",()=>{const s=setup(),a=s.factory.move(ids.part,1,{x:1,y:0,z:0});s.preview.create(a);expect(s.preview.update(s.factory.move(ids.part,1,{x:5,y:0,z:0})).after?.position.x).toBe(5);expect(()=>s.preview.update(s.factory.move(ids.part,2,{x:1,y:0,z:0}))).toThrow("PREVIEW_NOT_ACTIVE");expect(s.preview.rollback()?.intentId).toBe(a.id);expect(s.preview.get()).toBeUndefined();expect(s.preview.discard()).toBe(false);s.preview.create(a);expect(s.preview.discard()).toBe(true);expect(s.preview.snapshot()).toEqual(s.scene.snapshot())});
 it("handles preview of a missing non-create entity without persisting it",()=>{const s=setup(),intent=s.factory.move("missing",1,{x:1,y:1,z:1});expect(s.preview.create(intent).after).toBeNull();expect(s.preview.snapshot()).toEqual(s.scene.snapshot())});
 it("routes valid intents exclusively through TransactionCoordinator",()=>{const s=setup(),intent=s.factory.move(ids.part,7,{x:1,y:0,z:0});s.preview.create(intent);const result=s.bridge.execute(intent);expect(result).toEqual({success:true,code:"COMMITTED",transactionId:"tx-1"});expect(s.rules.analyze).toHaveBeenCalledOnce();expect(s.resolver.resolve).toHaveBeenCalledWith(intent);expect(s.coordinator.execute).toHaveBeenCalledOnce();const command=(s.coordinator.execute as any).mock.calls[0][0];expect(command).toMatchObject({id:`request:${intent.id}`,operationName:"STUDIO_MOVE",entityId:ids.part});command.operation({});command.preview.apply({});command.preview.revert({});expect(s.preview.get()).toBeUndefined()});
 it("rolls back failed coordinator results and always discards preview",()=>{const s=setup();(s.coordinator.execute as any).mockReturnValue({success:false});const intent=s.factory.delete(ids.part,2);s.preview.create(intent);expect(s.bridge.execute(intent)).toEqual({success:false,code:"ROLLED_BACK"});expect(s.preview.get()).toBeUndefined()});
 it("blocks commits when RuleRunner reports findings",()=>{const s=setup([{code:"BLOCK"}]),intent=s.factory.resize(ids.part,2,{width:1,height:1,depth:1});s.preview.create(intent);expect(s.bridge.execute(intent)).toEqual({success:false,code:"RULE_BLOCKED"});expect(s.coordinator.execute).not.toHaveBeenCalled();expect(s.preview.get()).toBeUndefined()});
 it("treats SelectionIntent as visual-only",()=>{const s=setup(),intent=s.factory.select(ids.part,1);s.preview.create(s.factory.move(ids.part,0,{x:1,y:0,z:0}));expect(s.bridge.execute(intent)).toEqual({success:true,code:"COMMITTED"});expect(s.rules.analyze).not.toHaveBeenCalled();expect(s.coordinator.execute).not.toHaveBeenCalled();expect(s.preview.get()).toBeUndefined()});
 it("manages the full interaction lifecycle",()=>{const s=setup(),input={source:"CANVAS"as const,command:"MOVE"as const,entityId:ids.part,sequence:1,payload:{delta:{x:1,y:0,z:0}}};expect((s.engine.capture(input)as any).kind).toBe("MOVE");expect(s.engine.getState()).toMatchObject({state:"PREVIEW",ownsUndoStack:false});expect(()=>s.engine.capture(input)).toThrow("INTERACTION_BUSY");expect(()=>s.engine.update({...input,sequence:2})).toThrow("INTERACTION_ID_MISMATCH");expect(s.engine.update({...input,payload:{delta:{x:2,y:0,z:0}}})).toMatchObject({active:true});expect(s.engine.commit()).toMatchObject({success:true,code:"COMMITTED"});expect(s.engine.getState().state).toBe("IDLE");expect(()=>s.engine.commit()).toThrow("INTERACTION_NOT_PREVIEWING")});
 it("supports cancel and visual selection commands",()=>{const s=setup(),move={source:"UI"as const,command:"DELETE"as const,entityId:ids.part,sequence:1};s.engine.capture(move);expect(s.engine.cancel()).toBe(true);expect(s.engine.cancel()).toBe(false);const selected=s.engine.capture({source:"CANVAS",command:"SELECT",entityId:ids.part,sequence:2});expect(selected).toEqual({success:true,code:"COMMITTED"});expect(s.selection.get().entityId).toBe(ids.part);expect(()=>s.engine.update(move)).toThrow("INTERACTION_NOT_PREVIEWING")});
 it("does not create a private undo/redo stack and emits RfE requirement",()=>{const s=setup();expect(s.engine.getState().ownsUndoStack).toBe(false);expect(()=>s.bridge.requestUndo()).toThrow("RFE_REQUIRED:TRANSACTION_COORDINATOR_UNDO");expect(()=>s.bridge.requestRedo()).toThrow("RFE_REQUIRED:TRANSACTION_COORDINATOR_REDO")});
});
