import type{Camera,Scene}from"three";import{describe,expect,it}from"vitest";import{ProjectBuilder}from"../../../builder/ProjectBuilder";import{environmentInput,ids,projectInput}from"../../../builder/tests/fixture";import{MobiCopilot}from"../../../copilot/MobiCopilot";import{RuleRegistry}from"../../../copilot/rules/RuleRegistry";import{RuleRunner}from"../../../copilot/rules/RuleRunner";import{MobiOrigin}from"../../../origin/MobiOrigin";import{PresentationCore}from"../../../presentation/PresentationCore";import{MobiStudio}from"../../../studio/MobiStudio";import{SyncManager}from"../../../sync/SyncManager";import{Viewer}from"../../../viewer/Viewer";import type{FrameScheduler,RenderBackend}from"../../../viewer/interfaces/ViewerTypes";import{MobiStudioApplication}from"../../mobi-studio/src/MobiStudioApplication";import{toArchitecture}from"../../mobi-studio-walls/src/WallGeometry";import{TechnicalPointRule}from"../src/TechnicalPointRule";import type{TechnicalPointDescriptor,TechnicalPointKind}from"../src/TechnicalPointTypes";import{TechnicalPointValidator}from"../src/TechnicalPointValidator";import{TechnicalPointsController}from"../src/TechnicalPointsController";
import{fromInfrastructure,toInfrastructure}from"../src/TechnicalPointCodec";
class B implements RenderBackend{render(_s:Scene,_c:Camera){}setSize(){}dispose(){}}class S implements FrameScheduler{request(){return 1}cancel(){}}
const wallId="61000000-0000-4000-8000-000000000001",tid=(n:number)=>`62000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;const wall={id:wallId,environmentId:ids.environment,start:{x:0,y:0,z:0},end:{x:4000,y:0,z:0},height:2700,thickness:100,finish:"paint"};
const point=(kind:TechnicalPointKind="outlet",n=1):TechnicalPointDescriptor=>({id:tid(n),environmentId:ids.environment,hostSurfaceId:wallId,kind,category:kind==="cold_water"||kind==="hot_water"?"water":kind==="sewer"?"sewer":kind==="gas"?"gas":kind==="internet"||kind==="tv"?"data":kind==="exhaust"?"hvac":"electrical",position:{x:1000,y:1000,z:0},...(kind==="custom"?{customType:"sensor"}:{})});
function setup(){const origin=new MobiOrigin(),foundation=new MobiStudio(origin),p=new PresentationCore();p.createSession("p");const studio=new MobiStudioApplication({origin,foundation,presentation:p,viewer:new Viewer(p,new B(),new S()),copilot:new MobiCopilot(origin,foundation),sync:new SyncManager(origin)});studio.startSession("s");const project=new ProjectBuilder().createProject(projectInput).addEnvironment(environmentInput).build();project.environments[0]!.architectures.push(toArchitecture(wall));foundation.openProject(JSON.stringify(project));const registry=new RuleRegistry();registry.registerRule(new TechnicalPointRule());return{c:new TechnicalPointsController(studio,new RuleRunner(registry)),origin,foundation,studio}}
describe("technical points",()=>{
 it("adds, updates and deletes transactionally",()=>{const{s:c0}= {s:setup()},c=c0.c,v=point();expect(c.add(v,"u",1).success).toBe(true);expect(c.update({...v,position:{x:1500,y:1200,z:0}},"u",2).success).toBe(true);expect(c.get(ids.environment,v.id)!.position.x).toBe(1500);expect(c.delete(ids.environment,v.id,"u",3).success).toBe(true);expect(c.get(ids.environment,v.id)).toBeUndefined()});
 it.each(["outlet","switch","lighting","cold_water","hot_water","sewer","gas","internet","tv","exhaust","custom"]as TechnicalPointKind[])("supports %s",kind=>{const{c}=setup();expect(c.add(point(kind),"u",1).success).toBe(true)});
 it("supports drain category variants",()=>{const{c}=setup();expect(c.add({...point("drain"),category:"water"},"u",1).success).toBe(true)});
 it("requires a valid Wall Floor or Ceiling host",()=>{const{c,foundation}=setup(),p=foundation.getProject(),e=p.environments[0]!,floor={...e.architectures[0]!,id:tid(90),type:"floor"as const,size:{width:4000,height:100,depth:3000},position:{x:0,y:0,z:0}},ceiling={...floor,id:tid(91),type:"ceiling"as const,position:{x:0,y:2700,z:0}};e.architectures.push(floor,ceiling);foundation.openProject(JSON.stringify(p));expect(c.add({...point("outlet",1),hostSurfaceId:""},"u",1).success).toBe(false);expect(c.add({...point("outlet",2),hostSurfaceId:tid(99)},"u",2).success).toBe(false);expect(c.add({...point("outlet",3),hostSurfaceId:floor.id,position:{x:500,y:0,z:500}},"u",3).success).toBe(true);expect(c.add({...point("lighting",4),hostSurfaceId:ceiling.id,position:{x:500,y:2700,z:500}},"u",4).success).toBe(true)});
 it("rejects points outside host bounds and category mismatch",()=>{const{c}=setup();expect(c.add({...point(),position:{x:5000,y:1000,z:0}},"u",1).success).toBe(false);expect(c.add({...point(),position:{x:1000,y:3000,z:0}},"u",2).success).toBe(false);expect(c.add({...point("gas"),category:"electrical"},"u",3).success).toBe(false)});
 it("rejects duplicate identity and missing update/delete",()=>{const{c}=setup(),v=point();c.add(v,"u",1);expect(c.add(v,"u",2).success).toBe(false);expect(c.update({...v,id:tid(99)},"u",3).success).toBe(false);expect(c.delete(ids.environment,tid(99),"u",4).success).toBe(false)});
 it("rolls back on RuleRunner rejection",()=>{const s=setup(),registry=new RuleRegistry();registry.registerRule({id:"reject",displayName:"R",description:"R",severity:"error",enabled:true,analyze:()=>[{code:"R",severity:"error",path:"/",message:"R"}]});const c=new TechnicalPointsController(s.studio,new RuleRunner(registry)),before=s.origin.getProject();expect(c.add(point(),"u",1).success).toBe(false);expect(s.origin.getProject()).toEqual(before)});
 it("validates serialized orphan points",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!;e.infrastructures.push({id:tid(1),parentId:e.id,hostId:tid(99),category:"electrical",type:"technical:outlet",position:{x:0,y:0,z:0}});expect(new TechnicalPointValidator().validateEnvironment(e).valid).toBe(false)});
 it("covers codec defaults, custom labels and mandatory host guard",()=>{const custom=point("custom");expect(fromInfrastructure(toInfrastructure(custom)).customType).toBe("sensor");const encoded=toInfrastructure({...custom,customType:""});expect(fromInfrastructure(encoded).customType).toBe("custom");const unknown=fromInfrastructure({...encoded,hostId:null,type:"technical"});expect(unknown.hostSurfaceId).toBe("");expect(unknown.kind).toBe("custom");expect(unknown.customType).toBe("custom");expect(()=>toInfrastructure({...point(),hostSurfaceId:""})).toThrow("TECHNICAL_POINT_WITHOUT_SURFACE")});
 it("rejects Opening as a host and off-plane Floor points",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,opening={...e.architectures[0]!,id:tid(90),type:"opening"as const,hostId:wallId},floor={...e.architectures[0]!,id:tid(91),type:"floor"as const,size:{width:1000,height:10,depth:1000},position:{x:0,y:0,z:0}};e.architectures.push(opening,floor);s.foundation.openProject(JSON.stringify(p));expect(s.c.add({...point(),hostSurfaceId:opening.id},"u",1).success).toBe(false);expect(s.c.add({...point(),hostSurfaceId:floor.id,position:{x:2000,y:0,z:0}},"u",2).success).toBe(false);expect(s.c.add({...point(),hostSurfaceId:floor.id,position:{x:500,y:10,z:500}},"u",3).success).toBe(false)});
 it("covers degenerate Wall and negative-side bounds",()=>{const s=setup(),p=s.foundation.getProject(),e=p.environments[0]!,host=e.architectures[0]!;host.referencePlane=structuredClone(host.position);s.foundation.openProject(JSON.stringify(p));expect(s.c.add({...point(),position:{x:0,y:0,z:0}},"u",1).success).toBe(false);const t=setup();expect(t.c.add({...point(),position:{x:-1,y:100,z:0}},"u",2).success).toBe(false)});
 it("handles missing environments and invalid committed updates defensively",()=>{const s=setup(),v=point();expect(s.c.add({...v,environmentId:tid(99)},"u",1).success).toBe(false);expect(s.c.get(tid(99),v.id)).toBeUndefined();s.c.add(v,"u",2);const before=s.origin.getProject();expect(s.c.update({...v,category:"gas"},"u",3).success).toBe(false);expect(s.origin.getProject()).toEqual(before)});
});
